//! MockBitget implementation for testing AP/CEX interactions
//!
//! Simulates Bitget exchange order placement and fills with configurable
//! spread, latency, and failure injection.

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use ethers::types::U256;
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use tokio::sync::{Mutex, RwLock};

use crate::error::Error;
use crate::traits::APClient;
use crate::types::{Fill, OrderId, OrderStatus, Side, TxHash};

use super::MockError;

/// Spread configuration for different asset types
#[derive(Debug, Clone)]
pub struct SpreadConfig {
    /// Spread in basis points (1 bp = 0.01%)
    pub spread_bps: u32,
}

impl SpreadConfig {
    /// Stablecoin spread (5 bps = 0.05%)
    pub const STABLECOIN: SpreadConfig = SpreadConfig { spread_bps: 5 };
    /// Major asset spread (10 bps = 0.10%)
    pub const MAJOR: SpreadConfig = SpreadConfig { spread_bps: 10 };
    /// Other asset spread (25 bps = 0.25%)
    pub const OTHER: SpreadConfig = SpreadConfig { spread_bps: 25 };
}

/// Order in the mock order book
#[derive(Debug, Clone)]
pub struct MockOrder {
    pub id: OrderId,
    pub pair: String,
    pub side: Side,
    pub amount: U256,
    pub price: U256,
    pub status: OrderStatus,
    pub filled_amount: U256,
    pub created_at: u64,
}

/// Fill generated by the mock
#[derive(Debug, Clone)]
pub struct MockFill {
    pub order_id: OrderId,
    pub fill_price: U256,
    pub fill_amount: U256,
    pub timestamp: u64,
}

/// Internal state for MockBitget
#[derive(Debug, Default)]
struct MockBitgetState {
    /// Orders by ID
    orders: HashMap<OrderId, MockOrder>,
    /// Fills by order ID
    fills: HashMap<OrderId, Vec<MockFill>>,
    /// Balances by asset
    balances: HashMap<String, U256>,
}

/// Configuration for MockBitget behavior
#[derive(Debug, Clone)]
pub struct MockBitgetConfig {
    /// Latency to add to all operations
    pub latency: Option<Duration>,
    /// Random failure rate (0.0-1.0)
    pub failure_rate: f64,
    /// Force next operation to fail with this error
    pub next_error: Option<MockError>,
    /// Spread configuration per pair
    pub spreads: HashMap<String, SpreadConfig>,
    /// Order book depth
    pub depth: U256,
    /// Fill delay (default 100ms)
    pub fill_delay: Duration,
    /// Random seed for reproducibility
    pub seed: Option<u64>,
}

impl Default for MockBitgetConfig {
    fn default() -> Self {
        Self {
            latency: Some(Duration::from_millis(100)), // Default latency
            failure_rate: 0.0,
            next_error: None,
            spreads: HashMap::new(),
            depth: U256::from(1_000_000u64) * U256::exp10(18), // 1M depth
            fill_delay: Duration::from_millis(100),
            seed: None,
        }
    }
}

/// Mock implementation of Bitget exchange client
///
/// Simulates order placement and fill mechanics with configurable
/// spread based on asset type.
pub struct MockBitget {
    state: Arc<RwLock<MockBitgetState>>,
    config: Arc<RwLock<MockBitgetConfig>>,
    order_counter: AtomicU64,
    /// Shutdown flag for cancelling background fill tasks
    shutdown: Arc<AtomicBool>,
    /// Seeded RNG for reproducible failure injection
    rng: Arc<Mutex<StdRng>>,
}

impl MockBitget {
    /// Check for injected errors or random failures
    async fn maybe_fail(&self) -> Result<(), Error> {
        let mut config = self.config.write().await;

        // Check for forced next error
        if let Some(err) = config.next_error.take() {
            return Err(err.into());
        }

        // Check for random failure
        if config.failure_rate > 0.0 {
            let mut rng = self.rng.lock().await;
            if rng.gen::<f64>() < config.failure_rate {
                return Err(MockError::SimulatedFailure(config.failure_rate).into());
            }
        }

        Ok(())
    }

    /// Apply configured latency
    async fn apply_latency(&self) {
        let config = self.config.read().await;
        if let Some(latency) = config.latency {
            tokio::time::sleep(latency).await;
        }
    }

    /// Get spread for a pair
    async fn get_spread(&self, pair: &str) -> SpreadConfig {
        let config = self.config.read().await;

        // Check for explicit spread config
        if let Some(spread) = config.spreads.get(pair) {
            return spread.clone();
        }

        // Determine by pair name - check major assets first
        // (BTC/USDC should be major, not stablecoin)
        let pair_upper = pair.to_uppercase();
        if pair_upper.contains("BTC") || pair_upper.contains("ETH") {
            SpreadConfig::MAJOR
        } else if pair_upper.contains("USDC")
            || pair_upper.contains("USDT")
            || pair_upper.contains("DAI")
        {
            SpreadConfig::STABLECOIN
        } else {
            SpreadConfig::OTHER
        }
    }

    /// Set latency for all operations
    pub async fn set_latency(&self, latency: Duration) {
        self.config.write().await.latency = Some(latency);
    }

    /// Set random failure rate (0.0-1.0)
    pub async fn set_failure_rate(&self, rate: f64) {
        self.config.write().await.failure_rate = rate.clamp(0.0, 1.0);
    }

    /// Set spread for a specific pair
    pub async fn set_spread(&self, pair: &str, spread_bps: u32) {
        self.config
            .write()
            .await
            .spreads
            .insert(pair.to_string(), SpreadConfig { spread_bps });
    }

    /// Force the next operation to fail with a specific error
    pub async fn set_next_error(&self, error: MockError) {
        self.config.write().await.next_error = Some(error);
    }

    /// Add balance to an asset
    pub async fn add_balance(&self, asset: &str, amount: U256) {
        let mut state = self.state.write().await;
        let balance = state.balances.entry(asset.to_string()).or_insert(U256::zero());
        *balance = balance.saturating_add(amount);
    }

    /// Simulate a fill for an order (test helper)
    /// Returns false if order not found, already filled, cancelled, or expired
    pub async fn simulate_fill(&self, order_id: OrderId, fill_amount: U256, fill_price: U256) -> bool {
        let mut state = self.state.write().await;

        if let Some(order) = state.orders.get_mut(&order_id) {
            // Can only fill Pending or Batched orders
            if order.status != OrderStatus::Pending && order.status != OrderStatus::Batched {
                return false;
            }

            let fill = MockFill {
                order_id,
                fill_amount,
                fill_price,
                timestamp: std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_secs(),
            };

            order.filled_amount = order.filled_amount.saturating_add(fill_amount);

            if order.filled_amount >= order.amount {
                order.status = OrderStatus::Filled;
            }

            state.fills.entry(order_id).or_default().push(fill);
            true
        } else {
            false
        }
    }

    /// Get all orders (test helper)
    pub async fn get_all_orders(&self) -> Vec<MockOrder> {
        self.state.read().await.orders.values().cloned().collect()
    }

    /// Cancel an order (returns error if already filled or not found)
    pub async fn cancel_order(&self, order_id: OrderId) -> Result<(), Error> {
        self.maybe_fail().await?;
        self.apply_latency().await;

        let mut state = self.state.write().await;
        match state.orders.get_mut(&order_id) {
            Some(order) => {
                if order.status == OrderStatus::Filled {
                    Err(
                        MockError::InvalidState("cannot cancel filled order".to_string())
                            .into(),
                    )
                } else {
                    order.status = OrderStatus::Cancelled;
                    Ok(())
                }
            }
            None => Err(MockError::OrderNotFound(format!("{}", order_id)).into()),
        }
    }

    /// Batch an order (move from Pending to Batched status)
    /// Used to simulate order being included in a batch for execution
    pub async fn batch_order(&self, order_id: OrderId) -> Result<(), Error> {
        let mut state = self.state.write().await;
        match state.orders.get_mut(&order_id) {
            Some(order) => {
                if order.status != OrderStatus::Pending {
                    Err(MockError::InvalidState(format!(
                        "cannot batch order with status {:?}",
                        order.status
                    ))
                    .into())
                } else {
                    order.status = OrderStatus::Batched;
                    Ok(())
                }
            }
            None => Err(MockError::OrderNotFound(format!("{}", order_id)).into()),
        }
    }

    /// Expire an order (move to Expired status)
    /// Used to simulate order deadline passing
    pub async fn expire_order(&self, order_id: OrderId) -> Result<(), Error> {
        let mut state = self.state.write().await;
        match state.orders.get_mut(&order_id) {
            Some(order) => match order.status {
                OrderStatus::Pending | OrderStatus::Batched => {
                    order.status = OrderStatus::Expired;
                    Ok(())
                }
                OrderStatus::Filled => {
                    Err(MockError::InvalidState("cannot expire filled order".to_string()).into())
                }
                OrderStatus::Cancelled => {
                    Err(MockError::InvalidState("cannot expire cancelled order".to_string()).into())
                }
                OrderStatus::Expired => {
                    Err(MockError::InvalidState("order already expired".to_string()).into())
                }
            },
            None => Err(MockError::OrderNotFound(format!("{}", order_id)).into()),
        }
    }
}

#[async_trait]
impl APClient for MockBitget {
    async fn place_order(
        &self,
        pair: String,
        side: Side,
        amount: U256,
        price: U256,
    ) -> Result<OrderId, Error> {
        self.maybe_fail().await?;
        self.apply_latency().await;

        // Validate amount
        if amount.is_zero() {
            return Err(MockError::InvalidState("order amount cannot be zero".to_string()).into());
        }

        // Enforce order book depth limit
        let depth = self.config.read().await.depth;
        if amount > depth {
            return Err(MockError::InvalidState(format!(
                "order amount {} exceeds order book depth {}",
                amount, depth
            ))
            .into());
        }

        // Generate order ID
        let order_id = U256::from(self.order_counter.fetch_add(1, Ordering::SeqCst));

        // Get spread for this pair
        let spread = self.get_spread(&pair).await;

        // Calculate adjusted fill price based on spread (integer math, no float precision loss)
        let spread_adjustment = price * U256::from(spread.spread_bps) / U256::from(10000);
        let fill_price = match side {
            Side::Buy => price.saturating_add(spread_adjustment / U256::from(2)),
            Side::Sell => price.saturating_sub(spread_adjustment / U256::from(2)),
        };

        let order = MockOrder {
            id: order_id,
            pair: pair.clone(),
            side,
            amount,
            price: fill_price,
            status: OrderStatus::Pending,
            filled_amount: U256::zero(),
            created_at: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
        };

        {
            let mut state = self.state.write().await;

            // Enforce balance if balances are configured
            if !state.balances.is_empty() {
                let parts: Vec<&str> = pair.split('/').collect();
                if parts.len() == 2 {
                    let (check_asset, required) = match side {
                        Side::Buy => {
                            // Buying base with quote: cost = amount * price / 10^18
                            let cost = amount
                                .checked_mul(price)
                                .map(|v| v / U256::exp10(18))
                                .unwrap_or(U256::MAX);
                            (parts[1], cost)
                        }
                        Side::Sell => (parts[0], amount),
                    };
                    let balance = state
                        .balances
                        .get(check_asset)
                        .copied()
                        .unwrap_or(U256::zero());
                    if balance < required {
                        return Err(MockError::InsufficientBalance(format!(
                            "{}: need {} have {}",
                            check_asset, required, balance
                        ))
                        .into());
                    }
                    // Deduct balance
                    if let Some(bal) = state.balances.get_mut(check_asset) {
                        *bal = bal.saturating_sub(required);
                    }
                }
            }

            state.orders.insert(order_id, order);
        }

        // Schedule automatic fill after delay
        let state_clone = self.state.clone();
        let config_clone = self.config.clone();
        let shutdown_clone = self.shutdown.clone();
        tokio::spawn(async move {
            let fill_delay = config_clone.read().await.fill_delay;
            tokio::time::sleep(fill_delay).await;

            // Check if shutdown was requested
            if shutdown_clone.load(Ordering::SeqCst) {
                return;
            }

            let mut state = state_clone.write().await;
            if let Some(order) = state.orders.get_mut(&order_id) {
                if order.status == OrderStatus::Pending {
                    order.filled_amount = order.amount;
                    order.status = OrderStatus::Filled;

                    let fill = MockFill {
                        order_id,
                        fill_amount: order.amount,
                        fill_price: order.price,
                        timestamp: std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .unwrap()
                            .as_secs(),
                    };
                    state.fills.entry(order_id).or_default().push(fill);
                }
            }
        });

        Ok(order_id)
    }

    async fn get_fills(&self, order_id: OrderId) -> Result<Vec<Fill>, Error> {
        self.maybe_fail().await?;
        self.apply_latency().await;

        let state = self.state.read().await;
        let fills = state.fills.get(&order_id).cloned().unwrap_or_default();

        // Convert MockFill to Fill
        Ok(fills
            .into_iter()
            .map(|f| Fill {
                order_id: f.order_id,
                fill_price: f.fill_price,
                fill_amount: f.fill_amount,
                cycle_number: U256::zero(),
                tx_hash: TxHash::zero(),
            })
            .collect())
    }

    async fn get_order_status(&self, order_id: OrderId) -> Result<OrderStatus, Error> {
        self.maybe_fail().await?;
        self.apply_latency().await;

        let state = self.state.read().await;
        state
            .orders
            .get(&order_id)
            .map(|o| o.status)
            .ok_or_else(|| MockError::OrderNotFound(format!("{}", order_id)).into())
    }
}

impl Drop for MockBitget {
    fn drop(&mut self) {
        // Signal shutdown to all spawned fill tasks
        self.shutdown.store(true, Ordering::SeqCst);
    }
}

/// Builder for MockBitget
pub struct MockBitgetBuilder {
    balances: HashMap<String, U256>,
    config: MockBitgetConfig,
}

impl MockBitgetBuilder {
    /// Create a new builder with defaults
    pub fn new() -> Self {
        Self {
            balances: HashMap::new(),
            config: MockBitgetConfig::default(),
        }
    }

    /// Add initial balance for an asset
    pub fn with_balance(mut self, asset: &str, amount: U256) -> Self {
        self.balances.insert(asset.to_string(), amount);
        self
    }

    /// Set spread for a pair in basis points
    pub fn with_spread(mut self, pair: &str, spread_bps: u32) -> Self {
        self.config
            .spreads
            .insert(pair.to_string(), SpreadConfig { spread_bps });
        self
    }

    /// Set order book depth
    pub fn with_depth(mut self, depth: U256) -> Self {
        self.config.depth = depth;
        self
    }

    /// Set operation latency
    pub fn with_latency(mut self, latency: Duration) -> Self {
        self.config.latency = Some(latency);
        self
    }

    /// Set random failure rate
    pub fn with_failure_rate(mut self, rate: f64) -> Self {
        self.config.failure_rate = rate.clamp(0.0, 1.0);
        self
    }

    /// Set random seed for reproducibility
    pub fn with_seed(mut self, seed: u64) -> Self {
        self.config.seed = Some(seed);
        self
    }

    /// Set fill delay
    pub fn with_fill_delay(mut self, delay: Duration) -> Self {
        self.config.fill_delay = delay;
        self
    }

    /// Build the MockBitget
    pub fn build(self) -> MockBitget {
        let state = MockBitgetState {
            orders: HashMap::new(),
            fills: HashMap::new(),
            balances: self.balances,
        };

        let rng = match self.config.seed {
            Some(seed) => StdRng::seed_from_u64(seed),
            None => StdRng::from_entropy(),
        };

        MockBitget {
            state: Arc::new(RwLock::new(state)),
            config: Arc::new(RwLock::new(self.config)),
            order_counter: AtomicU64::new(1),
            shutdown: Arc::new(AtomicBool::new(false)),
            rng: Arc::new(Mutex::new(rng)),
        }
    }
}

impl Default for MockBitgetBuilder {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_happy_path_order_fill() {
        let mock = MockBitgetBuilder::new()
            .with_fill_delay(Duration::from_millis(10))
            .with_latency(Duration::from_millis(1))
            .build();

        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await
            .unwrap();

        // Wait for fill
        tokio::time::sleep(Duration::from_millis(50)).await;

        let fills = mock.get_fills(order_id).await.unwrap();
        assert!(!fills.is_empty());

        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Filled);
    }

    #[tokio::test]
    async fn test_zero_amount_order() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .build();

        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::zero(),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await;

        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_failure_rate_and_set_next_error() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .build();

        // Test set_next_error
        mock.set_next_error(MockError::InsufficientBalance("test".to_string()))
            .await;

        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64),
                U256::from(50000u64),
            )
            .await;

        assert!(result.is_err());

        // Test failure rate
        mock.set_failure_rate(1.0).await;

        let result = mock
            .place_order(
                "ETH/USDC".to_string(),
                Side::Sell,
                U256::from(1000u64),
                U256::from(3000u64),
            )
            .await;

        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_latency() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(50))
            .with_fill_delay(Duration::from_millis(1))
            .build();

        let start = std::time::Instant::now();

        let _ = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64),
                U256::from(50000u64),
            )
            .await;

        let elapsed = start.elapsed();
        assert!(elapsed >= Duration::from_millis(50));
    }

    #[tokio::test]
    async fn test_concurrent_order_placements() {
        let mock = Arc::new(
            MockBitgetBuilder::new()
                .with_latency(Duration::from_millis(1))
                .with_fill_delay(Duration::from_millis(10))
                .build(),
        );

        let mut handles = vec![];

        for i in 0..10 {
            let mock_clone = mock.clone();
            handles.push(tokio::spawn(async move {
                mock_clone
                    .place_order(
                        format!("ASSET{}/USDC", i),
                        if i % 2 == 0 { Side::Buy } else { Side::Sell },
                        U256::from(1000u64 + i as u64),
                        U256::from(100u64),
                    )
                    .await
            }));
        }

        let results: Vec<_> = futures::future::join_all(handles).await;

        // All orders should succeed
        for result in results {
            assert!(result.is_ok());
            assert!(result.unwrap().is_ok());
        }

        // All orders should be tracked
        let orders = mock.get_all_orders().await;
        assert_eq!(orders.len(), 10);
    }

    #[tokio::test]
    async fn test_spread_defaults() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .build();

        // Test stablecoin spread
        let spread = mock.get_spread("USDC/USDT").await;
        assert_eq!(spread.spread_bps, 5);

        // Test major asset spread
        let spread = mock.get_spread("BTC/USDC").await;
        assert_eq!(spread.spread_bps, 10);

        let spread = mock.get_spread("ETH/USDT").await;
        assert_eq!(spread.spread_bps, 10);

        // Test other asset spread (pair without major or stablecoin)
        let spread = mock.get_spread("SOL/AVAX").await;
        assert_eq!(spread.spread_bps, 25);
    }

    #[tokio::test]
    async fn test_partial_fill_scenario() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10)) // Long delay - we'll manually fill
            .build();

        let total_amount = U256::from(1000u64) * U256::exp10(18);
        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                total_amount,
                U256::from(50000u64) * U256::exp10(18),
            )
            .await
            .unwrap();

        // Order should be pending initially
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Pending);

        // Simulate partial fill (50% of the order)
        let partial_amount = U256::from(500u64) * U256::exp10(18);
        let fill_price = U256::from(50000u64) * U256::exp10(18);
        let filled = mock.simulate_fill(order_id, partial_amount, fill_price).await;
        assert!(filled, "partial fill should succeed");

        // Should have one fill
        let fills = mock.get_fills(order_id).await.unwrap();
        assert_eq!(fills.len(), 1);
        assert_eq!(fills[0].fill_amount, partial_amount);

        // Status should still be Pending (not fully filled yet)
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Pending);

        // Simulate remaining fill
        let filled = mock.simulate_fill(order_id, partial_amount, fill_price).await;
        assert!(filled, "remaining fill should succeed");

        // Now should be fully filled
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Filled);

        // Should have two fills
        let fills = mock.get_fills(order_id).await.unwrap();
        assert_eq!(fills.len(), 2);
    }

    #[tokio::test]
    async fn test_order_not_found() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .build();

        // Query status of non-existent order
        let result = mock.get_order_status(U256::from(9999u64)).await;
        assert!(result.is_err());

        // Query fills of non-existent order (should return empty, not error)
        let fills = mock.get_fills(U256::from(9999u64)).await.unwrap();
        assert!(fills.is_empty());
    }

    #[tokio::test]
    async fn test_builder_with_balance() {
        let mock = MockBitgetBuilder::new()
            .with_balance("USDC", U256::from(100_000u64) * U256::exp10(18))
            .with_balance("BTC", U256::from(10u64) * U256::exp10(18))
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10))
            .build();

        // Buy 1 BTC at 50000 USDC = 50000 USDC needed, have 100000 - should succeed
        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await
            .unwrap();
        assert!(order_id > U256::zero());

        // Buy 2 BTC at 50000 = 100000 USDC needed, only 50000 left - should fail
        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(2u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await;
        assert!(result.is_err(), "should reject order exceeding balance");

        // Sell 5 BTC, have 10 - should succeed
        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Sell,
                U256::from(5u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await
            .unwrap();
        assert!(order_id > U256::zero());

        // Sell 6 BTC, only 5 left - should fail
        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Sell,
                U256::from(6u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await;
        assert!(result.is_err(), "should reject sell exceeding balance");
    }

    #[tokio::test]
    async fn test_custom_spread_override() {
        let mock = MockBitgetBuilder::new()
            .with_spread("CUSTOM/USDC", 15) // Custom 15 bps spread
            .with_latency(Duration::from_millis(1))
            .build();

        // Custom spread should be used
        let spread = mock.get_spread("CUSTOM/USDC").await;
        assert_eq!(spread.spread_bps, 15);

        // Other pairs still use defaults
        let spread = mock.get_spread("BTC/USDC").await;
        assert_eq!(spread.spread_bps, 10);
    }

    #[tokio::test]
    async fn test_set_spread_at_runtime() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .build();

        // Default OTHER spread (pair without BTC/ETH or stablecoins)
        let spread = mock.get_spread("SOL/AVAX").await;
        assert_eq!(spread.spread_bps, 25);

        // Override at runtime
        mock.set_spread("SOL/AVAX", 50).await;

        let spread = mock.get_spread("SOL/AVAX").await;
        assert_eq!(spread.spread_bps, 50);
    }

    #[tokio::test]
    async fn test_failure_rate_zero() {
        let mock = MockBitgetBuilder::new()
            .with_failure_rate(0.0)
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_millis(10))
            .build();

        // With 0% failure rate, all orders should succeed
        for _ in 0..10 {
            let result = mock
                .place_order(
                    "BTC/USDC".to_string(),
                    Side::Buy,
                    U256::from(100u64),
                    U256::from(50000u64),
                )
                .await;
            assert!(result.is_ok());
        }
    }

    #[tokio::test]
    async fn test_with_seed_reproducibility() {
        // Two mocks with the same seed should produce the same failure pattern
        let run_with_seed = |seed: u64| async move {
            let mock = MockBitgetBuilder::new()
                .with_seed(seed)
                .with_failure_rate(0.5)
                .with_latency(Duration::from_millis(1))
                .with_fill_delay(Duration::from_secs(10))
                .build();

            let mut results = vec![];
            for _ in 0..20 {
                let r = mock
                    .place_order(
                        "BTC/USDC".to_string(),
                        Side::Buy,
                        U256::from(100u64),
                        U256::from(50000u64),
                    )
                    .await;
                results.push(r.is_ok());
            }
            results
        };

        let results1 = run_with_seed(42).await;
        let results2 = run_with_seed(42).await;
        let results3 = run_with_seed(99).await;

        assert_eq!(results1, results2, "same seed must produce same failure pattern");
        // Different seed should (very likely) produce different pattern
        // With 20 trials at 50% rate, probability of identical sequences is ~1/2^20
        assert_ne!(results1, results3, "different seeds should produce different patterns");
    }

    #[tokio::test]
    async fn test_cancel_order() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10)) // Long delay so we can cancel before fill
            .build();

        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64),
                U256::from(50000u64),
            )
            .await
            .unwrap();

        // Order should be pending
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Pending);

        // Cancel the order
        mock.cancel_order(order_id).await.unwrap();

        // Should be cancelled now
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Cancelled);

        // Cancelling a non-existent order should error
        let result = mock.cancel_order(U256::from(9999u64)).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_depth_enforcement() {
        let small_depth = U256::from(1000u64) * U256::exp10(18);
        let mock = MockBitgetBuilder::new()
            .with_depth(small_depth)
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10))
            .build();

        // Order within depth should succeed
        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(500u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await;
        assert!(result.is_ok(), "order within depth should succeed");

        // Order exceeding depth should fail
        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(2000u64) * U256::exp10(18), // > 1000 depth
                U256::from(50000u64) * U256::exp10(18),
            )
            .await;
        assert!(result.is_err(), "order exceeding depth should fail");
    }

    #[tokio::test]
    async fn test_batch_order() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10))
            .build();

        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64),
                U256::from(50000u64),
            )
            .await
            .unwrap();

        // Should be pending initially
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Pending);

        // Batch the order
        mock.batch_order(order_id).await.unwrap();

        // Should be batched now
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Batched);

        // Can't batch an already batched order
        let result = mock.batch_order(order_id).await;
        assert!(result.is_err());

        // Batched order can still be filled via simulate_fill
        let filled = mock
            .simulate_fill(order_id, U256::from(1000u64), U256::from(50000u64))
            .await;
        assert!(filled, "batched order should accept fills");

        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Filled);
    }

    #[tokio::test]
    async fn test_expire_order() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10))
            .build();

        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64),
                U256::from(50000u64),
            )
            .await
            .unwrap();

        // Expire the order
        mock.expire_order(order_id).await.unwrap();

        // Should be expired now
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Expired);

        // Can't expire an already expired order (idempotent would be ok, but we chose strict)
        let result = mock.expire_order(order_id).await;
        assert!(result.is_err());

        // Can't fill an expired order
        let filled = mock
            .simulate_fill(order_id, U256::from(1000u64), U256::from(50000u64))
            .await;
        assert!(!filled, "expired order should reject fills");
    }

    #[tokio::test]
    async fn test_simulate_fill_on_cancelled_order() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10))
            .build();

        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1000u64),
                U256::from(50000u64),
            )
            .await
            .unwrap();

        // Cancel the order
        mock.cancel_order(order_id).await.unwrap();

        // Try to simulate a fill on cancelled order - should return false
        let filled = mock
            .simulate_fill(order_id, U256::from(1000u64), U256::from(50000u64))
            .await;
        assert!(!filled, "cancelled order should reject fills");

        // Status should remain Cancelled
        let status = mock.get_order_status(order_id).await.unwrap();
        assert_eq!(status, OrderStatus::Cancelled);
    }

    #[tokio::test]
    async fn test_add_balance_runtime() {
        let mock = MockBitgetBuilder::new()
            .with_latency(Duration::from_millis(1))
            .with_fill_delay(Duration::from_secs(10))
            .build();

        // No balances configured - orders should pass without balance check
        let order_id = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await
            .unwrap();
        assert!(order_id > U256::zero());

        // Add balance at runtime
        mock.add_balance("USDC", U256::from(100_000u64) * U256::exp10(18))
            .await;

        // Now order should succeed and deduct balance
        let order_id2 = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(1u64) * U256::exp10(18),
                U256::from(50000u64) * U256::exp10(18),
            )
            .await
            .unwrap();
        assert!(order_id2 > order_id);

        // Second order should fail - only 50000 USDC left
        let result = mock
            .place_order(
                "BTC/USDC".to_string(),
                Side::Buy,
                U256::from(2u64) * U256::exp10(18), // needs 100000 USDC
                U256::from(50000u64) * U256::exp10(18),
            )
            .await;
        assert!(result.is_err(), "should fail due to insufficient balance");
    }
}
