// CoinsBackground — real GLB coins (lathe with bevelled rim, 512 tris,
// generated by the model-hunt subagent) drifting toward the camera from
// the background. Each coin holds a fixed x/y, advances slowly along
// +Z over a long cycle, then loops back to the deep end. No sideways
// drift. Continuous slow rotation around its own face-normal axis so
// we see the rim flip past the camera. Brand-green body with a soft
// translucent feel, white pill (the current frontend mark) mapped onto
// both faces.
//
// Coins are intentionally sparse (7 total) and placed outside the
// horizontal text bands so the left "GENERAL / MARKET" and right
// "GENERALMARKET.IO" wordmarks read cleanly.

import React, { useMemo, useEffect } from "react";
import { AbsoluteFill, staticFile, useCurrentFrame } from "remotion";
import { ThreeCanvas } from "@remotion/three";
import { useThree } from "@react-three/fiber";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export type CoinsBackgroundProps = {
  forwardProgress: number;
  opacity: number;
  width: number;
  height: number;
};

const BG_COLOR = "#E0D8EC";
const COIN_MODEL_URL = staticFile("models/coin.glb");
const MARK_URL = staticFile("gm-mark-transparent-1024.png");
useGLTF.preload(COIN_MODEL_URL);
useTexture.preload(MARK_URL);

// ── Coin layout — placed around the text safe-zones ──────────────────
// Camera at (0, 0.5, 14), fov 40°. Visible half-height at z=0 is ~5.1,
// half-width ~9 (16:9). The left and right wordmarks live in the
// horizontal band y ∈ [-1.5, 1.5] at |x| ≈ 5..8.5. Coins live above
// (y > 1.8), below (y < -2), or in the deep back band.
//
// Each coin has a fixed x and y. Z is computed per frame from the
// advance cycle. spinAxis is the unit axis around which the coin
// rotates continuously — slightly off the face-normal so the disc
// flips and reveals its rim mid-cycle.

type CoinSeed = {
  x: number;
  y: number;
  baseScale: number;
  cycleSec: number; // total time deep → close → loop
  cyclePhase: number; // 0..1 offset so coins don't sync
  spinPeriodSec: number; // slow rotation period
  spinPhase: number;
  spinTilt: number; // angle off the up-axis so the face flips visibly
  tiltAxis: number; // rotation of the spin axis around Y
};

const COIN_SEEDS: CoinSeed[] = [
  // Top-left area, above "GENERAL/MARKET" wordmark
  {
    x: -5.2,
    y: 3.0,
    baseScale: 1.2,
    cycleSec: 22,
    cyclePhase: 0.0,
    spinPeriodSec: 13,
    spinPhase: 0.4,
    spinTilt: 0.6,
    tiltAxis: 0.2,
  },
  // Top-centre, above the phone
  {
    x: -0.4,
    y: 3.4,
    baseScale: 1.45,
    cycleSec: 24,
    cyclePhase: 0.35,
    spinPeriodSec: 16,
    spinPhase: 1.2,
    spinTilt: 0.7,
    tiltAxis: 0.9,
  },
  // Top-right, above "GENERALMARKET.IO"
  {
    x: 5.4,
    y: 3.0,
    baseScale: 1.25,
    cycleSec: 20,
    cyclePhase: 0.62,
    spinPeriodSec: 14,
    spinPhase: 2.0,
    spinTilt: 0.55,
    tiltAxis: 1.4,
  },
  // Bottom-left hero, below text
  {
    x: -5.0,
    y: -2.9,
    baseScale: 1.55,
    cycleSec: 26,
    cyclePhase: 0.18,
    spinPeriodSec: 17,
    spinPhase: 0.9,
    spinTilt: 0.65,
    tiltAxis: 0.5,
  },
  // Bottom-centre, below the phone
  {
    x: 0.8,
    y: -3.4,
    baseScale: 1.1,
    cycleSec: 21,
    cyclePhase: 0.5,
    spinPeriodSec: 12,
    spinPhase: 1.7,
    spinTilt: 0.5,
    tiltAxis: 2.1,
  },
  // Bottom-right hero, below text
  {
    x: 5.2,
    y: -2.9,
    baseScale: 1.4,
    cycleSec: 25,
    cyclePhase: 0.75,
    spinPeriodSec: 15,
    spinPhase: 2.4,
    spinTilt: 0.6,
    tiltAxis: 1.0,
  },
  // Deep back, mid-frame — never comes fully forward, just lives back
  // there for layered depth. Small.
  {
    x: -1.8,
    y: 0.2,
    baseScale: 0.55,
    cycleSec: 30,
    cyclePhase: 0.45,
    spinPeriodSec: 18,
    spinPhase: 1.0,
    spinTilt: 0.4,
    tiltAxis: 0.0,
  },
];

const FPS = 30;
const Z_BACK = -9;
const Z_FRONT = 4;
const FADE_BAND = 0.08; // fraction of cycle for fade in/out at the ends

function smoothstep(t: number): number {
  const x = Math.max(0, Math.min(1, t));
  return x * x * (3 - 2 * x);
}

// ── Coin instance ────────────────────────────────────────────────────
// Clones the loaded GLB scene once (so each coin has its own material
// instances) and binds the GM-mark texture to the Front and Back face
// materials. The Rim material gets a darker brand-green tint.

const COIN_BODY_COLOR = new THREE.Color("#1cb37c"); // brand green, lifted a hair
const COIN_RIM_COLOR = new THREE.Color("#0d6c4b");

const CoinMesh: React.FC<{
  seed: CoinSeed;
  frame: number;
  forwardProgress: number;
  globalAlpha: number;
  gltfScene: THREE.Group;
  faceMap: THREE.Texture;
}> = ({ seed, frame, forwardProgress, globalAlpha, gltfScene, faceMap }) => {
  // Per-instance clone of the loaded scene. Memoised so we don't
  // re-allocate every frame.
  const clone = useMemo(() => {
    const c = gltfScene.clone(true);
    c.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      // The model has named materials: Front, Back, Rim. Clone each so
      // texture/colour changes stay local.
      const mat = mesh.material as
        | THREE.MeshStandardMaterial
        | THREE.MeshPhysicalMaterial;
      const cloned = mat.clone();
      cloned.transparent = true;
      cloned.depthWrite = false;
      const name = (mat.name || "").toLowerCase();
      if (name === "front" || name === "back") {
        cloned.map = faceMap;
        cloned.color = new THREE.Color("#ffffff");
        if ("emissive" in cloned) {
          cloned.emissive = new THREE.Color("#ffffff");
          cloned.emissiveMap = faceMap;
          cloned.emissiveIntensity = 0.35;
        }
        cloned.roughness = 0.32;
        cloned.metalness = 0.15;
      } else {
        // Rim / body — translucent brand green.
        cloned.map = null;
        cloned.color = name === "rim" ? COIN_RIM_COLOR : COIN_BODY_COLOR;
        if ("emissive" in cloned) {
          cloned.emissive = COIN_RIM_COLOR.clone().multiplyScalar(0.15);
        }
        cloned.roughness = 0.34;
        cloned.metalness = 0.25;
        if ("transmission" in cloned) {
          // Solid translucent — read as a token, not a glass ring.
          (cloned as THREE.MeshPhysicalMaterial).transmission = 0.15;
          (cloned as THREE.MeshPhysicalMaterial).thickness = 0.3;
          (cloned as THREE.MeshPhysicalMaterial).ior = 1.45;
          (cloned as THREE.MeshPhysicalMaterial).clearcoat = 0.6;
          (cloned as THREE.MeshPhysicalMaterial).clearcoatRoughness = 0.22;
        }
        cloned.opacity = 0.95;
      }
      mesh.material = cloned;
    });
    return c;
  }, [gltfScene, faceMap]);

  // Drive material opacity each frame.
  useEffect(() => {
    clone.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      (mesh.material as THREE.MeshStandardMaterial).opacity = globalAlpha;
    });
  });

  // ── Advance cycle: deep z → near z, loop. Per-coin phase keeps them
  //    out of sync. The forwardProgress beat modulates how aggressive
  //    the advance is — at p=1 coins push closer.
  const p = smoothstep(forwardProgress);
  const cyclePosNormalised =
    (((frame / FPS) / seed.cycleSec + seed.cyclePhase) % 1 + 1) % 1;
  const zRange = Z_FRONT - Z_BACK;
  const zBase = Z_BACK + cyclePosNormalised * zRange;
  // forwardProgress nudges coins a bit further forward.
  const zOffset = p * 1.6;
  const z = zBase + zOffset;

  // Fade at cycle ends so coins don't pop in/out.
  const fadeIn = smoothstep(cyclePosNormalised / FADE_BAND);
  const fadeOut = 1 - smoothstep((cyclePosNormalised - (1 - FADE_BAND)) / FADE_BAND);
  const cycleAlpha = Math.min(fadeIn, fadeOut);

  // Scale grows as the coin approaches (perspective amplifier — makes
  // the close pass feel close even at constant world scale).
  const scale = seed.baseScale * (1 + cyclePosNormalised * 0.25);

  // ── Slow continuous spin. Rotation axis is tilted off vertical so
  //    the disc flips and reveals its rim mid-cycle.
  const spinAngle =
    seed.spinPhase + frame * ((Math.PI * 2) / (seed.spinPeriodSec * FPS));
  const tilt = seed.spinTilt;
  const tiltDir = seed.tiltAxis;
  // Build rotation: tilt the spin axis around Y by tiltAxis, then
  // rotate around that tilted axis by spinAngle.
  const axis = new THREE.Vector3(
    Math.sin(tilt) * Math.cos(tiltDir),
    Math.cos(tilt),
    Math.sin(tilt) * Math.sin(tiltDir),
  ).normalize();
  const quat = new THREE.Quaternion().setFromAxisAngle(axis, spinAngle);

  // Apply the cycle-fade by scaling material alpha via group opacity.
  // Instead of a render attribute, drive it on the materials directly.
  useEffect(() => {
    clone.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      (mesh.material as THREE.MeshStandardMaterial).opacity =
        globalAlpha * cycleAlpha;
    });
  });

  return (
    <group position={[seed.x, seed.y, z]} scale={scale} quaternion={quat}>
      <primitive object={clone} />
    </group>
  );
};

const Scene: React.FC<{
  frame: number;
  forwardProgress: number;
  opacity: number;
}> = ({ frame, forwardProgress, opacity }) => {
  const { camera } = useThree();
  const gltf = useGLTF(COIN_MODEL_URL);
  const faceMap = useTexture(MARK_URL);
  faceMap.colorSpace = THREE.SRGBColorSpace;
  faceMap.anisotropy = 8;

  const persp = camera as THREE.PerspectiveCamera;
  persp.position.set(0, 0.5, 14);
  persp.lookAt(0, 0, 0);
  persp.fov = 40;
  persp.updateProjectionMatrix();

  return (
    <>
      <hemisphereLight args={["#ffffff", "#9eb5c8", 0.7]} />
      <directionalLight position={[3, 8, 9]} intensity={1.5} color="#ffffff" />
      <directionalLight position={[-5, 3, -6]} intensity={0.55} color="#b8e8d8" />
      <directionalLight position={[-6, -2, 5]} intensity={0.35} color="#e8f5ee" />
      {COIN_SEEDS.map((seed, i) => (
        <CoinMesh
          key={i}
          seed={seed}
          frame={frame}
          forwardProgress={forwardProgress}
          globalAlpha={opacity}
          gltfScene={gltf.scene}
          faceMap={faceMap}
        />
      ))}
    </>
  );
};

export const CoinsBackground: React.FC<CoinsBackgroundProps> = ({
  forwardProgress,
  opacity,
  width,
  height,
}) => {
  const frame = useCurrentFrame();

  return (
    <AbsoluteFill style={{ width, height, background: BG_COLOR }}>
      <ThreeCanvas
        width={width}
        height={height}
        camera={{
          fov: 40,
          near: 0.5,
          far: 200,
          position: [0, 0.5, 14],
        }}
        gl={{
          antialias: true,
          alpha: true,
          powerPreference: "high-performance",
          toneMapping: THREE.ACESFilmicToneMapping,
          toneMappingExposure: 1.05,
        }}
        style={{ background: "transparent" }}
      >
        <React.Suspense fallback={null}>
          <Scene
            frame={frame}
            forwardProgress={forwardProgress}
            opacity={opacity}
          />
        </React.Suspense>
      </ThreeCanvas>
    </AbsoluteFill>
  );
};
