// CoinsBackground — real GLB coins (lathe with bevelled rim, 512 tris,
// generated by the model-hunt subagent) drifting toward the camera from
// the background. Each coin holds a fixed x/y, advances slowly along
// +Z over a long cycle, then loops back to the deep end. No sideways
// drift. Continuous slow rotation around its own face-normal axis so
// we see the rim flip past the camera. Brand-green body with a soft
// translucent feel, white pill (the current frontend mark) mapped onto
// both faces.
//
// Coins are intentionally sparse (7 total) and placed outside the
// horizontal text bands so the left "GENERAL / MARKET" and right
// "GENERALMARKET.IO" wordmarks read cleanly.

import React, { useMemo, useEffect } from "react";
import { AbsoluteFill, staticFile, useCurrentFrame } from "remotion";
import { ThreeCanvas } from "@remotion/three";
import { useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export type CoinsBackgroundProps = {
  forwardProgress: number;
  opacity: number;
  width: number;
  height: number;
};

const BG_COLOR = "#E0D8EC";
const COIN_MODEL_URL = staticFile("models/coin.glb");
useGLTF.preload(COIN_MODEL_URL);

// Brand identity: green body with a white pill mark (the current frontend
// logo). Built procedurally as a CanvasTexture so the coin face is a
// solid disc — not a transparent-bg PNG (which would let the lavender
// background bleed through the geometry).
const FACE_TEXTURE_SIZE = 512;
const BRAND_GREEN = "#1cb37c";
const BRAND_GREEN_DARK = "#0d6c4b";

function buildFaceTexture(): THREE.CanvasTexture {
  const canvas = document.createElement("canvas");
  canvas.width = FACE_TEXTURE_SIZE;
  canvas.height = FACE_TEXTURE_SIZE;
  const ctx = canvas.getContext("2d");
  if (ctx) {
    // Solid green disc covering the full UV square. The GLB face is a
    // circular cap inscribed in this square, so only the inscribed
    // disc gets sampled — but filling everything keeps the texture
    // robust to UV edge cases.
    ctx.fillStyle = BRAND_GREEN;
    ctx.fillRect(0, 0, FACE_TEXTURE_SIZE, FACE_TEXTURE_SIZE);
    // Soft radial vignette so the face has subtle depth toward the rim.
    const vignette = ctx.createRadialGradient(
      FACE_TEXTURE_SIZE / 2,
      FACE_TEXTURE_SIZE / 2,
      FACE_TEXTURE_SIZE * 0.18,
      FACE_TEXTURE_SIZE / 2,
      FACE_TEXTURE_SIZE / 2,
      FACE_TEXTURE_SIZE * 0.55,
    );
    vignette.addColorStop(0, "rgba(255,255,255,0.10)");
    vignette.addColorStop(1, "rgba(0,0,0,0.18)");
    ctx.fillStyle = vignette;
    ctx.fillRect(0, 0, FACE_TEXTURE_SIZE, FACE_TEXTURE_SIZE);
    // White pill — proportions match the brand logo: 512×100 pill on a
    // 1024×1024 frame, centered. Scaled down to fit our 512×512 canvas.
    const pillW = FACE_TEXTURE_SIZE * 0.5;
    const pillH = FACE_TEXTURE_SIZE * (100 / 1024);
    const pillX = (FACE_TEXTURE_SIZE - pillW) / 2;
    const pillY = (FACE_TEXTURE_SIZE - pillH) / 2;
    const pillR = pillH / 2;
    ctx.fillStyle = "#FFFFFF";
    ctx.beginPath();
    ctx.moveTo(pillX + pillR, pillY);
    ctx.lineTo(pillX + pillW - pillR, pillY);
    ctx.arc(pillX + pillW - pillR, pillY + pillR, pillR, -Math.PI / 2, Math.PI / 2);
    ctx.lineTo(pillX + pillR, pillY + pillH);
    ctx.arc(pillX + pillR, pillY + pillR, pillR, Math.PI / 2, -Math.PI / 2);
    ctx.closePath();
    ctx.fill();
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.anisotropy = 8;
  tex.needsUpdate = true;
  return tex;
}

// ── Coin layout — placed around the text safe-zones ──────────────────
// Camera at (0, 0.5, 14), fov 40°. Visible half-height at z=0 is ~5.1,
// half-width ~9 (16:9). The left and right wordmarks live in the
// horizontal band y ∈ [-1.5, 1.5] at |x| ≈ 5..8.5. Coins live above
// (y > 1.8), below (y < -2), or in the deep back band.
//
// Each coin has a fixed x and y. Z is computed per frame from the
// advance cycle. spinAxis is the unit axis around which the coin
// rotates continuously — slightly off the face-normal so the disc
// flips and reveals its rim mid-cycle.

type CoinSeed = {
  x: number;
  y: number;
  baseScale: number;
  cycleSec: number; // total time deep → close → loop
  cyclePhase: number; // 0..1 offset so coins don't sync
  spinPeriodSec: number; // slow rotation period (around world Y)
  spinPhase: number;
  staticTiltX: number; // constant lean forward/back, radians
  staticTiltZ: number; // constant lean left/right, radians
};

const COIN_SEEDS: CoinSeed[] = [
  // Top-left, above the GENERAL/MARKET wordmark
  {
    x: -5.4,
    y: 3.0,
    baseScale: 1.2,
    cycleSec: 22,
    cyclePhase: 0.0,
    spinPeriodSec: 18,
    spinPhase: 0.4,
    staticTiltX: 0.18,
    staticTiltZ: 0.12,
  },
  // Top-centre, above the phone
  {
    x: -0.4,
    y: 3.4,
    baseScale: 1.45,
    cycleSec: 24,
    cyclePhase: 0.35,
    spinPeriodSec: 22,
    spinPhase: 1.2,
    staticTiltX: -0.12,
    staticTiltZ: 0.05,
  },
  // Top-right, above GENERALMARKET.IO
  {
    x: 5.4,
    y: 3.0,
    baseScale: 1.25,
    cycleSec: 20,
    cyclePhase: 0.62,
    spinPeriodSec: 19,
    spinPhase: 2.0,
    staticTiltX: 0.1,
    staticTiltZ: -0.18,
  },
  // Bottom-left hero, below the wordmark band
  {
    x: -5.0,
    y: -2.9,
    baseScale: 1.55,
    cycleSec: 26,
    cyclePhase: 0.18,
    spinPeriodSec: 24,
    spinPhase: 0.9,
    staticTiltX: -0.22,
    staticTiltZ: -0.1,
  },
  // Bottom-centre, below the phone
  {
    x: 0.8,
    y: -3.4,
    baseScale: 1.1,
    cycleSec: 21,
    cyclePhase: 0.5,
    spinPeriodSec: 17,
    spinPhase: 1.7,
    staticTiltX: 0.15,
    staticTiltZ: 0.0,
  },
  // Bottom-right hero
  {
    x: 5.2,
    y: -2.9,
    baseScale: 1.4,
    cycleSec: 25,
    cyclePhase: 0.75,
    spinPeriodSec: 20,
    spinPhase: 2.4,
    staticTiltX: -0.18,
    staticTiltZ: 0.15,
  },
  // Deep back, mid-frame — small, slow, layered depth
  {
    x: -1.8,
    y: 0.2,
    baseScale: 0.55,
    cycleSec: 30,
    cyclePhase: 0.45,
    spinPeriodSec: 26,
    spinPhase: 1.0,
    staticTiltX: 0.0,
    staticTiltZ: 0.08,
  },
];

const FPS = 30;
const Z_BACK = -9;
const Z_FRONT = 4;
const FADE_BAND = 0.08; // fraction of cycle for fade in/out at the ends

function smoothstep(t: number): number {
  const x = Math.max(0, Math.min(1, t));
  return x * x * (3 - 2 * x);
}

// ── Coin instance ────────────────────────────────────────────────────
// Clones the loaded GLB scene once (so each coin has its own material
// instances) and binds the brand face texture to Front/Back. Rim and
// any other body parts get the darker green so the rim catches light
// and reads as a separate volume.

const COIN_RIM_COLOR = new THREE.Color(BRAND_GREEN_DARK);

const CoinMesh: React.FC<{
  seed: CoinSeed;
  frame: number;
  forwardProgress: number;
  globalAlpha: number;
  gltfScene: THREE.Group;
  faceMap: THREE.Texture;
}> = ({ seed, frame, forwardProgress, globalAlpha, gltfScene, faceMap }) => {
  // Per-instance clone of the loaded scene. Memoised so we don't
  // re-allocate every frame.
  const clone = useMemo(() => {
    const c = gltfScene.clone(true);
    c.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      const mat = mesh.material as
        | THREE.MeshStandardMaterial
        | THREE.MeshPhysicalMaterial;
      const cloned = mat.clone();
      cloned.transparent = true;
      const name = (mat.name || "").toLowerCase();
      if (name === "front" || name === "back") {
        // Solid green face with the white pill baked in. No
        // transmission — the disc is opaque token, not glass.
        cloned.map = faceMap;
        cloned.color = new THREE.Color("#ffffff");
        cloned.roughness = 0.36;
        cloned.metalness = 0.15;
        if ("transmission" in cloned) {
          (cloned as THREE.MeshPhysicalMaterial).transmission = 0;
        }
        if ("emissive" in cloned) {
          cloned.emissive = new THREE.Color("#ffffff");
          cloned.emissiveMap = faceMap;
          cloned.emissiveIntensity = 0.12;
        }
      } else {
        // Rim / body — darker brand green, more metallic so the
        // bevel catches the key light.
        cloned.map = null;
        cloned.color = COIN_RIM_COLOR;
        cloned.roughness = 0.32;
        cloned.metalness = 0.55;
        if ("transmission" in cloned) {
          (cloned as THREE.MeshPhysicalMaterial).transmission = 0;
        }
        if ("emissive" in cloned) {
          cloned.emissive = COIN_RIM_COLOR.clone().multiplyScalar(0.18);
        }
      }
      mesh.material = cloned;
    });
    return c;
  }, [gltfScene, faceMap]);

  // Drive material opacity each frame.
  useEffect(() => {
    clone.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      (mesh.material as THREE.MeshStandardMaterial).opacity = globalAlpha;
    });
  });

  // ── Advance cycle: deep z → near z, loop. Per-coin phase keeps them
  //    out of sync. The forwardProgress beat modulates how aggressive
  //    the advance is — at p=1 coins push closer.
  const p = smoothstep(forwardProgress);
  const cyclePosNormalised =
    (((frame / FPS) / seed.cycleSec + seed.cyclePhase) % 1 + 1) % 1;
  const zRange = Z_FRONT - Z_BACK;
  const zBase = Z_BACK + cyclePosNormalised * zRange;
  // forwardProgress nudges coins a bit further forward.
  const zOffset = p * 1.6;
  const z = zBase + zOffset;

  // Fade at cycle ends so coins don't pop in/out.
  const fadeIn = smoothstep(cyclePosNormalised / FADE_BAND);
  const fadeOut = 1 - smoothstep((cyclePosNormalised - (1 - FADE_BAND)) / FADE_BAND);
  const cycleAlpha = Math.min(fadeIn, fadeOut);

  // Scale grows as the coin approaches (perspective amplifier — makes
  // the close pass feel close even at constant world scale).
  const scale = seed.baseScale * (1 + cyclePosNormalised * 0.25);

  // ── Orientation
  // The GLB lies flat in the XZ plane (face normals along ±Y). Tip
  // it 90° around X so the face points toward the camera (+Z). Then
  // apply a slow rotation around world Y so the coin gracefully
  // turns — face → edge → back → edge → loop. A small static tilt
  // per coin breaks up the synchrony.
  const baseOrient = new THREE.Quaternion().setFromAxisAngle(
    new THREE.Vector3(1, 0, 0),
    Math.PI / 2,
  );
  const spinAngle =
    seed.spinPhase + frame * ((Math.PI * 2) / (seed.spinPeriodSec * FPS));
  const spinQ = new THREE.Quaternion().setFromAxisAngle(
    new THREE.Vector3(0, 1, 0),
    spinAngle,
  );
  const tiltQ = new THREE.Quaternion().setFromEuler(
    new THREE.Euler(seed.staticTiltX, 0, seed.staticTiltZ, "YXZ"),
  );
  // tiltQ * spinQ * baseOrient — apply baseOrient first (model → face camera),
  // then spinQ (around world Y), then tiltQ (constant per-coin lean).
  const quat = tiltQ.clone().multiply(spinQ).multiply(baseOrient);

  // Apply the cycle-fade by scaling material alpha via group opacity.
  // Instead of a render attribute, drive it on the materials directly.
  useEffect(() => {
    clone.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      (mesh.material as THREE.MeshStandardMaterial).opacity =
        globalAlpha * cycleAlpha;
    });
  });

  return (
    <group position={[seed.x, seed.y, z]} scale={scale} quaternion={quat}>
      <primitive object={clone} />
    </group>
  );
};

const Scene: React.FC<{
  frame: number;
  forwardProgress: number;
  opacity: number;
}> = ({ frame, forwardProgress, opacity }) => {
  const { camera } = useThree();
  const gltf = useGLTF(COIN_MODEL_URL);
  // Procedural face — green disc with white pill mark.
  const faceMap = useMemo(() => buildFaceTexture(), []);

  const persp = camera as THREE.PerspectiveCamera;
  persp.position.set(0, 0.5, 14);
  persp.lookAt(0, 0, 0);
  persp.fov = 40;
  persp.updateProjectionMatrix();

  return (
    <>
      <hemisphereLight args={["#ffffff", "#9eb5c8", 0.7]} />
      <directionalLight position={[3, 8, 9]} intensity={1.5} color="#ffffff" />
      <directionalLight position={[-5, 3, -6]} intensity={0.55} color="#b8e8d8" />
      <directionalLight position={[-6, -2, 5]} intensity={0.35} color="#e8f5ee" />
      {COIN_SEEDS.map((seed, i) => (
        <CoinMesh
          key={i}
          seed={seed}
          frame={frame}
          forwardProgress={forwardProgress}
          globalAlpha={opacity}
          gltfScene={gltf.scene}
          faceMap={faceMap}
        />
      ))}
    </>
  );
};

export const CoinsBackground: React.FC<CoinsBackgroundProps> = ({
  forwardProgress,
  opacity,
  width,
  height,
}) => {
  const frame = useCurrentFrame();

  return (
    <AbsoluteFill style={{ width, height, background: BG_COLOR }}>
      <ThreeCanvas
        width={width}
        height={height}
        camera={{
          fov: 40,
          near: 0.5,
          far: 200,
          position: [0, 0.5, 14],
        }}
        gl={{
          antialias: true,
          alpha: true,
          powerPreference: "high-performance",
          toneMapping: THREE.ACESFilmicToneMapping,
          toneMappingExposure: 1.05,
        }}
        style={{ background: "transparent" }}
      >
        <React.Suspense fallback={null}>
          <Scene
            frame={frame}
            forwardProgress={forwardProgress}
            opacity={opacity}
          />
        </React.Suspense>
      </ThreeCanvas>
    </AbsoluteFill>
  );
};
