// CoinsBackground — real GLB coins (lathe with bevelled rim, 512 tris,
// generated by the model-hunt subagent) drifting toward the camera from
// the background. Each coin holds a fixed x/y, advances slowly along
// +Z over a long cycle, then loops back to the deep end. No sideways
// drift. Continuous slow rotation around its own face-normal axis so
// we see the rim flip past the camera. Brand-green body with a soft
// translucent feel, white pill (the current frontend mark) mapped onto
// both faces.
//
// Coins are intentionally sparse (7 total) and placed outside the
// horizontal text bands so the left "GENERAL / MARKET" and right
// "GENERALMARKET.IO" wordmarks read cleanly.

import React, { useMemo, useEffect } from "react";
import { AbsoluteFill, staticFile, useCurrentFrame } from "remotion";
import { ThreeCanvas } from "@remotion/three";
import { useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export type CoinsBackgroundProps = {
  forwardProgress: number;
  opacity: number;
  width: number;
  height: number;
};

// Background gradient — lifts the centre slightly warmer to match
// Houdini's reference. Pure flat lavender reads as a placeholder.
const BG_GRADIENT =
  "radial-gradient(ellipse at center, #E8E0F2 0%, #D8CFE7 60%, #C6BCD7 100%)";
const COIN_MODEL_URL = staticFile("models/coin.glb");
useGLTF.preload(COIN_MODEL_URL);

// Houdini-style translucent purple coins with the white pill mark.
// Glass material (transmission + clearcoat) reads as a glossy gem-like
// token. Brand identity expressed by the mark, not by the coin colour.
const FACE_TEXTURE_SIZE = 512;
const COIN_BODY_HEX = "#a78bd9";
const COIN_BODY_LIGHT = "#c4b1ec";
const COIN_BODY_DEEP = "#6a4cad";

function buildFaceTexture(): THREE.CanvasTexture {
  const canvas = document.createElement("canvas");
  canvas.width = FACE_TEXTURE_SIZE;
  canvas.height = FACE_TEXTURE_SIZE;
  const ctx = canvas.getContext("2d");
  if (ctx) {
    const cx = FACE_TEXTURE_SIZE / 2;
    const cy = FACE_TEXTURE_SIZE / 2;
    // Subtle vertical gradient from a lighter top to a deeper bottom —
    // sells the disc as a dimensional object lit from above.
    const bodyGrad = ctx.createLinearGradient(0, 0, 0, FACE_TEXTURE_SIZE);
    bodyGrad.addColorStop(0, COIN_BODY_LIGHT);
    bodyGrad.addColorStop(0.45, COIN_BODY_HEX);
    bodyGrad.addColorStop(1, COIN_BODY_DEEP);
    ctx.fillStyle = bodyGrad;
    ctx.fillRect(0, 0, FACE_TEXTURE_SIZE, FACE_TEXTURE_SIZE);
    // Soft inner vignette so the face has depth toward the rim.
    const vignette = ctx.createRadialGradient(
      cx,
      cy * 0.85,
      FACE_TEXTURE_SIZE * 0.12,
      cx,
      cy,
      FACE_TEXTURE_SIZE * 0.55,
    );
    vignette.addColorStop(0, "rgba(255,255,255,0.18)");
    vignette.addColorStop(0.65, "rgba(255,255,255,0)");
    vignette.addColorStop(1, "rgba(0,0,0,0.22)");
    ctx.fillStyle = vignette;
    ctx.fillRect(0, 0, FACE_TEXTURE_SIZE, FACE_TEXTURE_SIZE);
    // Crescent highlight in the upper-left — the signature Houdini-coin
    // specular sheen.
    ctx.save();
    ctx.beginPath();
    ctx.arc(cx, cy, FACE_TEXTURE_SIZE * 0.49, 0, Math.PI * 2);
    ctx.clip();
    const sheen = ctx.createRadialGradient(
      cx - FACE_TEXTURE_SIZE * 0.22,
      cy - FACE_TEXTURE_SIZE * 0.24,
      FACE_TEXTURE_SIZE * 0.04,
      cx - FACE_TEXTURE_SIZE * 0.22,
      cy - FACE_TEXTURE_SIZE * 0.24,
      FACE_TEXTURE_SIZE * 0.32,
    );
    sheen.addColorStop(0, "rgba(255,255,255,0.7)");
    sheen.addColorStop(0.4, "rgba(255,255,255,0.25)");
    sheen.addColorStop(1, "rgba(255,255,255,0)");
    ctx.fillStyle = sheen;
    ctx.fillRect(0, 0, FACE_TEXTURE_SIZE, FACE_TEXTURE_SIZE);
    ctx.restore();
    // White pill — match the brand mark but bigger on the face so it
    // reads as a "logo coin" the way Houdini's "H" reads on theirs.
    // Sized to ~70% of the inscribed disc.
    const pillW = FACE_TEXTURE_SIZE * 0.68;
    const pillH = FACE_TEXTURE_SIZE * (100 / 1024) * 1.35;
    const pillX = (FACE_TEXTURE_SIZE - pillW) / 2;
    const pillY = (FACE_TEXTURE_SIZE - pillH) / 2;
    const pillR = pillH / 2;
    ctx.fillStyle = "#FFFFFF";
    ctx.beginPath();
    ctx.moveTo(pillX + pillR, pillY);
    ctx.lineTo(pillX + pillW - pillR, pillY);
    ctx.arc(pillX + pillW - pillR, pillY + pillR, pillR, -Math.PI / 2, Math.PI / 2);
    ctx.lineTo(pillX + pillR, pillY + pillH);
    ctx.arc(pillX + pillR, pillY + pillR, pillR, Math.PI / 2, -Math.PI / 2);
    ctx.closePath();
    ctx.fill();
  }
  const tex = new THREE.CanvasTexture(canvas);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.anisotropy = 8;
  tex.needsUpdate = true;
  return tex;
}

// ── Coin layout — placed around the text safe-zones ──────────────────
// Camera at (0, 0.5, 14), fov 40°. Visible half-height at z=0 is ~5.1,
// half-width ~9 (16:9). The left and right wordmarks live in the
// horizontal band y ∈ [-1.5, 1.5] at |x| ≈ 5..8.5. Coins live above
// (y > 1.8), below (y < -2), or in the deep back band.
//
// Each coin has a fixed x and y. Z is computed per frame from the
// advance cycle. spinAxis is the unit axis around which the coin
// rotates continuously — slightly off the face-normal so the disc
// flips and reveals its rim mid-cycle.

type CoinSeed = {
  x: number;
  y: number;
  baseScale: number;
  cycleSec: number; // total time deep → past-camera → loop (faster)
  cyclePhase: number; // 0..1 offset so coins don't sync
  // ── Wobble (replaces continuous spin) ────────────────────────────
  // Each coin rocks back and forth on a diagonal axis. The axis is
  // either /-diagonal (tiltAxisDir = +1) or \-diagonal (-1). The
  // wobble oscillates between ±wobbleAmplitudeDeg degrees with a
  // period of wobblePeriodSec seconds. wobblePhase shifts the start
  // angle so coins aren't synchronised.
  tiltAxisDir: 1 | -1;
  wobbleAmplitudeDeg: number; // 30 or 15 (some coins have a smaller range)
  wobblePeriodSec: number;   // ≥ 5 (5s for a full 60° swing → ≤12°/s)
  wobblePhase: number;        // radians, sets starting angle
  staticTiltDeg: number;      // additional constant lean (-30..+30°)
};

// Frame layout (world units, 16:9):
//   visible half-width @ z=0  ≈ 9.05
//   visible half-height        ≈ 5.1
// Text bands sit at roughly x ∈ [-8.5, -5.2] (left wordmark) and
// x ∈ [5.2, 8.5] (right URL), y ∈ [-1.2, 1.2]. Coins must NEVER
// occupy that rectangle even at their largest scale. Phone occupies
// roughly x ∈ [-1.8, 1.8], y ∈ [-4.0, 4.0]; coins behind the phone
// fall behind the CSS phone naturally because the phone is drawn on
// top of the canvas in the DOM.
//
// So coin world-x must satisfy ONE of:
//   above text:   y > 1.8
//   below text:   y < -1.8
//   middle gap:   |x| < 5.0  (between phone and wordmark) — but
//                 these would cross the phone, so we put them deep
//
// 12 coins total, 4 size tiers, dense.

// 14 coin tracks. Each one is a fixed x/y "lane" — the coin advances
// along z, fades out past the camera, and the SAME lane immediately
// starts a new coin from the back. With staggered cyclePhase values
// across the seed list there is always a mix of "just entering" and
// "about to leave" coins in the frame.
const COIN_SEEDS: CoinSeed[] = [
  // ── Top band (above wordmark vertical band)
  { x: -5.4, y: 3.0, baseScale: 1.4, cycleSec: 9, cyclePhase: 0.0,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 6.0,
    wobblePhase: 0.4, staticTiltDeg: -18 },
  { x: -0.6, y: 3.4, baseScale: 1.5, cycleSec: 11, cyclePhase: 0.35,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 15, wobblePeriodSec: 5.5,
    wobblePhase: 1.2, staticTiltDeg: 12 },
  { x: 5.4, y: 3.0, baseScale: 1.45, cycleSec: 10, cyclePhase: 0.62,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 7.0,
    wobblePhase: 2.0, staticTiltDeg: 22 },
  // ── Bottom band (below wordmark vertical band)
  { x: -5.4, y: -3.0, baseScale: 1.55, cycleSec: 12, cyclePhase: 0.18,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 6.5,
    wobblePhase: 0.9, staticTiltDeg: -25 },
  { x: 0.6, y: -3.5, baseScale: 1.3, cycleSec: 9.5, cyclePhase: 0.5,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 15, wobblePeriodSec: 5.5,
    wobblePhase: 1.7, staticTiltDeg: 8 },
  { x: 5.4, y: -3.0, baseScale: 1.5, cycleSec: 11, cyclePhase: 0.75,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 6.0,
    wobblePhase: 2.4, staticTiltDeg: 20 },
  // ── Far edges, above and below text band
  { x: -8.0, y: 2.2, baseScale: 0.85, cycleSec: 13, cyclePhase: 0.12,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 7.5,
    wobblePhase: 0.7, staticTiltDeg: -10 },
  { x: 8.0, y: -2.2, baseScale: 0.9, cycleSec: 12.5, cyclePhase: 0.55,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 15, wobblePeriodSec: 5.5,
    wobblePhase: 1.8, staticTiltDeg: 14 },
  { x: -7.4, y: -2.4, baseScale: 0.95, cycleSec: 11.5, cyclePhase: 0.3,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 6.0,
    wobblePhase: 0.0, staticTiltDeg: 25 },
  { x: 7.4, y: 2.4, baseScale: 0.95, cycleSec: 10.5, cyclePhase: 0.85,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 15, wobblePeriodSec: 5.0,
    wobblePhase: 2.6, staticTiltDeg: -16 },
  // ── Back filler — tiny, behind the phone-and-text plane, just adds
  // depth without ever blocking text.
  { x: -2.0, y: 1.8, baseScale: 0.45, cycleSec: 14, cyclePhase: 0.2,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 15, wobblePeriodSec: 5.5,
    wobblePhase: 1.4, staticTiltDeg: 6 },
  { x: 2.0, y: 1.8, baseScale: 0.45, cycleSec: 14, cyclePhase: 0.7,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 15, wobblePeriodSec: 6.0,
    wobblePhase: 0.2, staticTiltDeg: -8 },
  { x: -2.4, y: -1.8, baseScale: 0.42, cycleSec: 13.5, cyclePhase: 0.42,
    tiltAxisDir: 1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 7.0,
    wobblePhase: 2.6, staticTiltDeg: 18 },
  { x: 2.4, y: -1.9, baseScale: 0.44, cycleSec: 13, cyclePhase: 0.9,
    tiltAxisDir: -1, wobbleAmplitudeDeg: 30, wobblePeriodSec: 6.5,
    wobblePhase: 1.0, staticTiltDeg: -22 },
];

const FPS = 30;
// Coins start deep, advance toward the camera, and exit the frame
// LATERALLY via perspective — they don't fade. As a coin gets close
// to the camera, its outer world-x/y projects further off-axis and
// the coin sails out of view past the frame edges. Cycle then loops
// silently and the same lane spawns a fresh coin from the back.
const Z_BACK = -16;
const Z_FRONT = 11; // near camera (sits at z = 14) — coin gets large
const FADE_IN_BAND = 0.07;
const FADE_OUT_BAND = 0.04; // very short — coin should EXIT the frame, not fade out

function smoothstep(t: number): number {
  const x = Math.max(0, Math.min(1, t));
  return x * x * (3 - 2 * x);
}

// ── Coin instance ────────────────────────────────────────────────────
// Clones the loaded GLB scene once (so each coin has its own material
// instances) and binds the procedural face texture to Front/Back.
// Rim and body get a darker purple so the bevel reads as a separate
// volume against the lighter face.

const COIN_RIM_COLOR = new THREE.Color(COIN_BODY_DEEP);

const CoinMesh: React.FC<{
  seed: CoinSeed;
  frame: number;
  forwardProgress: number;
  globalAlpha: number;
  gltfScene: THREE.Group;
  faceMap: THREE.Texture;
}> = ({ seed, frame, forwardProgress, globalAlpha, gltfScene, faceMap }) => {
  // Per-instance clone of the loaded scene. Memoised so we don't
  // re-allocate every frame.
  const clone = useMemo(() => {
    const c = gltfScene.clone(true);
    c.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      const mat = mesh.material as
        | THREE.MeshStandardMaterial
        | THREE.MeshPhysicalMaterial;
      const cloned = mat.clone();
      cloned.transparent = true;
      const name = (mat.name || "").toLowerCase();
      if (name === "front" || name === "back") {
        // Translucent purple face with the white pill baked in. Glass
        // transmission + heavy clearcoat reads as Houdini's gem-like
        // disc rather than an opaque token.
        cloned.map = faceMap;
        cloned.color = new THREE.Color("#ffffff");
        cloned.roughness = 0.18;
        cloned.metalness = 0.0;
        if ("transmission" in cloned) {
          (cloned as THREE.MeshPhysicalMaterial).transmission = 0.35;
          (cloned as THREE.MeshPhysicalMaterial).thickness = 0.35;
          (cloned as THREE.MeshPhysicalMaterial).ior = 1.45;
          (cloned as THREE.MeshPhysicalMaterial).clearcoat = 1.0;
          (cloned as THREE.MeshPhysicalMaterial).clearcoatRoughness = 0.06;
          (cloned as THREE.MeshPhysicalMaterial).attenuationColor = new THREE.Color(COIN_BODY_HEX);
          (cloned as THREE.MeshPhysicalMaterial).attenuationDistance = 1.6;
        }
        if ("emissive" in cloned) {
          cloned.emissive = new THREE.Color("#ffffff");
          cloned.emissiveMap = faceMap;
          cloned.emissiveIntensity = 0.12;
        }
      } else {
        // Rim — deeper purple, glossy with subtle transmission. The
        // bevel catches the key light and reads as the gem edge.
        cloned.map = null;
        cloned.color = COIN_RIM_COLOR;
        cloned.roughness = 0.18;
        cloned.metalness = 0.1;
        if ("transmission" in cloned) {
          (cloned as THREE.MeshPhysicalMaterial).transmission = 0.4;
          (cloned as THREE.MeshPhysicalMaterial).thickness = 0.45;
          (cloned as THREE.MeshPhysicalMaterial).ior = 1.5;
          (cloned as THREE.MeshPhysicalMaterial).clearcoat = 0.95;
          (cloned as THREE.MeshPhysicalMaterial).clearcoatRoughness = 0.1;
          (cloned as THREE.MeshPhysicalMaterial).attenuationColor = new THREE.Color(COIN_BODY_DEEP);
          (cloned as THREE.MeshPhysicalMaterial).attenuationDistance = 1.2;
        }
        if ("emissive" in cloned) {
          cloned.emissive = COIN_RIM_COLOR.clone().multiplyScalar(0.18);
        }
      }
      mesh.material = cloned;
    });
    return c;
  }, [gltfScene, faceMap]);

  // Drive material opacity each frame.
  useEffect(() => {
    clone.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      (mesh.material as THREE.MeshStandardMaterial).opacity = globalAlpha;
    });
  });

  // ── Advance cycle: deep z → past camera → loop. The cycle is short
  //    enough that the field always reads as "tokens streaming past".
  //    forwardProgress (a beat-level modulator) pushes coins a hair
  //    further forward without changing the cycle itself.
  const p = smoothstep(forwardProgress);
  const cyclePosNormalised =
    (((frame / FPS) / seed.cycleSec + seed.cyclePhase) % 1 + 1) % 1;
  const zRange = Z_FRONT - Z_BACK;
  const zBase = Z_BACK + cyclePosNormalised * zRange;
  const zOffset = p * 1.2;
  const z = zBase + zOffset;

  // Fade — short fade-in at the start of the cycle, longer fade-out
  // as the coin passes the camera so it glides out rather than pops.
  const fadeIn = smoothstep(cyclePosNormalised / FADE_IN_BAND);
  const fadeOut =
    1 - smoothstep((cyclePosNormalised - (1 - FADE_OUT_BAND)) / FADE_OUT_BAND);
  const cycleAlpha = Math.min(fadeIn, fadeOut);

  // Scale grows as the coin approaches (perspective amplifier — makes
  // the close pass feel close at constant world scale).
  const scale = seed.baseScale * (1 + cyclePosNormalised * 0.4);

  // ── Orientation
  // GLB lies flat in XZ (face normal ±Y). Tip 90° around X so the
  // face points toward the camera. On top of that, the coin wobbles
  // back and forth on a DIAGONAL axis. The diagonal axis is either
  // /-direction (+1) or \-direction (-1). The total swing covers
  // -wobbleAmplitudeDeg..+wobbleAmplitudeDeg (so 60° or 30° range).
  // At least 5 seconds for a full 60° swing → max 12°/s.
  const baseOrient = new THREE.Quaternion().setFromAxisAngle(
    new THREE.Vector3(1, 0, 0),
    Math.PI / 2,
  );
  const wobbleSpeed = (Math.PI * 2) / (seed.wobblePeriodSec * FPS);
  const wobbleRad =
    (seed.wobbleAmplitudeDeg * Math.PI) / 180 *
    Math.sin(seed.wobblePhase + frame * wobbleSpeed);
  const staticRad = (seed.staticTiltDeg * Math.PI) / 180;
  const totalAngle = wobbleRad + staticRad;
  // Diagonal axis in world space. Camera looks along -Z, so the X/Y
  // plane is the screen plane. A "/" diagonal is (1, 1, 0)/√2; a
  // "\" diagonal is (1, -1, 0)/√2. Direction sign just flips Y.
  const ax = Math.SQRT1_2;
  const ay = Math.SQRT1_2 * seed.tiltAxisDir;
  const diagonalAxis = new THREE.Vector3(ax, ay, 0);
  const wobbleQ = new THREE.Quaternion().setFromAxisAngle(
    diagonalAxis,
    totalAngle,
  );
  // wobbleQ * baseOrient — orient coin to face camera, then rock it.
  const quat = wobbleQ.clone().multiply(baseOrient);

  // Apply the cycle-fade by scaling material alpha via group opacity.
  // Instead of a render attribute, drive it on the materials directly.
  useEffect(() => {
    clone.traverse((obj) => {
      const mesh = obj as THREE.Mesh;
      if (!mesh.isMesh) return;
      if (Array.isArray(mesh.material)) return;
      (mesh.material as THREE.MeshStandardMaterial).opacity =
        globalAlpha * cycleAlpha;
    });
  });

  return (
    <group position={[seed.x, seed.y, z]} scale={scale} quaternion={quat}>
      <primitive object={clone} />
    </group>
  );
};

const Scene: React.FC<{
  frame: number;
  forwardProgress: number;
  opacity: number;
}> = ({ frame, forwardProgress, opacity }) => {
  const { camera } = useThree();
  const gltf = useGLTF(COIN_MODEL_URL);
  // Procedural face — green disc with white pill mark.
  const faceMap = useMemo(() => buildFaceTexture(), []);

  const persp = camera as THREE.PerspectiveCamera;
  persp.position.set(0, 0.5, 14);
  persp.lookAt(0, 0, 0);
  persp.fov = 40;
  persp.updateProjectionMatrix();

  return (
    <>
      {/* Hemisphere fill so the rim metal has something to reflect
          (without a costly HDRI). */}
      <hemisphereLight args={["#ffffff", "#9eb5c8", 0.9]} />
      <ambientLight intensity={0.45} color="#ffffff" />
      <directionalLight position={[4, 9, 10]} intensity={1.4} color="#ffffff" />
      <directionalLight position={[-6, 3, -4]} intensity={0.6} color="#b8e8d8" />
      <directionalLight position={[0, -5, 6]} intensity={0.35} color="#e8f5ee" />
      {COIN_SEEDS.map((seed, i) => (
        <CoinMesh
          key={i}
          seed={seed}
          frame={frame}
          forwardProgress={forwardProgress}
          globalAlpha={opacity}
          gltfScene={gltf.scene}
          faceMap={faceMap}
        />
      ))}
    </>
  );
};

export const CoinsBackground: React.FC<CoinsBackgroundProps> = ({
  forwardProgress,
  opacity,
  width,
  height,
}) => {
  const frame = useCurrentFrame();

  return (
    <AbsoluteFill style={{ width, height, background: BG_GRADIENT }}>
      <ThreeCanvas
        width={width}
        height={height}
        camera={{
          fov: 40,
          near: 0.5,
          far: 200,
          position: [0, 0.5, 14],
        }}
        gl={{
          antialias: true,
          alpha: true,
          powerPreference: "high-performance",
          toneMapping: THREE.ACESFilmicToneMapping,
          toneMappingExposure: 1.05,
        }}
        style={{ background: "transparent" }}
      >
        <React.Suspense fallback={null}>
          <Scene
            frame={frame}
            forwardProgress={forwardProgress}
            opacity={opacity}
          />
        </React.Suspense>
      </ThreeCanvas>
    </AbsoluteFill>
  );
};
