// Source: https://tympanus.net/Development/OpeningSequence/
import React from "react";
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
} from "remotion";
import { loadFont } from "@remotion/google-fonts/Dosis";

/**
 * 1:1 reproduction of the Codrops "Text Opening Sequence" by Manoela Ilic.
 *
 * Original: CSS @keyframes on per-letter spans generated by lettering.js.
 * Black background, white Dosis 200 uppercase text. Each phrase fades in
 * with letters rotating from Y-90deg, converging letter-spacing, glowing
 * text-shadow — then drifts toward camera (translateZ) and fades out.
 *
 * Compressed from ~44s real-time into 300 frames (10s @ 30fps).
 */

// ── Font ─────────────────────────────────────────────────────────────────────
const { fontFamily } = loadFont("normal", {
  subsets: ["latin"],
  weights: ["200", "600"],
});

// ── Phrase data ──────────────────────────────────────────────────────────────
// Each phrase has words; some words are bold (weight 600).
// boldIndices is 0-based word index within the phrase.

interface Phrase {
  text: string;
  boldIndices: number[];
  largeFontSize?: boolean; // "Thanatos" was 150px in original
  isFinal?: boolean; // "Refresh to replay" uses FadeIn, not OpeningSequence
}

const PHRASES: Phrase[] = [
  { text: "Sometimes it's better", boldIndices: [2] }, // "better" bold
  { text: "to hide", boldIndices: [1] }, // "hide" bold
  { text: "in order to", boldIndices: [] },
  { text: "survive evil", boldIndices: [1] }, // "evil" bold
  { text: "Thanatos", boldIndices: [], largeFontSize: true },
  { text: "This fall", boldIndices: [] },
  { text: "Prepare", boldIndices: [] },
  { text: "Refresh to replay", boldIndices: [], isFinal: true },
];

// ── Timing (in frames, 300 total at 30fps) ───────────────────────────────────
// Original timing (seconds): 0, 5, 10, 15, 21, 30, 34, 40
// Original total: ~44s. Scale factor: 300/44/30 ≈ 0.227
// But we want crisp spacing. Hand-tuned frame offsets:

interface PhraseTimingEntry {
  startFrame: number;
  durationFrames: number;
}

const PHRASE_TIMING: PhraseTimingEntry[] = [
  { startFrame: 0, durationFrames: 36 }, // "Sometimes it's better"
  { startFrame: 34, durationFrames: 36 }, // "to hide"
  { startFrame: 68, durationFrames: 36 }, // "in order to"
  { startFrame: 102, durationFrames: 36 }, // "survive evil"
  { startFrame: 140, durationFrames: 56 }, // "Thanatos" (longer, like original 8s)
  { startFrame: 198, durationFrames: 36 }, // "This fall"
  { startFrame: 232, durationFrames: 36 }, // "Prepare"
  { startFrame: 266, durationFrames: 34 }, // "Refresh to replay" (FadeIn)
];

// ── OpeningSequence keyframe interpolation ───────────────────────────────────
// CSS original:
//   0%:  rotateY(-90deg), letter-spacing 80px, opacity 0.2, shadow 50px
//   50%: rotateY(0deg),   letter-spacing 14px, opacity 0.8, shadow 1px
//   85%: rotateY(0deg),   translateZ(100px),   opacity 0.8, shadow 1px
//   100%: translateZ(130px), opacity 0, shadow 10px

function getLetterStyle(
  progress: number, // 0..1 through the phrase animation
  isBold: boolean,
  largeFontSize: boolean,
): React.CSSProperties {
  // The original CSS uses `animation-timing-function: linear` so keyframe
  // percentages map directly to time. All interpolations below are linear
  // (no easing argument) to match that behavior exactly.

  // rotateY: -90 at 0%, 0 at 50%+
  const rotateY = interpolate(progress, [0, 0.5], [-90, 0], {
    extrapolateRight: "clamp",
  });

  // letter-spacing: 80px at 0%, 14px at 50%+
  const letterSpacing = interpolate(progress, [0, 0.5], [80, 14], {
    extrapolateRight: "clamp",
  });

  // translateZ: 0 through 50%, ramps to 100 at 85%, 130 at 100%
  const translateZ = interpolate(progress, [0.5, 0.85, 1.0], [0, 100, 130], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // opacity: 0.2 at 0%, 0.8 at 50%, 0.8 at 85%, 0 at 100%
  const opacity = interpolate(
    progress,
    [0, 0.5, 0.85, 1.0],
    [0.2, 0.8, 0.8, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // text-shadow blur: 50px at 0%, 1px at 50%, 1px at 85%, 10px at 100%
  const shadowBlur = interpolate(
    progress,
    [0, 0.5, 0.85, 1.0],
    [50, 1, 1, 10],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  const fontSize = largeFontSize ? 150 : 70;

  // Original CSS: color is transparent (hsla(0,0%,0%,0)), all visible text
  // comes from the white text-shadow glow. text-shadow uses full #fff —
  // opacity on the element controls overall visibility.
  return {
    display: "inline-block",
    fontFamily,
    fontSize,
    fontWeight: isBold ? 600 : 200,
    textTransform: "uppercase" as const,
    color: "hsla(0,0%,0%,0)",
    opacity,
    letterSpacing,
    textShadow: `0 0 ${shadowBlur}px #fff`,
    transform: `rotateY(${rotateY}deg) translateZ(${translateZ}px)`,
    transformStyle: "preserve-3d" as const,
    transformOrigin: "50% 50%",
    whiteSpace: "nowrap" as const,
  };
}

// ── FadeIn keyframe (for final phrase) ───────────────────────────────────────
// 0%: opacity 0, shadow 50px
// 100%: opacity 0.8, shadow 1px

function getFinalLetterStyle(progress: number): React.CSSProperties {
  // Original: `animation: FadeIn 4s linear` — also linear timing
  const opacity = interpolate(progress, [0, 1], [0, 0.8], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const shadowBlur = interpolate(progress, [0, 1], [50, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return {
    display: "inline-block",
    fontFamily,
    fontSize: 30,
    fontWeight: 200,
    textTransform: "uppercase" as const,
    color: "hsla(0,0%,0%,0)",
    opacity,
    letterSpacing: 14,
    textShadow: `0 0 ${shadowBlur}px #fff`,
    whiteSpace: "nowrap" as const,
  };
}

// ── Single animated letter ───────────────────────────────────────────────────

const AnimatedLetter: React.FC<{
  char: string;
  progress: number;
  isBold: boolean;
  largeFontSize: boolean;
  isFinal: boolean;
}> = ({ char, progress, isBold, largeFontSize, isFinal }) => {
  if (isFinal) {
    return <span style={getFinalLetterStyle(progress)}>{char}</span>;
  }
  return (
    <span style={getLetterStyle(progress, isBold, largeFontSize)}>{char}</span>
  );
};

// ── Single phrase ────────────────────────────────────────────────────────────

const AnimatedPhrase: React.FC<{
  phrase: Phrase;
  timing: PhraseTimingEntry;
  currentFrame: number;
}> = ({ phrase, timing, currentFrame }) => {
  const { startFrame, durationFrames } = timing;
  const localFrame = currentFrame - startFrame;

  // Don't render if we haven't reached this phrase yet or it's long done
  if (localFrame < -5 || localFrame > durationFrames + 10) return null;

  const words = phrase.text.split(" ");

  // Original: all letters share the same animation — no per-letter stagger.
  // Uniform progress for every character in the phrase.
  const progress = interpolate(
    localFrame,
    [0, durationFrames],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  return (
    <div
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
      }}
    >
      {words.map((word, wordIdx) => {
        const isBold = phrase.boldIndices.includes(wordIdx);

        return (
          <span
            key={wordIdx}
            style={{
              // Original: h2 > span { margin: 0 15px }
              margin: "0 15px",
              display: "flex",
              flexDirection: "row",
              alignItems: "center",
            }}
          >
            {Array.from(word).map((char, charIdx) => (
              <span
                key={charIdx}
                style={{
                  display: "inline-block",
                  perspective: 1000,
                  transformOrigin: "50% 50%",
                }}
              >
                <AnimatedLetter
                  char={char}
                  progress={progress}
                  isBold={isBold}
                  largeFontSize={phrase.largeFontSize ?? false}
                  isFinal={phrase.isFinal ?? false}
                />
              </span>
            ))}
          </span>
        );
      })}
    </div>
  );
};

// ── Main composition ─────────────────────────────────────────────────────────

export const OpeningSequence: React.FC = () => {
  const frame = useCurrentFrame();
  const { width, height } = useVideoConfig();

  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#000",
        width,
        height,
        overflow: "hidden",
      }}
    >
      {PHRASES.map((phrase, i) => (
        <AnimatedPhrase
          key={i}
          phrase={phrase}
          timing={PHRASE_TIMING[i]}
          currentFrame={frame}
        />
      ))}
    </AbsoluteFill>
  );
};
