//! Health monitor for Morpho lending protocol
//!
//! Provides monitoring capabilities for:
//! - Position health factor scanning
//! - Oracle freshness checking
//! - Mirror registry sync status
//! - Vault metrics reporting
//!
//! Generates structured JSON reports with alerts for risk events.

use crate::data_node_client::DataNodeClient;
use crate::quote::CrisisLevel;
use crate::serm::{AssetConfig, AssetPriceData, SermEngine};
use crate::tier_config::RiskTier;
use chrono::{DateTime, Utc};
use ethers::prelude::*;
use ethers::types::{Address, TransactionRequest, U256};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;
use thiserror::Error;
use tracing::{debug, info, warn};

// ============================================================================
// Constants
// ============================================================================

/// Default warning threshold for health factor
pub const DEFAULT_WARNING_HEALTH_FACTOR: f64 = 1.2;

/// Default critical threshold for health factor
pub const DEFAULT_CRITICAL_HEALTH_FACTOR: f64 = 1.05;

/// Maximum staleness before market is effectively frozen (24 hours)
pub const MAX_STALENESS_SECS: u64 = 24 * 60 * 60;

/// Default oracle cadence for Tier A (4 hours)
pub const TIER_A_CADENCE_SECS: u64 = 4 * 60 * 60;

/// Default oracle cadence for Tier B (6 hours)
pub const TIER_B_CADENCE_SECS: u64 = 6 * 60 * 60;

/// Default oracle cadence for Tier C (12 hours)
pub const TIER_C_CADENCE_SECS: u64 = 12 * 60 * 60;

/// Default oracle cadence for Tier D (24 hours)
pub const TIER_D_CADENCE_SECS: u64 = 24 * 60 * 60;

/// Default high utilization threshold percentage
pub const DEFAULT_HIGH_UTILIZATION_PCT: u8 = 90;

// ============================================================================
// Function Selectors (precomputed keccak256)
// ============================================================================

/// Selector for oracle.lastUpdated() - keccak256("lastUpdated()")[:4]
const SELECTOR_LAST_UPDATED: [u8; 4] = [0x08, 0x6d, 0x1b, 0x8a];

/// Selector for oracle.currentPrice() - keccak256("currentPrice()")[:4]
const SELECTOR_CURRENT_PRICE: [u8; 4] = [0x9d, 0x1b, 0x46, 0x4a];

/// Selector for registry.registryNonce() - keccak256("registryNonce()")[:4]
const SELECTOR_REGISTRY_NONCE: [u8; 4] = [0x6b, 0x83, 0xc2, 0xdf];

/// Selector for mirrorRegistry.activeCount() - keccak256("activeCount()")[:4]
const SELECTOR_ACTIVE_COUNT: [u8; 4] = [0x43, 0xc7, 0x0c, 0x85];

/// Selector for oracleRegistry.activeOracleCount() - keccak256("activeOracleCount()")[:4]
const SELECTOR_ACTIVE_ORACLE_COUNT: [u8; 4] = [0xbc, 0xa8, 0x6a, 0xf8];

/// Selector for vault.totalAssets() - keccak256("totalAssets()")[:4]
const SELECTOR_TOTAL_ASSETS: [u8; 4] = [0x01, 0xe1, 0xd1, 0x14];

/// Selector for vault.totalSupply() - keccak256("totalSupply()")[:4]
const SELECTOR_TOTAL_SUPPLY: [u8; 4] = [0x18, 0x16, 0x0d, 0xdd];

/// Selector for vault.idle() - keccak256("idle()")[:4]
const SELECTOR_IDLE: [u8; 4] = [0xae, 0xf8, 0xae, 0x13];

/// Selector for morpho.market(bytes32) - keccak256("market(bytes32)")[:4]
const SELECTOR_MARKET: [u8; 4] = [0x5c, 0x60, 0xe3, 0x9a];

/// Selector for morpho.position(bytes32,address) - keccak256("position(bytes32,address)")[:4]
const SELECTOR_POSITION: [u8; 4] = [0x93, 0xc5, 0x20, 0x62];

/// Selector for morpho.idToMarketParams(bytes32) - keccak256("idToMarketParams(bytes32)")[:4]
const SELECTOR_ID_TO_MARKET_PARAMS: [u8; 4] = [0x2c, 0x3c, 0x91, 0x57];

// ============================================================================
// Types - Alert System (Task 1.5)
// ============================================================================

/// Alert severity levels
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Severity {
    /// Routine status updates
    Info,
    /// Conditions requiring attention
    Warning,
    /// Conditions requiring immediate action
    Critical,
}

/// Alert categories
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertCategory {
    /// Position health alerts
    Position,
    /// Oracle freshness alerts
    Oracle,
    /// Mirror registry sync alerts
    Mirror,
    /// Vault metrics alerts
    Vault,
}

/// An alert generated by the health monitor
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    /// Severity level
    pub severity: Severity,
    /// Category of the alert
    pub category: AlertCategory,
    /// Human-readable message
    pub message: String,
    /// Additional details (JSON object)
    pub details: serde_json::Value,
}

// ============================================================================
// Types - Position Health (Task 2.1)
// ============================================================================

/// Health status of a position
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HealthStatus {
    /// Health factor >= 1.2
    Healthy,
    /// Health factor between 1.05 and 1.2
    Warning,
    /// Health factor between 1.0 and 1.05
    Critical,
    /// Health factor < 1.0
    Liquidatable,
}

/// Health metrics for a single borrow position
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionHealth {
    /// Borrower address
    pub borrower: Address,
    /// Market identifier
    #[serde(with = "hex_bytes32")]
    pub market_id: [u8; 32],
    /// Collateral amount (in collateral tokens)
    pub collateral: U256,
    /// Borrow shares held
    pub borrow_shares: U256,
    /// Debt assets (converted from shares)
    pub debt_assets: U256,
    /// Computed health factor
    pub health_factor: f64,
    /// Health status classification
    pub status: HealthStatus,
}

// ============================================================================
// Types - Oracle Status (Task 3.1)
// ============================================================================

/// Status of an ITPNAVOracle
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OracleStatus {
    /// Oracle contract address
    pub oracle_address: Address,
    /// ITP token address this oracle serves
    pub itp_address: Address,
    /// Timestamp of last price update
    pub last_updated: u64,
    /// Current price (36 decimal precision for Morpho)
    pub current_price: U256,
    /// Age in seconds since last update
    pub age_secs: u64,
    /// Whether oracle is stale (exceeds tier cadence)
    pub is_stale: bool,
    /// Whether oracle is frozen (exceeds MAX_STALENESS)
    pub is_frozen: bool,
    /// Configured cadence for this oracle's risk tier
    pub configured_cadence: u64,
}

// ============================================================================
// Types - Mirror Sync Status (Task 4.1)
// ============================================================================

/// Sync status between L3 OracleRegistry and MirrorOracleRegistry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MirrorSyncStatus {
    /// Registry nonce on L3
    pub l3_nonce: u64,
    /// Registry nonce on mirror (settlement chain)
    pub mirror_nonce: u64,
    /// Nonce gap (l3 - mirror)
    pub nonce_gap: i64,
    /// Whether registries are in sync
    pub is_synced: bool,
    /// Active oracle count on L3
    pub l3_active_count: u64,
    /// Active count on mirror
    pub mirror_active_count: u64,
}

// ============================================================================
// Types - Vault Metrics (Task 5.1)
// ============================================================================

/// Metrics for the MetaMorpho vault
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VaultMetrics {
    /// Total assets deposited (USDC)
    pub total_assets: U256,
    /// Total vault shares
    pub total_supply: U256,
    /// Idle assets (not allocated to markets)
    pub idle_assets: U256,
    /// Utilization percentage (0-100)
    pub utilization_pct: u8,
    /// Number of markets the vault supplies to
    pub markets_count: usize,
    /// Whether utilization is critically high
    pub high_utilization: bool,
}

// ============================================================================
// Types - Alert Config (Task 1.3)
// ============================================================================

/// Configuration for alert thresholds
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlertConfig {
    /// Health factor below which to generate WARNING
    pub warning_health_factor: f64,
    /// Health factor below which to generate CRITICAL
    pub critical_health_factor: f64,
    /// Oracle staleness thresholds per risk tier (in seconds)
    pub oracle_stale_secs: HashMap<RiskTier, u64>,
    /// Utilization percentage above which to flag high utilization
    pub high_utilization_pct: u8,
}

impl Default for AlertConfig {
    fn default() -> Self {
        let mut oracle_stale_secs = HashMap::new();
        oracle_stale_secs.insert(RiskTier::A, TIER_A_CADENCE_SECS);
        oracle_stale_secs.insert(RiskTier::B, TIER_B_CADENCE_SECS);
        oracle_stale_secs.insert(RiskTier::C, TIER_C_CADENCE_SECS);
        oracle_stale_secs.insert(RiskTier::D, TIER_D_CADENCE_SECS);

        Self {
            warning_health_factor: DEFAULT_WARNING_HEALTH_FACTOR,
            critical_health_factor: DEFAULT_CRITICAL_HEALTH_FACTOR,
            oracle_stale_secs,
            high_utilization_pct: DEFAULT_HIGH_UTILIZATION_PCT,
        }
    }
}

// ============================================================================
// Types - Health Report (Task 1.4)
// ============================================================================

/// Complete health report from a monitoring scan cycle
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthReport {
    /// When this scan was performed
    pub timestamp: DateTime<Utc>,
    /// Health status of all scanned positions
    pub positions: Vec<PositionHealth>,
    /// Status of all monitored oracles
    pub oracles: Vec<OracleStatus>,
    /// Mirror registry sync status
    pub mirror_sync: MirrorSyncStatus,
    /// Vault metrics
    pub vault_metrics: VaultMetrics,
    /// Generated alerts
    pub alerts: Vec<Alert>,
    /// Crisis level per market (market_id hex → CrisisLevel)
    #[serde(default)]
    pub crisis_levels: HashMap<String, CrisisLevel>,
}

// ============================================================================
// Errors
// ============================================================================

/// Errors from the health monitor
#[derive(Debug, Error)]
pub enum MonitorError {
    #[error("Failed to read from chain: {0}")]
    ReadError(String),

    #[error("Provider error: {0}")]
    Provider(String),

    #[error("Failed to connect to L3 RPC: {0}")]
    L3ConnectionError(String),

    #[error("Operation timed out: {0}")]
    Timeout(String),

    #[error("Invalid data: {0}")]
    InvalidData(String),

    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
}

// ============================================================================
// Health Monitor (Task 1.2)
// ============================================================================

/// Health monitor for Morpho lending protocol
pub struct HealthMonitor {
    /// Main chain provider (settlement/deployment chain)
    provider: Arc<Provider<Http>>,
    /// L3 chain provider (for OracleRegistry)
    l3_provider: Arc<Provider<Http>>,
    /// Morpho Blue contract address
    morpho_address: Address,
    /// MetaMorpho vault address
    vault_address: Address,
    /// Oracle addresses to monitor
    oracle_addresses: Vec<Address>,
    /// ITP addresses corresponding to oracles
    itp_addresses: Vec<Address>,
    /// Mirror registry address (on settlement chain)
    mirror_registry_address: Address,
    /// L3 OracleRegistry address
    l3_registry_address: Address,
    /// Market IDs to monitor
    market_ids: Vec<[u8; 32]>,
    /// Alert configuration
    alert_config: AlertConfig,
    /// Oracle risk tier mappings
    oracle_tiers: HashMap<Address, RiskTier>,
    /// Known borrowers per market (for position scanning)
    known_borrowers: HashMap<[u8; 32], Vec<Address>>,
    /// RPC timeout
    rpc_timeout: Duration,
    /// Data node service URL (e.g., "http://localhost:8200") for asset stress computation
    data_node_url: Option<String>,
    /// HTTP client for data-node API calls
    http_client: reqwest::Client,
    /// Data-node HTTP client for L3 chain reads (replaces direct RPC when configured)
    data_node_client: Option<DataNodeClient>,
}

impl HealthMonitor {
    /// Create a new health monitor
    pub fn new(
        rpc_url: &str,
        l3_rpc_url: &str,
        morpho_address: Address,
        vault_address: Address,
        oracle_addresses: Vec<Address>,
        itp_addresses: Vec<Address>,
        mirror_registry_address: Address,
        l3_registry_address: Address,
        market_ids: Vec<[u8; 32]>,
        alert_config: AlertConfig,
    ) -> Result<Self, MonitorError> {
        let provider = Provider::<Http>::try_from(rpc_url)
            .map_err(|e| MonitorError::Provider(format!("Failed to create provider: {}", e)))?;

        let l3_provider = Provider::<Http>::try_from(l3_rpc_url).map_err(|e| {
            MonitorError::L3ConnectionError(format!("Failed to create L3 provider: {}", e))
        })?;

        Ok(Self {
            provider: Arc::new(provider),
            l3_provider: Arc::new(l3_provider),
            morpho_address,
            vault_address,
            oracle_addresses,
            itp_addresses,
            mirror_registry_address,
            l3_registry_address,
            market_ids,
            alert_config,
            oracle_tiers: HashMap::new(),
            known_borrowers: HashMap::new(),
            rpc_timeout: Duration::from_secs(30),
            data_node_url: None,
            // Default Client has no timeout. A health monitor that hangs
            // on every poll is worse than one that fails to start.
            http_client: reqwest::Client::builder()
                .timeout(Duration::from_secs(10))
                .build()
                .expect("reqwest::Client::builder failed — TLS or DNS backend missing"),
            data_node_client: None,
        })
    }

    /// Set risk tier for an oracle
    pub fn set_oracle_tier(&mut self, oracle_address: Address, tier: RiskTier) {
        self.oracle_tiers.insert(oracle_address, tier);
    }

    /// Add a known borrower for a market
    pub fn add_known_borrower(&mut self, market_id: [u8; 32], borrower: Address) {
        self.known_borrowers
            .entry(market_id)
            .or_default()
            .push(borrower);
    }

    /// Set the data node service URL for asset stress computation and L3 chain reads
    pub fn set_data_node_url(&mut self, url: String) {
        info!(url = %url, "Data node URL configured for health monitor (stress + L3 reads)");
        self.data_node_client = Some(DataNodeClient::new(&url));
        self.data_node_url = Some(url);
    }

    /// Fetch current and 24h-ago prices from the data-node service,
    /// compute per-asset stress using SERM, return average stress for use as market-wide stress.
    async fn fetch_asset_stress(&self) -> f64 {
        let base_url = match &self.data_node_url {
            Some(url) => url,
            None => return 0.0,
        };

        // 1. Fetch all current prices from /fast-prices
        let fast_prices_url = format!("{}/fast-prices", base_url);
        let current_prices: HashMap<String, f64> = match self
            .http_client
            .get(&fast_prices_url)
            .send()
            .await
        {
            Ok(resp) => {
                match resp.json::<serde_json::Value>().await {
                    Ok(json) => {
                        let mut prices = HashMap::new();
                        if let Some(obj) = json.get("prices").and_then(|p| p.as_object()) {
                            for (symbol, entry) in obj {
                                if let Some(price_str) = entry.get("last_price").and_then(|p| p.as_str()) {
                                    if let Ok(price) = price_str.parse::<f64>() {
                                        prices.insert(symbol.clone(), price);
                                    }
                                }
                            }
                        }
                        debug!(count = prices.len(), "Fetched fast prices for stress computation");
                        prices
                    }
                    Err(e) => {
                        warn!(error = %e, "Failed to parse fast-prices response");
                        return 0.0;
                    }
                }
            }
            Err(e) => {
                warn!(error = %e, url = %fast_prices_url, "Failed to fetch fast-prices");
                return 0.0;
            }
        };

        if current_prices.is_empty() {
            return 0.0;
        }

        // 2. Fetch 24h-ago prices for each symbol via /price?symbol=X&at=<24h_ago>
        let now = Utc::now();
        let ago_24h = now - chrono::Duration::hours(24);
        let ago_str = ago_24h.to_rfc3339();

        let mut stress_values: Vec<f64> = Vec::new();

        for (symbol, current_price) in &current_prices {
            let hist_url = format!(
                "{}/price?symbol={}&at={}",
                base_url, symbol, ago_str
            );
            match self.http_client.get(&hist_url).send().await {
                Ok(resp) => {
                    if let Ok(json) = resp.json::<serde_json::Value>().await {
                        if let Some(price_str) = json.get("price").and_then(|p| p.as_str()) {
                            if let Ok(price_24h_ago) = price_str.parse::<f64>() {
                                // Convert f64 prices to WAD-scaled U256 for SERM
                                let current_wad = U256::from((current_price * 1e18) as u128);
                                let ago_wad = U256::from((price_24h_ago * 1e18) as u128);

                                let price_data = AssetPriceData {
                                    price: current_wad,
                                    price_24h_ago: ago_wad,
                                };
                                let config = AssetConfig::default(); // 3% baseline vol, 0.5 liquidity

                                let stress_wad = SermEngine::compute_asset_stress(&price_data, &config);
                                let stress_f64 = stress_wad.as_u128() as f64 / 1e18;

                                if stress_f64 > 0.0 {
                                    debug!(
                                        symbol = %symbol,
                                        current = %current_price,
                                        ago_24h = %price_24h_ago,
                                        stress = %stress_f64,
                                        "Asset stress computed"
                                    );
                                }

                                stress_values.push(stress_f64);
                            }
                        }
                    }
                }
                Err(_) => {
                    // Historical price not available for this symbol — skip
                }
            }
        }

        if stress_values.is_empty() {
            return 0.0;
        }

        // Use the maximum stress across all assets as conservative market-wide stress.
        // Any single high-stress asset in a basket should raise the alarm.
        let max_stress = stress_values.iter().cloned().fold(0.0f64, f64::max);
        if max_stress > 0.0 {
            info!(
                max_stress = %max_stress,
                assets_checked = stress_values.len(),
                stressed_assets = stress_values.iter().filter(|&&s| s > 0.0).count(),
                "Asset stress computed from data-node"
            );
        }
        max_stress
    }

    /// Get the configured cadence for an oracle based on its risk tier
    fn get_oracle_cadence(&self, oracle_address: &Address) -> u64 {
        let tier = self.oracle_tiers.get(oracle_address).unwrap_or(&RiskTier::D);
        *self
            .alert_config
            .oracle_stale_secs
            .get(tier)
            .unwrap_or(&TIER_D_CADENCE_SECS)
    }

    // ========================================================================
    // Data-Node RPC Fallback Helpers
    // ========================================================================

    /// Read L3 activeOracleCount via direct RPC (fallback when data-node unavailable)
    async fn rpc_read_l3_active_oracle_count(&self) -> u64 {
        let tx = TransactionRequest::new()
            .to(self.l3_registry_address)
            .data(SELECTOR_ACTIVE_ORACLE_COUNT.to_vec());

        match tokio::time::timeout(
            self.rpc_timeout,
            self.l3_provider.call(&tx.into(), None),
        )
        .await
        {
            Ok(Ok(result)) if result.len() >= 32 => {
                U256::from_big_endian(&result[0..32]).as_u64()
            }
            _ => 0,
        }
    }

    // ========================================================================
    // Position Health Factor Scanner (Task 2)
    // ========================================================================

    /// Scan all positions in a market and compute health factors
    pub async fn scan_positions(
        &self,
        market_id: [u8; 32],
    ) -> Result<Vec<PositionHealth>, MonitorError> {
        let borrowers = self
            .known_borrowers
            .get(&market_id)
            .cloned()
            .unwrap_or_default();

        if borrowers.is_empty() {
            debug!(
                market_id = %hex::encode(market_id),
                "No known borrowers for market"
            );
            return Ok(vec![]);
        }

        // Read market data once
        let (total_borrow_assets, total_borrow_shares, lltv) =
            self.read_market_data(market_id).await?;

        // Read oracle price from market params
        let oracle_address = self.read_market_oracle(market_id).await?;
        let oracle_price = self.read_oracle_price(oracle_address).await?;

        let mut positions = Vec::new();

        for borrower in borrowers {
            match self
                .read_position(
                    market_id,
                    borrower,
                    total_borrow_assets,
                    total_borrow_shares,
                    oracle_price,
                    lltv,
                )
                .await
            {
                Ok(Some(pos)) => positions.push(pos),
                Ok(None) => {} // No borrow position
                Err(e) => {
                    warn!(
                        borrower = ?borrower,
                        error = %e,
                        "Failed to read position"
                    );
                }
            }
        }

        Ok(positions)
    }

    /// Read market data from Morpho
    async fn read_market_data(
        &self,
        market_id: [u8; 32],
    ) -> Result<(U256, U256, U256), MonitorError> {
        let mut calldata = SELECTOR_MARKET.to_vec();
        calldata.extend_from_slice(&market_id);

        let tx = TransactionRequest::new()
            .to(self.morpho_address)
            .data(calldata);

        let result = tokio::time::timeout(self.rpc_timeout, self.provider.call(&tx.into(), None))
            .await
            .map_err(|_| MonitorError::Timeout("market() call".to_string()))?
            .map_err(|e| MonitorError::ReadError(format!("market() call failed: {}", e)))?;

        if result.len() < 192 {
            return Err(MonitorError::InvalidData(format!(
                "Invalid market data length: {}",
                result.len()
            )));
        }

        // Decode: totalSupplyAssets, totalSupplyShares, totalBorrowAssets, totalBorrowShares, ...
        let total_borrow_assets = U256::from_big_endian(&result[64..96]);
        let total_borrow_shares = U256::from_big_endian(&result[96..128]);

        // Read LLTV from market params
        let lltv = self.read_market_lltv(market_id).await?;

        Ok((total_borrow_assets, total_borrow_shares, lltv))
    }

    /// Read market LLTV from idToMarketParams
    async fn read_market_lltv(&self, market_id: [u8; 32]) -> Result<U256, MonitorError> {
        let mut calldata = SELECTOR_ID_TO_MARKET_PARAMS.to_vec();
        calldata.extend_from_slice(&market_id);

        let tx = TransactionRequest::new()
            .to(self.morpho_address)
            .data(calldata);

        let result = tokio::time::timeout(self.rpc_timeout, self.provider.call(&tx.into(), None))
            .await
            .map_err(|_| MonitorError::Timeout("idToMarketParams() call".to_string()))?
            .map_err(|e| MonitorError::ReadError(format!("idToMarketParams() call failed: {}", e)))?;

        if result.len() < 160 {
            return Err(MonitorError::InvalidData(format!(
                "Invalid idToMarketParams data length: {}",
                result.len()
            )));
        }

        // LLTV is at offset 128-160
        Ok(U256::from_big_endian(&result[128..160]))
    }

    /// Read market oracle address from idToMarketParams
    async fn read_market_oracle(&self, market_id: [u8; 32]) -> Result<Address, MonitorError> {
        let mut calldata = SELECTOR_ID_TO_MARKET_PARAMS.to_vec();
        calldata.extend_from_slice(&market_id);

        let tx = TransactionRequest::new()
            .to(self.morpho_address)
            .data(calldata);

        let result = tokio::time::timeout(self.rpc_timeout, self.provider.call(&tx.into(), None))
            .await
            .map_err(|_| MonitorError::Timeout("idToMarketParams() call".to_string()))?
            .map_err(|e| MonitorError::ReadError(format!("idToMarketParams() call failed: {}", e)))?;

        if result.len() < 96 {
            return Err(MonitorError::InvalidData(format!(
                "Invalid idToMarketParams data length: {}",
                result.len()
            )));
        }

        // Oracle is at offset 76-96 (third address, padded to 32 bytes)
        Ok(Address::from_slice(&result[76..96]))
    }

    /// Read oracle price
    async fn read_oracle_price(&self, oracle_address: Address) -> Result<U256, MonitorError> {
        let tx = TransactionRequest::new()
            .to(oracle_address)
            .data(SELECTOR_CURRENT_PRICE.to_vec());

        let result = tokio::time::timeout(self.rpc_timeout, self.provider.call(&tx.into(), None))
            .await
            .map_err(|_| MonitorError::Timeout("currentPrice() call".to_string()))?
            .map_err(|e| MonitorError::ReadError(format!("currentPrice() call failed: {}", e)))?;

        if result.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid currentPrice response".to_string(),
            ));
        }

        Ok(U256::from_big_endian(&result[0..32]))
    }

    /// Read a single position
    async fn read_position(
        &self,
        market_id: [u8; 32],
        borrower: Address,
        total_borrow_assets: U256,
        total_borrow_shares: U256,
        oracle_price: U256,
        lltv: U256,
    ) -> Result<Option<PositionHealth>, MonitorError> {
        let mut calldata = SELECTOR_POSITION.to_vec();
        calldata.extend_from_slice(&market_id);
        // Pad address to 32 bytes
        calldata.extend_from_slice(&[0u8; 12]);
        calldata.extend_from_slice(borrower.as_bytes());

        let tx = TransactionRequest::new()
            .to(self.morpho_address)
            .data(calldata);

        let result = tokio::time::timeout(self.rpc_timeout, self.provider.call(&tx.into(), None))
            .await
            .map_err(|_| MonitorError::Timeout("position() call".to_string()))?
            .map_err(|e| MonitorError::ReadError(format!("position() call failed: {}", e)))?;

        if result.len() < 96 {
            return Err(MonitorError::InvalidData(format!(
                "Invalid position data length: {}",
                result.len()
            )));
        }

        // Position returns: supplyShares, borrowShares, collateral
        let _supply_shares = U256::from_big_endian(&result[0..32]);
        let borrow_shares = U256::from_big_endian(&result[32..64]);
        let collateral = U256::from_big_endian(&result[64..96]);

        // Skip positions with no borrows
        if borrow_shares.is_zero() {
            return Ok(None);
        }

        // Convert borrow shares to assets
        let debt_assets = if total_borrow_shares.is_zero() {
            U256::zero()
        } else {
            borrow_shares
                .checked_mul(total_borrow_assets)
                .unwrap_or(U256::MAX)
                .checked_div(total_borrow_shares)
                .unwrap_or(U256::zero())
        };

        // Compute health factor
        let health_factor =
            compute_health_factor(collateral, debt_assets, lltv, oracle_price);

        // Classify health status
        let status = classify_health_status(health_factor, &self.alert_config);

        Ok(Some(PositionHealth {
            borrower,
            market_id,
            collateral,
            borrow_shares,
            debt_assets,
            health_factor,
            status,
        }))
    }

    /// Run scan cycle with externally-provided asset stress data from SERM
    pub async fn run_scan_cycle_with_stress(
        &self,
        external_stress: &HashMap<[u8; 32], f64>,
        external_nav_drops: &HashMap<[u8; 32], f64>,
    ) -> Result<HealthReport, MonitorError> {
        let mut report = self.run_scan_cycle().await?;
        // Recompute crisis levels with actual stress data
        let crisis_levels = compute_crisis_levels(
            &report.positions,
            &self.market_ids,
            external_stress,
            external_nav_drops,
        );
        report.crisis_levels = crisis_levels;
        Ok(report)
    }

    /// Trigger oracle refresh for critical positions (Phase 1: log only)
    pub async fn trigger_oracle_refresh(
        &self,
        oracle_address: Address,
    ) -> Result<(), MonitorError> {
        // Phase 1: Log only, actual trigger in Phase 2
        info!(
            oracle = ?oracle_address,
            "Would trigger oracle refresh for critical position (Phase 1: log only)"
        );
        Ok(())
    }

    // ========================================================================
    // Oracle Freshness Checker (Task 3)
    // ========================================================================

    /// Check freshness of an oracle
    pub async fn check_oracle_freshness(
        &self,
        oracle_address: Address,
        itp_address: Address,
    ) -> Result<OracleStatus, MonitorError> {
        // Read lastUpdated
        let tx_last_updated = TransactionRequest::new()
            .to(oracle_address)
            .data(SELECTOR_LAST_UPDATED.to_vec());

        let result_last_updated = tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_last_updated.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("lastUpdated() call".to_string()))?
        .map_err(|e| MonitorError::ReadError(format!("lastUpdated() call failed: {}", e)))?;

        if result_last_updated.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid lastUpdated response".to_string(),
            ));
        }

        let last_updated = U256::from_big_endian(&result_last_updated[0..32]).as_u64();

        // Read currentPrice
        let tx_price = TransactionRequest::new()
            .to(oracle_address)
            .data(SELECTOR_CURRENT_PRICE.to_vec());

        let result_price = tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_price.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("currentPrice() call".to_string()))?
        .map_err(|e| MonitorError::ReadError(format!("currentPrice() call failed: {}", e)))?;

        if result_price.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid currentPrice response".to_string(),
            ));
        }

        let current_price = U256::from_big_endian(&result_price[0..32]);

        // Get current block timestamp
        let block = self
            .provider
            .get_block(BlockNumber::Latest)
            .await
            .map_err(|e| MonitorError::Provider(format!("Failed to get block: {}", e)))?
            .ok_or_else(|| MonitorError::InvalidData("No latest block".to_string()))?;

        let now = block.timestamp.as_u64();
        let age_secs = now.saturating_sub(last_updated);

        let configured_cadence = self.get_oracle_cadence(&oracle_address);
        let is_stale = age_secs > configured_cadence;
        let is_frozen = age_secs > MAX_STALENESS_SECS;

        Ok(OracleStatus {
            oracle_address,
            itp_address,
            last_updated,
            current_price,
            age_secs,
            is_stale,
            is_frozen,
            configured_cadence,
        })
    }

    // ========================================================================
    // Mirror Registry Sync Checker (Task 4)
    // ========================================================================

    /// Check sync status between L3 and mirror registries
    pub async fn check_mirror_sync(&self) -> Result<MirrorSyncStatus, MonitorError> {
        // Read L3 registry nonce
        let tx_l3 = TransactionRequest::new()
            .to(self.l3_registry_address)
            .data(SELECTOR_REGISTRY_NONCE.to_vec());

        let result_l3 = tokio::time::timeout(
            self.rpc_timeout,
            self.l3_provider.call(&tx_l3.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("L3 registryNonce() call".to_string()))?
        .map_err(|e| {
            MonitorError::L3ConnectionError(format!("L3 registryNonce() call failed: {}", e))
        })?;

        if result_l3.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid L3 registryNonce response".to_string(),
            ));
        }

        let l3_nonce = U256::from_big_endian(&result_l3[0..32]).as_u64();

        // Read mirror registry nonce
        let tx_mirror = TransactionRequest::new()
            .to(self.mirror_registry_address)
            .data(SELECTOR_REGISTRY_NONCE.to_vec());

        let result_mirror = tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_mirror.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("mirror registryNonce() call".to_string()))?
        .map_err(|e| {
            MonitorError::ReadError(format!("mirror registryNonce() call failed: {}", e))
        })?;

        if result_mirror.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid mirror registryNonce response".to_string(),
            ));
        }

        let mirror_nonce = U256::from_big_endian(&result_mirror[0..32]).as_u64();

        // Read active counts (L3) — use data-node if available, otherwise direct RPC
        let l3_active_count = if let Some(ref dn) = self.data_node_client {
            match dn.get_active_oracle_count().await {
                Ok(count) => {
                    debug!(count, "L3 active oracle count via data-node");
                    count
                }
                Err(e) => {
                    warn!(error = %e, "Data-node activeOracleCount failed, falling back to RPC");
                    self.rpc_read_l3_active_oracle_count().await
                }
            }
        } else {
            self.rpc_read_l3_active_oracle_count().await
        };

        // Read active counts (mirror)
        let tx_mirror_count = TransactionRequest::new()
            .to(self.mirror_registry_address)
            .data(SELECTOR_ACTIVE_COUNT.to_vec());

        let mirror_active_count = match tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_mirror_count.into(), None),
        )
        .await
        {
            Ok(Ok(result)) if result.len() >= 32 => {
                U256::from_big_endian(&result[0..32]).as_u64()
            }
            _ => 0, // Default if call fails
        };

        let nonce_gap = l3_nonce as i64 - mirror_nonce as i64;
        let is_synced = nonce_gap == 0;

        Ok(MirrorSyncStatus {
            l3_nonce,
            mirror_nonce,
            nonce_gap,
            is_synced,
            l3_active_count,
            mirror_active_count,
        })
    }

    // ========================================================================
    // Vault Metrics Reader (Task 5)
    // ========================================================================

    /// Read vault metrics from MetaMorpho
    pub async fn read_vault_metrics(&self) -> Result<VaultMetrics, MonitorError> {
        // Read totalAssets
        let tx_assets = TransactionRequest::new()
            .to(self.vault_address)
            .data(SELECTOR_TOTAL_ASSETS.to_vec());

        let result_assets = tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_assets.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("totalAssets() call".to_string()))?
        .map_err(|e| MonitorError::ReadError(format!("totalAssets() call failed: {}", e)))?;

        if result_assets.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid totalAssets response".to_string(),
            ));
        }

        let total_assets = U256::from_big_endian(&result_assets[0..32]);

        // Read totalSupply
        let tx_supply = TransactionRequest::new()
            .to(self.vault_address)
            .data(SELECTOR_TOTAL_SUPPLY.to_vec());

        let result_supply = tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_supply.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("totalSupply() call".to_string()))?
        .map_err(|e| MonitorError::ReadError(format!("totalSupply() call failed: {}", e)))?;

        if result_supply.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid totalSupply response".to_string(),
            ));
        }

        let total_supply = U256::from_big_endian(&result_supply[0..32]);

        // Read idle assets
        let tx_idle = TransactionRequest::new()
            .to(self.vault_address)
            .data(SELECTOR_IDLE.to_vec());

        let result_idle = tokio::time::timeout(
            self.rpc_timeout,
            self.provider.call(&tx_idle.into(), None),
        )
        .await
        .map_err(|_| MonitorError::Timeout("idle() call".to_string()))?
        .map_err(|e| MonitorError::ReadError(format!("idle() call failed: {}", e)))?;

        if result_idle.len() < 32 {
            return Err(MonitorError::InvalidData(
                "Invalid idle response".to_string(),
            ));
        }

        let idle_assets = U256::from_big_endian(&result_idle[0..32]);

        // Compute utilization: (totalAssets - idle) * 100 / totalAssets
        let utilization_pct = if total_assets.is_zero() {
            0u8
        } else {
            let utilized = total_assets.saturating_sub(idle_assets);
            let util = utilized
                .checked_mul(U256::from(100))
                .unwrap_or(U256::MAX)
                .checked_div(total_assets)
                .unwrap_or(U256::zero());
            util.as_u64().min(100) as u8
        };

        let high_utilization = utilization_pct > self.alert_config.high_utilization_pct;
        let markets_count = self.market_ids.len();

        Ok(VaultMetrics {
            total_assets,
            total_supply,
            idle_assets,
            utilization_pct,
            markets_count,
            high_utilization,
        })
    }

    // ========================================================================
    // Main Monitoring Loop (Task 6)
    // ========================================================================

    /// Run a complete scan cycle and generate a health report
    pub async fn run_scan_cycle(&self) -> Result<HealthReport, MonitorError> {
        let timestamp = Utc::now();
        let mut alerts = Vec::new();

        // Scan all positions
        let mut all_positions = Vec::new();
        for market_id in &self.market_ids {
            match self.scan_positions(*market_id).await {
                Ok(positions) => {
                    for pos in &positions {
                        // Generate alerts for unhealthy positions
                        if pos.status == HealthStatus::Critical
                            || pos.status == HealthStatus::Liquidatable
                        {
                            alerts.push(Alert {
                                severity: Severity::Critical,
                                category: AlertCategory::Position,
                                message: format!(
                                    "Position {} has critical health factor {:.4}",
                                    pos.borrower, pos.health_factor
                                ),
                                details: serde_json::json!({
                                    "borrower": format!("{:?}", pos.borrower),
                                    "health_factor": pos.health_factor,
                                    "collateral": pos.collateral.to_string(),
                                    "debt": pos.debt_assets.to_string(),
                                }),
                            });
                        } else if pos.status == HealthStatus::Warning {
                            alerts.push(Alert {
                                severity: Severity::Warning,
                                category: AlertCategory::Position,
                                message: format!(
                                    "Position {} has low health factor {:.4}",
                                    pos.borrower, pos.health_factor
                                ),
                                details: serde_json::json!({
                                    "borrower": format!("{:?}", pos.borrower),
                                    "health_factor": pos.health_factor,
                                }),
                            });
                        }
                    }
                    all_positions.extend(positions);
                }
                Err(e) => {
                    warn!(
                        market_id = %hex::encode(market_id),
                        error = %e,
                        "Failed to scan positions for market"
                    );
                }
            }
        }

        // Check all oracles
        let mut oracles = Vec::new();
        for (i, oracle_address) in self.oracle_addresses.iter().enumerate() {
            let itp_address = self
                .itp_addresses
                .get(i)
                .copied()
                .unwrap_or(Address::zero());

            match self
                .check_oracle_freshness(*oracle_address, itp_address)
                .await
            {
                Ok(status) => {
                    if status.is_frozen {
                        alerts.push(Alert {
                            severity: Severity::Critical,
                            category: AlertCategory::Oracle,
                            message: format!(
                                "Oracle {:?} is FROZEN ({} seconds old, MAX_STALENESS: {})",
                                oracle_address, status.age_secs, MAX_STALENESS_SECS
                            ),
                            details: serde_json::json!({
                                "oracle_address": format!("{:?}", oracle_address),
                                "age_secs": status.age_secs,
                                "max_staleness": MAX_STALENESS_SECS,
                            }),
                        });
                    } else if status.is_stale {
                        alerts.push(Alert {
                            severity: Severity::Warning,
                            category: AlertCategory::Oracle,
                            message: format!(
                                "Oracle {:?} is stale ({} seconds old, cadence: {})",
                                oracle_address, status.age_secs, status.configured_cadence
                            ),
                            details: serde_json::json!({
                                "oracle_address": format!("{:?}", oracle_address),
                                "age_secs": status.age_secs,
                                "configured_cadence": status.configured_cadence,
                            }),
                        });
                    }
                    oracles.push(status);
                }
                Err(e) => {
                    warn!(
                        oracle = ?oracle_address,
                        error = %e,
                        "Failed to check oracle freshness"
                    );
                }
            }
        }

        // Check mirror sync
        let mirror_sync = self.check_mirror_sync().await?;
        if mirror_sync.nonce_gap > 2 {
            alerts.push(Alert {
                severity: Severity::Critical,
                category: AlertCategory::Mirror,
                message: format!(
                    "Mirror registry significantly behind L3 (gap: {})",
                    mirror_sync.nonce_gap
                ),
                details: serde_json::json!({
                    "l3_nonce": mirror_sync.l3_nonce,
                    "mirror_nonce": mirror_sync.mirror_nonce,
                    "gap": mirror_sync.nonce_gap,
                }),
            });
        } else if mirror_sync.nonce_gap > 0 {
            alerts.push(Alert {
                severity: Severity::Warning,
                category: AlertCategory::Mirror,
                message: format!(
                    "Mirror registry behind L3 (gap: {})",
                    mirror_sync.nonce_gap
                ),
                details: serde_json::json!({
                    "l3_nonce": mirror_sync.l3_nonce,
                    "mirror_nonce": mirror_sync.mirror_nonce,
                    "gap": mirror_sync.nonce_gap,
                }),
            });
        }

        // Read vault metrics
        let vault_metrics = self.read_vault_metrics().await?;
        if vault_metrics.high_utilization {
            alerts.push(Alert {
                severity: Severity::Warning,
                category: AlertCategory::Vault,
                message: format!(
                    "Vault utilization is high ({}%)",
                    vault_metrics.utilization_pct
                ),
                details: serde_json::json!({
                    "utilization_pct": vault_metrics.utilization_pct,
                    "total_assets": vault_metrics.total_assets.to_string(),
                    "idle_assets": vault_metrics.idle_assets.to_string(),
                }),
            });
        }

        // Compute per-market asset stress from data-node service
        // Fetches current + 24h-ago prices, computes SERM stress per asset,
        // uses max stress across all assets as conservative market-wide stress.
        let global_stress = self.fetch_asset_stress().await;
        let mut asset_stress: HashMap<[u8; 32], f64> = HashMap::new();
        let nav_drops: HashMap<[u8; 32], f64> = HashMap::new();

        for market_id in &self.market_ids {
            asset_stress.insert(*market_id, global_stress);
        }
        let crisis_levels =
            compute_crisis_levels(&all_positions, &self.market_ids, &asset_stress, &nav_drops);

        // Generate alerts for elevated+ crisis levels
        for (market_hex, level) in &crisis_levels {
            match level {
                CrisisLevel::Emergency => {
                    alerts.push(Alert {
                        severity: Severity::Critical,
                        category: AlertCategory::Position,
                        message: format!("EMERGENCY crisis level for market {}", market_hex),
                        details: serde_json::json!({
                            "market_id": market_hex,
                            "crisis_level": "Emergency",
                        }),
                    });
                }
                CrisisLevel::Stress => {
                    alerts.push(Alert {
                        severity: Severity::Critical,
                        category: AlertCategory::Position,
                        message: format!("STRESS crisis level for market {}", market_hex),
                        details: serde_json::json!({
                            "market_id": market_hex,
                            "crisis_level": "Stress",
                        }),
                    });
                }
                CrisisLevel::Elevated => {
                    alerts.push(Alert {
                        severity: Severity::Warning,
                        category: AlertCategory::Position,
                        message: format!("ELEVATED crisis level for market {}", market_hex),
                        details: serde_json::json!({
                            "market_id": market_hex,
                            "crisis_level": "Elevated",
                        }),
                    });
                }
                CrisisLevel::Normal => {} // No alert for normal
            }
        }

        Ok(HealthReport {
            timestamp,
            positions: all_positions,
            oracles,
            mirror_sync,
            vault_metrics,
            alerts,
            crisis_levels,
        })
    }
}

// ============================================================================
// Crisis Level Detection (Phase 5A)
// ============================================================================

/// Per-market crisis assessment input
pub struct MarketCrisisInput {
    /// Average health factor across all positions in this market
    pub avg_health_factor: f64,
    /// Whether any position is liquidatable (HF < 1.0)
    pub has_liquidatable: bool,
    /// Asset stress score (0.0 = no stress, 5.0 = max)
    pub asset_stress: f64,
    /// NAV drop over last 24h as a fraction (0.15 = 15% drop)
    pub nav_drop_24h: f64,
}

/// Determine crisis level for a market based on position health and stress data
///
/// Levels per architecture doc:
/// - Normal: all HF > 1.3, no asset stress
/// - Elevated: avg HF < 1.3 OR any asset stress > 1
/// - Stress: avg HF < 1.15 OR any asset stress > 3
/// - Emergency: any liquidatable OR asset stress > 4 OR NAV drop > 15%
pub fn determine_crisis_level(input: &MarketCrisisInput) -> CrisisLevel {
    // Emergency triggers (check first — most severe)
    if input.has_liquidatable || input.asset_stress > 4.0 || input.nav_drop_24h > 0.15 {
        return CrisisLevel::Emergency;
    }

    // Stress triggers
    if input.avg_health_factor < 1.15 || input.asset_stress > 3.0 {
        return CrisisLevel::Stress;
    }

    // Elevated triggers
    if input.avg_health_factor < 1.3 || input.asset_stress > 1.0 {
        return CrisisLevel::Elevated;
    }

    CrisisLevel::Normal
}

/// Compute crisis levels for all markets from position health data
///
/// Returns map of market_id (hex) → CrisisLevel.
/// For markets with no positions, defaults to Normal.
/// Asset stress and NAV drop are optional inputs (default 0.0 if not available).
pub fn compute_crisis_levels(
    positions: &[PositionHealth],
    market_ids: &[[u8; 32]],
    asset_stress: &HashMap<[u8; 32], f64>,
    nav_drops: &HashMap<[u8; 32], f64>,
) -> HashMap<String, CrisisLevel> {
    let mut levels = HashMap::new();

    for market_id in market_ids {
        let market_positions: Vec<&PositionHealth> = positions
            .iter()
            .filter(|p| &p.market_id == market_id)
            .collect();

        let (avg_hf, has_liquidatable) = if market_positions.is_empty() {
            (f64::INFINITY, false)
        } else {
            let sum_hf: f64 = market_positions.iter().map(|p| p.health_factor).sum();
            let avg = sum_hf / market_positions.len() as f64;
            let liquidatable = market_positions
                .iter()
                .any(|p| p.status == HealthStatus::Liquidatable);
            (avg, liquidatable)
        };

        let stress = asset_stress.get(market_id).copied().unwrap_or(0.0);
        let nav_drop = nav_drops.get(market_id).copied().unwrap_or(0.0);

        let input = MarketCrisisInput {
            avg_health_factor: avg_hf,
            has_liquidatable,
            asset_stress: stress,
            nav_drop_24h: nav_drop,
        };

        let level = determine_crisis_level(&input);
        let key = format!("0x{}", hex::encode(market_id));
        levels.insert(key, level);
    }

    levels
}

// ============================================================================
// Helper Functions (Task 2.3)
// ============================================================================

/// Compute health factor for a position
///
/// Formula: healthFactor = (collateral * oraclePrice * LLTV) / debt
///
/// Where:
/// - collateral is in collateral token units (18 decimals for ITP)
/// - oraclePrice is in Morpho format (36 decimals, adjusted for loan/collateral decimal diff)
/// - LLTV is in 1e18 format (e.g., 0.77e18 = 77%)
/// - debt is in loan token units (6 decimals for USDC)
pub fn compute_health_factor(
    collateral: U256,
    debt: U256,
    lltv: U256,
    oracle_price: U256,
) -> f64 {
    if debt.is_zero() {
        return f64::INFINITY;
    }

    // For precision, compute in U256 then convert to f64
    // numerator = collateral * price * lltv
    // denominator = debt * 1e18 (to match lltv scaling)
    //
    // But since price is already scaled for loan/collateral decimals,
    // and we want HF in human-readable form:
    // HF = (collateral * price / 1e36) * (lltv / 1e18) / debt

    // Simplified for f64 computation:
    let collateral_f = collateral.as_u128() as f64;
    let debt_f = debt.as_u128() as f64;
    let lltv_f = lltv.as_u128() as f64 / 1e18;
    let price_f = oracle_price.as_u128() as f64;

    // Price is scaled: 36 + loanDecimals - collateralDecimals = 36 + 6 - 18 = 24
    // So price is in 1e24 format
    // collateral (1e18) * price (1e24) = 1e42
    // debt (1e6) needs to match, so: 1e42 / 1e6 = 1e36
    // Therefore: HF = collateral * price * lltv / (debt * 1e36)
    let hf = (collateral_f * price_f * lltv_f) / (debt_f * 1e36);

    hf
}

/// Classify health status based on health factor
pub fn classify_health_status(health_factor: f64, config: &AlertConfig) -> HealthStatus {
    if health_factor < 1.0 {
        HealthStatus::Liquidatable
    } else if health_factor < config.critical_health_factor {
        HealthStatus::Critical
    } else if health_factor < config.warning_health_factor {
        HealthStatus::Warning
    } else {
        HealthStatus::Healthy
    }
}

/// Write a health report to a JSON file
pub fn write_report_to_file(report: &HealthReport, path: &Path) -> Result<(), std::io::Error> {
    let json = serde_json::to_string_pretty(report)?;
    std::fs::write(path, json)
}

// ============================================================================
// Serde Helper for [u8; 32]
// ============================================================================

mod hex_bytes32 {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(bytes: &[u8; 32], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&format!("0x{}", hex::encode(bytes)))
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<[u8; 32], D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        let s = s.strip_prefix("0x").unwrap_or(&s);
        let bytes = hex::decode(s).map_err(serde::de::Error::custom)?;
        if bytes.len() != 32 {
            return Err(serde::de::Error::custom("expected 32 bytes"));
        }
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&bytes);
        Ok(arr)
    }
}

// ============================================================================
// Unit Tests (Task 8)
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // Health Factor Tests (Task 8.2-8.5)
    // ========================================================================

    #[test]
    fn test_compute_health_factor_healthy() {
        // collateral=1000e18, debt=500e6, lltv=0.77e18, price=100e24 (1 ITP = 100 USDC)
        // HF = (1000e18 * 100e24 * 0.77) / (500e6 * 1e36)
        // HF = (1000 * 100 * 0.77) / 500 = 77000 / 500 = 154
        let collateral = U256::from(1000u64) * U256::exp10(18);
        let debt = U256::from(500u64) * U256::exp10(6);
        let lltv = U256::from(77u64) * U256::exp10(16); // 0.77e18
        let price = U256::from(100u64) * U256::exp10(24);

        let hf = compute_health_factor(collateral, debt, lltv, price);
        assert!(hf > 1.2, "Expected HF > 1.2, got {}", hf);
    }

    #[test]
    fn test_compute_health_factor_warning() {
        // Adjust parameters for HF between 1.05 and 1.2
        // HF = (collateral * price * lltv) / (debt * 1e36)
        // Target HF ≈ 1.1
        // debt = (collateral * price * lltv) / (HF * 1e36)
        let collateral = U256::from(100u64) * U256::exp10(18);
        let lltv = U256::from(77u64) * U256::exp10(16); // 0.77e18
        let price = U256::from(100u64) * U256::exp10(24);
        // For HF = 1.1: debt = (100 * 100 * 0.77) / 1.1 = 7000 (not 700)
        let debt = U256::from(7000u64) * U256::exp10(6);

        let hf = compute_health_factor(collateral, debt, lltv, price);
        assert!(
            hf >= 1.05 && hf < 1.2,
            "Expected 1.05 <= HF < 1.2, got {}",
            hf
        );
    }

    #[test]
    fn test_compute_health_factor_critical() {
        // Target HF ≈ 1.02 (between 1.0 and 1.05)
        let collateral = U256::from(100u64) * U256::exp10(18);
        let lltv = U256::from(77u64) * U256::exp10(16);
        let price = U256::from(100u64) * U256::exp10(24);
        // For HF = 1.02: debt = (100 * 100 * 0.77) / 1.02 ≈ 7549
        let debt = U256::from(7549u64) * U256::exp10(6);

        let hf = compute_health_factor(collateral, debt, lltv, price);
        assert!(
            hf >= 1.0 && hf < 1.05,
            "Expected 1.0 <= HF < 1.05, got {}",
            hf
        );
    }

    #[test]
    fn test_compute_health_factor_liquidatable() {
        // Target HF < 1.0
        let collateral = U256::from(100u64) * U256::exp10(18);
        let lltv = U256::from(77u64) * U256::exp10(16);
        let price = U256::from(100u64) * U256::exp10(24);
        // For HF = 0.9: debt = (100 * 100 * 0.77) / 0.9 ≈ 8555
        let debt = U256::from(8555u64) * U256::exp10(6);

        let hf = compute_health_factor(collateral, debt, lltv, price);
        assert!(hf < 1.0, "Expected HF < 1.0, got {}", hf);
    }

    #[test]
    fn test_compute_health_factor_zero_debt() {
        let collateral = U256::from(1000u64) * U256::exp10(18);
        let debt = U256::zero();
        let lltv = U256::from(77u64) * U256::exp10(16);
        let price = U256::from(100u64) * U256::exp10(24);

        let hf = compute_health_factor(collateral, debt, lltv, price);
        assert!(hf.is_infinite(), "Expected infinite HF for zero debt");
    }

    // ========================================================================
    // Oracle Freshness Tests (Task 8.6-8.8)
    // ========================================================================

    #[test]
    fn test_oracle_freshness_not_stale() {
        // lastUpdated = now - 1 hour (3600 seconds)
        // Tier A cadence = 4 hours (14400 seconds)
        // age < cadence → not stale
        let age_secs = 3600u64;
        let configured_cadence = TIER_A_CADENCE_SECS;

        let is_stale = age_secs > configured_cadence;
        let is_frozen = age_secs > MAX_STALENESS_SECS;

        assert!(!is_stale, "Expected not stale");
        assert!(!is_frozen, "Expected not frozen");
    }

    #[test]
    fn test_oracle_freshness_stale() {
        // lastUpdated = now - 5 hours (18000 seconds)
        // Tier A cadence = 4 hours (14400 seconds)
        // age > cadence → stale
        let age_secs = 18000u64;
        let configured_cadence = TIER_A_CADENCE_SECS;

        let is_stale = age_secs > configured_cadence;
        let is_frozen = age_secs > MAX_STALENESS_SECS;

        assert!(is_stale, "Expected stale");
        assert!(!is_frozen, "Expected not frozen (< 24 hours)");
    }

    #[test]
    fn test_oracle_freshness_frozen() {
        // lastUpdated = now - 25 hours (90000 seconds)
        // MAX_STALENESS = 24 hours (86400 seconds)
        // age > MAX_STALENESS → frozen
        let age_secs = 90000u64;

        let is_frozen = age_secs > MAX_STALENESS_SECS;

        assert!(is_frozen, "Expected frozen (> 24 hours)");
    }

    // ========================================================================
    // Mirror Sync Tests (Task 8.9-8.10)
    // ========================================================================

    #[test]
    fn test_mirror_sync_in_sync() {
        let l3_nonce = 5u64;
        let mirror_nonce = 5u64;
        let nonce_gap = l3_nonce as i64 - mirror_nonce as i64;
        let is_synced = nonce_gap == 0;

        assert!(is_synced, "Expected synced");
        assert_eq!(nonce_gap, 0);
    }

    #[test]
    fn test_mirror_sync_behind() {
        let l3_nonce = 7u64;
        let mirror_nonce = 5u64;
        let nonce_gap = l3_nonce as i64 - mirror_nonce as i64;
        let is_synced = nonce_gap == 0;

        assert!(!is_synced, "Expected not synced");
        assert_eq!(nonce_gap, 2);
    }

    // ========================================================================
    // Vault Metrics Tests (Task 8.11-8.12)
    // ========================================================================

    #[test]
    fn test_vault_metrics_normal() {
        // 80% utilization should not be flagged
        let total_assets = U256::from(10000u64);
        let idle_assets = U256::from(2000u64);
        let utilized = total_assets.saturating_sub(idle_assets);
        let utilization_pct = ((utilized * U256::from(100)) / total_assets).as_u64() as u8;

        assert_eq!(utilization_pct, 80);
        assert!(
            utilization_pct <= DEFAULT_HIGH_UTILIZATION_PCT,
            "Expected normal utilization"
        );
    }

    #[test]
    fn test_vault_metrics_high_utilization() {
        // 92% utilization should be flagged
        let total_assets = U256::from(10000u64);
        let idle_assets = U256::from(800u64);
        let utilized = total_assets.saturating_sub(idle_assets);
        let utilization_pct = ((utilized * U256::from(100)) / total_assets).as_u64() as u8;

        assert_eq!(utilization_pct, 92);
        assert!(
            utilization_pct > DEFAULT_HIGH_UTILIZATION_PCT,
            "Expected high utilization"
        );
    }

    // ========================================================================
    // Alert Generation Tests (Task 8.13)
    // ========================================================================

    #[test]
    fn test_classify_health_status_healthy() {
        let config = AlertConfig::default();
        let status = classify_health_status(1.5, &config);
        assert_eq!(status, HealthStatus::Healthy);
    }

    #[test]
    fn test_classify_health_status_warning() {
        let config = AlertConfig::default();
        let status = classify_health_status(1.1, &config);
        assert_eq!(status, HealthStatus::Warning);
    }

    #[test]
    fn test_classify_health_status_critical() {
        let config = AlertConfig::default();
        let status = classify_health_status(1.02, &config);
        assert_eq!(status, HealthStatus::Critical);
    }

    #[test]
    fn test_classify_health_status_liquidatable() {
        let config = AlertConfig::default();
        let status = classify_health_status(0.95, &config);
        assert_eq!(status, HealthStatus::Liquidatable);
    }

    #[test]
    fn test_alert_config_default_thresholds() {
        let config = AlertConfig::default();
        assert_eq!(config.warning_health_factor, 1.2);
        assert_eq!(config.critical_health_factor, 1.05);
        assert_eq!(config.high_utilization_pct, 90);
    }

    // ========================================================================
    // Crisis Level Detection Tests (Phase 5A)
    // ========================================================================

    #[test]
    fn test_crisis_level_normal() {
        let input = MarketCrisisInput {
            avg_health_factor: 2.0,
            has_liquidatable: false,
            asset_stress: 0.0,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Normal);
    }

    #[test]
    fn test_crisis_level_elevated_low_avg_hf() {
        let input = MarketCrisisInput {
            avg_health_factor: 1.25,
            has_liquidatable: false,
            asset_stress: 0.0,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Elevated);
    }

    #[test]
    fn test_crisis_level_elevated_asset_stress() {
        let input = MarketCrisisInput {
            avg_health_factor: 2.0,
            has_liquidatable: false,
            asset_stress: 1.5,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Elevated);
    }

    #[test]
    fn test_crisis_level_stress_low_avg_hf() {
        let input = MarketCrisisInput {
            avg_health_factor: 1.1,
            has_liquidatable: false,
            asset_stress: 0.0,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Stress);
    }

    #[test]
    fn test_crisis_level_stress_high_asset_stress() {
        let input = MarketCrisisInput {
            avg_health_factor: 2.0,
            has_liquidatable: false,
            asset_stress: 3.5,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Stress);
    }

    #[test]
    fn test_crisis_level_emergency_liquidatable() {
        let input = MarketCrisisInput {
            avg_health_factor: 0.9,
            has_liquidatable: true,
            asset_stress: 0.0,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Emergency);
    }

    #[test]
    fn test_crisis_level_emergency_flash_crash() {
        let input = MarketCrisisInput {
            avg_health_factor: 2.0,
            has_liquidatable: false,
            asset_stress: 4.5,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Emergency);
    }

    #[test]
    fn test_crisis_level_emergency_nav_drop() {
        let input = MarketCrisisInput {
            avg_health_factor: 2.0,
            has_liquidatable: false,
            asset_stress: 0.0,
            nav_drop_24h: 0.20,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Emergency);
    }

    #[test]
    fn test_crisis_level_boundary_1_3() {
        // Exactly 1.3 is NOT elevated (avg HF < 1.3 triggers elevated)
        let input = MarketCrisisInput {
            avg_health_factor: 1.3,
            has_liquidatable: false,
            asset_stress: 0.0,
            nav_drop_24h: 0.0,
        };
        assert_eq!(determine_crisis_level(&input), CrisisLevel::Normal);
    }

    #[test]
    fn test_compute_crisis_levels_mixed() {
        let market_a = [0xAAu8; 32];
        let market_b = [0xBBu8; 32];

        let positions = vec![
            PositionHealth {
                borrower: Address::zero(),
                market_id: market_a,
                collateral: U256::from(100),
                borrow_shares: U256::from(50),
                debt_assets: U256::from(50),
                health_factor: 1.1, // Stress-level avg
                status: HealthStatus::Warning,
            },
            PositionHealth {
                borrower: Address::zero(),
                market_id: market_b,
                collateral: U256::from(200),
                borrow_shares: U256::from(30),
                debt_assets: U256::from(30),
                health_factor: 2.0, // Healthy
                status: HealthStatus::Healthy,
            },
        ];

        let stress = HashMap::new();
        let nav = HashMap::new();
        let levels =
            compute_crisis_levels(&positions, &[market_a, market_b], &stress, &nav);

        let key_a = format!("0x{}", hex::encode(market_a));
        let key_b = format!("0x{}", hex::encode(market_b));

        assert_eq!(levels[&key_a], CrisisLevel::Stress);
        assert_eq!(levels[&key_b], CrisisLevel::Normal);
    }

    #[test]
    fn test_compute_crisis_levels_no_positions() {
        let market = [0xCC; 32];
        let stress = HashMap::new();
        let nav = HashMap::new();
        let levels = compute_crisis_levels(&[], &[market], &stress, &nav);
        let key = format!("0x{}", hex::encode(market));
        assert_eq!(levels[&key], CrisisLevel::Normal);
    }

    #[test]
    fn test_alert_config_default_oracle_cadences() {
        let config = AlertConfig::default();
        assert_eq!(
            config.oracle_stale_secs.get(&RiskTier::A),
            Some(&TIER_A_CADENCE_SECS)
        );
        assert_eq!(
            config.oracle_stale_secs.get(&RiskTier::B),
            Some(&TIER_B_CADENCE_SECS)
        );
        assert_eq!(
            config.oracle_stale_secs.get(&RiskTier::C),
            Some(&TIER_C_CADENCE_SECS)
        );
        assert_eq!(
            config.oracle_stale_secs.get(&RiskTier::D),
            Some(&TIER_D_CADENCE_SECS)
        );
    }
}
