[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana = "4gyWezdYUBZ56EoXtGL5M1eD5NTcRr7DXCvNYUkZBy1V"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
