// Then-vs-Now baseline table for /dead-financial-market section 6.
// Fourteen BaselineRow entries. The page's spine.
//
// All [VERIFY] tags must be re-checked against the source URL before publication.
// See research file 06 in this directory for full context.

import type { BaselineRow } from './types'

export const THEN_VS_NOW: BaselineRow[] = [
  {
    slug: 'mev',
    property: 'MEV extracted from on-chain users per year',
    then: { year: 2015, value: '$0', note: 'Ethereum launched July 2015. Concept did not exist.' },
    now:  { year: 2024, value: '~$700M+/yr', note: 'Ethereum + L2s + Solana via Jito tips.' },
    knife: 'An extraction category invented from nothing in nine years.',
    sourceLabel: 'Flashbots Explore · EigenPhi · Helius MEV Report',
    sourceUrl: 'https://explore.flashbots.net/',
  },
  {
    slug: 'citadel-sec-revenue',
    property: 'Citadel Securities net trading revenue',
    then: { year: 2015, value: '~$1.7B' },
    now:  { year: 2024, value: '~$11–12B', note: 'Record year, follows record 2023 ($9.7B).' },
    knife: 'Six and a half times larger. One firm.',
    sourceLabel: 'FT · Bloomberg · bond prospectus',
    sourceUrl: 'https://www.ft.com/content/citadel-securities-9-7bn-record',
  },
  {
    slug: 'jane-street-revenue',
    property: 'Jane Street net trading revenue',
    then: { year: 2015, value: '~$1–2B (est)', note: 'Private until 2023; estimated from later disclosures.' },
    now:  { year: 2024, value: '~$20.5B', note: 'Annualized from H1 disclosure of $14.2B.' },
    knife: 'Roughly ten times larger. One firm.',
    sourceLabel: 'FT · Bloomberg · Moody\'s · S&P',
    sourceUrl: 'https://www.ft.com/content/jane-street-bond-prospectus',
  },
  {
    slug: 'pfof-total',
    property: 'PFOF paid by US retail brokers',
    then: { year: 2015, value: '~$0.7B' },
    now:  { year: 2024, value: '~$3.7B' },
    knife: 'Five times more paid for the right to read retail before the market does.',
    sourceLabel: 'SEC Rule 606 · Bloomberg Intelligence',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&type=606',
  },
  {
    slug: 'zerodte',
    property: '0DTE share of S&P 500 options volume',
    then: { year: 2015, value: '~5%' },
    now:  { year: 2024, value: '~50%' },
    knife: 'Half the S&P options market now expires before retail finishes lunch.',
    sourceLabel: 'CBOE Global Markets',
    sourceUrl: 'https://www.cboe.com/us/options/market_statistics/',
  },
  {
    slug: 'us-listings',
    property: 'Number of US-listed public companies',
    then: { year: 1996, value: '~8,090', note: 'The historical peak.' },
    now:  { year: 2024, value: '~4,300' },
    knife: 'Half the public companies are gone. The growth happens in private rounds retail cannot enter.',
    sourceLabel: 'Wilshire Associates · WSJ',
    sourceUrl: 'https://www.wilshire.com/',
  },
  {
    slug: 'latency',
    property: 'NY → Chicago latency, fastest commercial link',
    then: { year: 2015, value: '~8ms', note: 'Spread Networks fiber + first-gen microwave.' },
    now:  { year: 2024, value: '~6.5ms', note: 'Maxed microwave plus laser links.' },
    knife: 'A microsecond now costs more than a small house. Retail pays for none of it and receives none of it.',
    sourceLabel: 'McKay Brothers · Quincy Data · Anova',
    sourceUrl: 'https://www.mckay-brothers.com/',
  },
  {
    slug: 'off-exchange',
    property: 'US equity volume executed off-exchange',
    then: { year: 2015, value: '~36%' },
    now:  { year: 2024, value: '~50%+' },
    knife: 'Half the tape is no longer the tape.',
    sourceLabel: 'Cboe US Equities Market Share',
    sourceUrl: 'https://www.cboe.com/us/equities/market_statistics/',
  },
  {
    slug: 'pod-shops',
    property: 'Top-8 quant pod-shop combined AUM',
    then: { year: 2015, value: '~$150B' },
    now:  { year: 2024, value: '~$350B+', note: 'Levered footprint over $2T.' },
    knife: 'Eight funds. One coordinated alpha-extraction engine.',
    sourceLabel: 'HFR Industry Reports · Bloomberg',
    sourceUrl: 'https://www.hfr.com/research',
  },
  {
    slug: 'algo-share',
    property: 'Algorithmic share of US equity volume',
    then: { year: 2015, value: '~73%' },
    now:  { year: 2024, value: '~85%' },
    knife: 'Of every hundred trades, fifteen are humans. The rest is the machine.',
    sourceLabel: 'Tabb Group · Greenwich Associates',
    sourceUrl: 'https://www.greenwich.com/equities/u-s-equity-market-structure',
  },
  {
    slug: 'fx-algo',
    property: 'Algo / electronic share of global FX',
    then: { year: 2016, value: '~62%' },
    now:  { year: 2022, value: '~74%', note: 'BIS Triennial; 2025 survey due.' },
    knife: 'Currency markets too. The same migration to the same firms.',
    sourceLabel: 'BIS Triennial Central Bank Survey',
    sourceUrl: 'https://www.bis.org/statistics/rpfx22.htm',
  },
  {
    slug: 'treasury-ptf',
    property: 'PTF share of US Treasury secondary trading',
    then: { year: 2014, value: '~30%' },
    now:  { year: 2022, value: '~60%+' },
    knife: 'The deepest market in the world now hosted by firms that can withdraw it in microseconds.',
    sourceLabel: 'US Treasury · OFR · Federal Reserve',
    sourceUrl: 'https://home.treasury.gov/system/files/276/Joint_Staff_Report_Treasury_10-15-2015.pdf',
  },
  {
    slug: 'crypto-liquidations',
    property: 'Annual crypto perp retail liquidations',
    then: { year: 2017, value: '~$5B' },
    now:  { year: 2024, value: '~$200B+' },
    knife: 'Two hundred billion dollars of margin closed against the trader who posted it. One year.',
    sourceLabel: 'Coinglass',
    sourceUrl: 'https://www.coinglass.com/LiquidationData',
  },
  {
    slug: 'options-volume',
    property: 'US options contracts traded per year',
    then: { year: 2015, value: '~4.1B contracts' },
    now:  { year: 2024, value: '~12B+ contracts', note: 'OCC record; mostly 0DTE-driven.' },
    knife: 'Triple the options. Same retail. Worse outcomes.',
    sourceLabel: 'OCC · CBOE',
    sourceUrl: 'https://www.theocc.com/Market-Data/Market-Data-Reports/Volume-and-Open-Interest',
  },
]
