// Compounding-clock data for /dead-financial-market section 3.
// Twelve DeltaStat rows. Each one independently devastating.
//
// All [VERIFY] tags must be re-checked against the source URL before publication.
// See companion research files 01–06 in this directory for full context per row.

import type { DeltaStat } from './types'

export const COMPOUNDING_CLOCK: DeltaStat[] = [
  {
    slug: 'hft-revenue',
    metric: 'HFT firm aggregate revenue',
    from: { year: 2015, value: '~$4B' },     // Citadel Sec + Virtu + Jane Street + HRT, low estimate
    to:   { year: 2024, value: '~$45B+' },   // same firms, latest disclosures
    change: '+ 1000%',
    unit: 'USD revenue',
    knife: 'Four firms. Ten years. The pile of money they extract from the rest of the market grew tenfold.',
    sourceLabel: 'FT · Bloomberg · SEC 10-K (Virtu)',
    sourceUrl: 'https://www.ft.com/content/citadel-securities-9-7bn-record',
  },
  {
    slug: 'mev-extracted',
    metric: 'MEV extracted per year (Ethereum + L2s)',
    from: { year: 2015, value: '$0' },
    to:   { year: 2024, value: '~$700M+/yr' },
    change: '+ ∞',
    unit: 'USD/year extracted from on-chain users',
    knife: 'A category that did not exist now drains the equivalent of a mid-cap company every year.',
    sourceLabel: 'Flashbots · EigenPhi',
    sourceUrl: 'https://explore.flashbots.net/',
  },
  {
    slug: 'pfof-total',
    metric: 'PFOF received by US retail brokers',
    from: { year: 2015, value: '~$0.7B' },
    to:   { year: 2024, value: '~$3.7B' },
    change: '+ 430%',
    unit: 'USD/year PFOF paid to brokers',
    knife: 'Retail brokers were paid five times more to hand over their customers in 2024 than in 2015.',
    sourceLabel: 'SEC Rule 606 · Bloomberg Intelligence',
    sourceUrl: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&type=606',
  },
  {
    slug: 'off-exchange-share',
    metric: 'US equity volume executed off-exchange',
    from: { year: 2015, value: '36%' },
    to:   { year: 2024, value: '50%+' },
    change: '+ 14pp',
    unit: '% of consolidated tape volume',
    knife: 'Half the market is no longer on the public market.',
    sourceLabel: 'Cboe US Equities Market Share',
    sourceUrl: 'https://www.cboe.com/us/equities/market_statistics/',
  },
  {
    slug: 'algo-share',
    metric: 'Algo-initiated US equity volume',
    from: { year: 2015, value: '73%' },
    to:   { year: 2024, value: '~85%' },
    change: '+ 12pp',
    unit: '% of volume initiated by algorithms',
    knife: 'Of every hundred trades, fifteen are humans. The rest is the machine.',
    sourceLabel: 'Tabb Group · Greenwich Associates',
    sourceUrl: 'https://www.greenwich.com/equities/u-s-equity-market-structure',
  },
  {
    slug: 'pod-shop-aum',
    metric: 'Top-8 quant pod-shop combined AUM',
    from: { year: 2015, value: '~$150B' },
    to:   { year: 2024, value: '~$350B+' },
    change: '+ 133%',
    unit: 'USD AUM (leverage ~5–8×)',
    knife: 'Eight funds. The footprint they trade with rounds to two trillion dollars.',
    sourceLabel: 'HFR Industry Reports · Bloomberg',
    sourceUrl: 'https://www.hfr.com/research',
  },
  {
    slug: 'zerodte-share',
    metric: '0DTE share of S&P 500 options volume',
    from: { year: 2015, value: '~5%' },
    to:   { year: 2024, value: '~50%' },
    change: '+ 45pp',
    unit: '% of SPX options volume',
    knife: 'Options on the S&P 500 are now mostly lottery tickets that expire by the closing bell.',
    sourceLabel: 'CBOE Global Markets',
    sourceUrl: 'https://www.cboe.com/us/options/market_statistics/',
  },
  {
    slug: 'latency-ny-chicago',
    metric: 'NY → Chicago round-trip latency, fastest commercial link',
    from: { year: 2015, value: '~8ms' },
    to:   { year: 2024, value: '~6.5ms' },
    change: '− 19%',
    unit: 'millisecond round-trip',
    knife: 'Every microsecond cut costs millions to engineer. Retail does not get any of them.',
    sourceLabel: 'McKay Brothers · Quincy Data',
    sourceUrl: 'https://www.mckay-brothers.com/',
  },
  {
    slug: 'treasury-ptf',
    metric: 'PTF share of US Treasury secondary trading',
    from: { year: 2014, value: '~30%' },
    to:   { year: 2022, value: '~60%+' },
    change: '+ 30pp',
    unit: '% of secondary on-the-run volume',
    knife: 'The deepest market in the world is now run by people who can withdraw it in a microsecond.',
    sourceLabel: 'US Treasury · OFR · Federal Reserve',
    sourceUrl: 'https://home.treasury.gov/system/files/276/Joint_Staff_Report_Treasury_10-15-2015.pdf',
  },
  {
    slug: 'phd-comp',
    metric: 'New-grad quant PhD median total compensation',
    from: { year: 2015, value: '~$350K' },
    to:   { year: 2024, value: '~$1M+' },
    change: '+ 186%',
    unit: 'USD Y1 total comp',
    knife: 'The arms race is a hiring race. The PhD who used to teach is now extracting.',
    sourceLabel: 'WSJ · eFinancialCareers · Wall Street Oasis',
    sourceUrl: 'https://www.wsj.com/finance/investing/quants-bonus-pay-jane-street',
  },
  {
    slug: 'us-listings',
    metric: 'Number of US public-listed companies',
    from: { year: 1996, value: '~8,090' },
    to:   { year: 2024, value: '~4,300' },
    change: '− 47%',
    unit: 'count of US-listed equities',
    knife: 'Half the companies vanished. The growth that remains happens before retail can buy.',
    sourceLabel: 'Wilshire · WSJ',
    sourceUrl: 'https://www.wilshire.com/',
  },
  {
    slug: 'crypto-liquidations',
    metric: 'Annual crypto perp retail liquidations',
    from: { year: 2017, value: '~$5B' },     // ~zero in 2015; pick 2017 for the floor as MEV did
    to:   { year: 2024, value: '~$200B' },
    change: '+ 4000%',
    unit: 'USD liquidated per year',
    knife: 'Two hundred billion dollars of margin closed against the trader who posted it.',
    sourceLabel: 'Coinglass',
    sourceUrl: 'https://www.coinglass.com/LiquidationData',
  },
]
