import type { JargonEntry } from './types'

// The jargon dictionary.
// Six entries. Each is a direct quote from a public filing. The
// industry has a vocabulary for the user it cannot get back. The
// vocabulary is the confession.

export const JARGON: JargonEntry[] = [
  {
    slug: 'churned-resurrected',
    company: 'Robinhood',
    term: 'Churned. Resurrected.',
    quote:
      '"An account is considered \'Churned\' if it was ever a New Funded Account and its balance drops to or below zero for at least 45 consecutive calendar days. An account is considered \'Resurrected\' if it was a Churned Account as of the end of the immediately preceding period and its balance rises above zero."',
    knife:
      'The Net Cumulative Funded Accounts formula is New Funded − Churned + Resurrected. The company defines its own audience as a subtraction.',
    sourceLabel: 'HOOD S-1 (2021), definitional notes',
    sourceUrl:
      'https://www.sec.gov/Archives/edgar/data/1783879/000162828021013318/robinhoods-1.htm',
  },
  {
    slug: 'discontinued',
    company: 'Coinbase',
    term: 'Verified Users (discontinued, 2023)',
    quote:
      '"Verified users may overstate the number of unique customers as one customer may register for and use multiple accounts."',
    knife:
      'The company stopped publishing the metric in 2023 when the active-to-verified ratio fell below 9%. They called the metric inaccurate. The metric was accurate. The truth was inconvenient.',
    sourceLabel: 'COIN FY2022 10-K',
    sourceUrl:
      'https://www.sec.gov/Archives/edgar/data/0001679788/000167978823000031/coin-20221231.htm',
  },
  {
    slug: 'amp-erosion',
    company: 'Flutter (FanDuel)',
    term: 'Erosion of AMP base',
    quote:
      '"There is no guarantee that the company will not experience an erosion of its AMP base or engagement levels among customers in the future."',
    knife:
      'Average Monthly Players grew from 12.3M to 15.9M in two years. The risk factor still warns about erosion. Growing is not the same as keeping.',
    sourceLabel: 'FLUT 10-K FY2023',
    sourceUrl:
      'https://www.sec.gov/Archives/edgar/data/0001635327/000119312524076966/d766413d10k.htm',
  },
  {
    slug: 'regulator-forced',
    company: 'IG Group',
    term: 'Regulation requiring the closure of inactive accounts',
    quote:
      '"A decline in funded accounts in Europe reflects the implementation of regulation requiring the closure of inactive accounts."',
    knife:
      'The regulator forced IG to close accounts the firm itself maintained. The dormant accounts were a comfort. The company could not pull the trigger. The regulator did.',
    sourceLabel: 'IG Group Annual Report 2025',
    sourceUrl:
      'https://www.iggroup.com/~/media/Files/I/IG-Group/documents/investors/financial-results/results-reports-and-presentations/2025/annual-report-2025.pdf',
  },
  {
    slug: 'forfeiture',
    company: 'Caesars',
    term: 'Forfeiture',
    quote:
      '"A member\'s Reward Credit balance is forfeited if the member does not earn at least one Reward Credit during a continuous six-month period."',
    knife:
      'The casino has codified the moment the customer is officially gone. After six months, the balance is taken back. The accounting word for the user who walked away is forfeiture.',
    sourceLabel: 'CZR 10-K FY2024',
    sourceUrl:
      'https://www.sec.gov/Archives/edgar/data/0001590895/000159089525000068/czr-20241231.htm',
  },
  {
    slug: 'vintage-concentration',
    company: 'Plus500',
    term: 'Vintage concentration',
    quote:
      '"Approximately 50% of OTC revenue in 2025 was generated by customers trading with the Group for more than five years."',
    knife:
      'Said as a strength: our oldest cohorts are loyal. Read again: half the revenue depends on a generation acquired before the catastrophe chain began. The newer ones do not stay.',
    sourceLabel: 'Plus500 FY2025 Preliminary Results',
    sourceUrl:
      'https://cdn.plus500.com/Media/Investors/Reports/Plus500_Preliminary_Results_FY2025.pdf',
  },
  {
    slug: 'penn-mau-consistent',
    company: 'Penn Entertainment',
    term: '"Pretty consistent."',
    quote:
      '"MAU declines have been pretty consistent. It\'s not as though these are further accelerating in the wrong direction. It\'s been very stable on a year-over-year basis from a post-rebrand perspective."',
    knife:
      'Jay Snowden, CEO, Q1 2026 earnings call. A chief executive calling a structural decline "consistent" as if that were comfort. The cohort empties at a measurable rate. The rate is the news.',
    sourceLabel: 'PENN Q1 2026 earnings transcript',
    sourceUrl:
      'https://www.investing.com/news/transcripts/earnings-call-transcript-penn-entertainment-q1-2026-beats-eps-forecast-stock-surges-93CH-4660072',
  },
  {
    slug: 'etoro-vintage-roi',
    company: 'eToro',
    term: '1.8× vs 5.6×',
    quote:
      '"Our 2024 cohort has already achieved a 1.8x return on investment, while our 2020 cohort has delivered 5.6x return on investment."',
    knife:
      'Meron Shani, CFO, Q4 2025. Vintage as destiny. A 2020 customer is worth three times a 2024 customer, and management published the multiple. The newer arrivals are worth less; the company knows; they say so.',
    sourceLabel: 'ETOR Q4 2025 earnings transcript',
    sourceUrl:
      'https://www.fool.com/earnings/call-transcripts/2026/02/17/etoro-etor-q4-2025-earnings-call-transcript/',
  },
  {
    slug: 'ig-less-value',
    company: 'IG Group',
    term: 'Less value to us',
    quote:
      '"Sometimes, we do trigger customers that are less value to us. So sometimes we do some marketing stuff that is quite effective, but the customer value is not what we would hope."',
    knife:
      'Breon Corcoran, CEO, FY2025 results. A CEO publicly confessing that growth marketing produces a known fraction of unmonetizable users. The funnel surfaces them; the model scores them; the relationship ends before it begins.',
    sourceLabel: 'IGG FY2025 results presentation',
    sourceUrl:
      'https://www.iggroup.com/~/media/Files/I/IG-Group/documents/investors/financial-results/results-reports-and-presentations/2026/transcript-ig-group-2025-results-presentation.pdf',
  },
  {
    slug: 'flutter-smaller-base',
    company: 'Flutter (FanDuel)',
    term: 'Smaller player base',
    quote:
      '"Overall sportsbook performance was adversely impacted by NFL trends observed in Q4, with persistently high gross revenue margins negatively affecting customer activity, leaving us with a smaller player base as we entered 2026."',
    knife:
      'Peter Jackson, CEO, Q1 2026. The world\'s largest sportsbook attributes player-base shrinkage to a single quarter where customers won less. Customers got hurt. Customers left. The bleed continues.',
    sourceLabel: 'FLUT Q1 2026 earnings transcript',
    sourceUrl:
      'https://www.fool.com/earnings/call-transcripts/2026/05/06/flutter-flut-q1-2026-earnings-transcript/',
  },
]
