// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/deploy-all-tokens.py — DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../src/mocks/MockERC20.sol";

/// @title DeployAllTokens - Deploy 621 Bitget tokens + fund vault
contract DeployAllTokens is Script {
    uint256 constant N = 621;
    uint256 constant FUND = 1_000_000 * 1e18;

    uint256 private _tokenSaltCounter;

    function _deployToken(string memory name, string memory symbol, uint8 decimals) internal returns (address) {
        bytes32 salt = keccak256(abi.encode("INDEX_TOKEN", block.chainid, symbol, ++_tokenSaltCounter));
        return address(new MockERC20{salt: salt}(name, symbol, decimals));
    }

    function run() external {
        uint256 pk = vm.envOr("PRIVATE_KEY", uint256(0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d));
        address bv = vm.envAddress("MOCK_BITGET_VAULT");

        address[] memory t = new address[](N);

        vm.startBroadcast(pk);
        _deployBatch0(t);
        _deployBatch1(t);
        _deployBatch2(t);
        _deployBatch3(t);
        _deployBatch4(t);
        _deployBatch5(t);
        _deployBatch6(t);
        _deployBatch7(t);
        _deployBatch8(t);
        _deployBatch9(t);
        _deployBatch10(t);
        _deployBatch11(t);
        _deployBatch12(t);
        _deployBatch13(t);
        _deployBatch14(t);
        _deployBatch15(t);
        _deployBatch16(t);
        _deployBatch17(t);
        _deployBatch18(t);
        _deployBatch19(t);
        _deployBatch20(t);
        _deployBatch21(t);
        _deployBatch22(t);
        _deployBatch23(t);
        _deployBatch24(t);
        // Fund vault with 1M of each token
        for (uint256 i = 0; i < N; i++) MockERC20(t[i]).mint(bv, FUND);
        vm.stopBroadcast();

        _export(t);
        console.log("Done: 621 tokens deployed, vault funded");
    }

    function _deployBatch0(address[] memory t) internal {
        t[0] = _deployToken("Mock 0G", "0G", 18);
        t[1] = _deployToken("Mock 1INCH", "1INCH", 18);
        t[2] = _deployToken("Mock 2Z", "2Z", 18);
        t[3] = _deployToken("Mock A47", "A47", 18);
        t[4] = _deployToken("Mock A8", "A8", 18);
        t[5] = _deployToken("Mock AAVE", "AAVE", 18);
        t[6] = _deployToken("Mock AB", "AB", 18);
        t[7] = _deployToken("Mock ACE", "ACE", 18);
        t[8] = _deployToken("Mock ACH", "ACH", 18);
        t[9] = _deployToken("Mock ACM", "ACM", 18);
        t[10] = _deployToken("Mock ACT", "ACT", 18);
        t[11] = _deployToken("Mock ACX", "ACX", 18);
        t[12] = _deployToken("Mock ADA", "ADA", 18);
        t[13] = _deployToken("Mock AERGO", "AERGO", 18);
        t[14] = _deployToken("Mock AERO", "AERO", 18);
        t[15] = _deployToken("Mock AEVO", "AEVO", 18);
        t[16] = _deployToken("Mock AFC", "AFC", 18);
        t[17] = _deployToken("Mock AGLD", "AGLD", 18);
        t[18] = _deployToken("Mock AIA", "AIA", 18);
        t[19] = _deployToken("Mock AIAV", "AIAV", 18);
        t[20] = _deployToken("Mock AIN", "AIN", 18);
        t[21] = _deployToken("Mock AIO", "AIO", 18);
        t[22] = _deployToken("Mock AITECH", "AITECH", 18);
        t[23] = _deployToken("Mock AI", "AI", 18);
        t[24] = _deployToken("Mock AIXBT", "AIXBT", 18);
    }

    function _deployBatch1(address[] memory t) internal {
        t[25] = _deployToken("Mock ALCH", "ALCH", 18);
        t[26] = _deployToken("Mock ALGO", "ALGO", 18);
        t[27] = _deployToken("Mock ALICE", "ALICE", 18);
        t[28] = _deployToken("Mock ALLO", "ALLO", 18);
        t[29] = _deployToken("Mock ALMANAK", "ALMANAK", 18);
        t[30] = _deployToken("Mock ALPH", "ALPH", 18);
        t[31] = _deployToken("Mock ALPINE", "ALPINE", 18);
        t[32] = _deployToken("Mock ALT", "ALT", 18);
        t[33] = _deployToken("Mock AL", "AL", 18);
        t[34] = _deployToken("Mock AMP", "AMP", 18);
        t[35] = _deployToken("Mock ANIME", "ANIME", 18);
        t[36] = _deployToken("Mock ANKR", "ANKR", 18);
        t[37] = _deployToken("Mock APE", "APE", 18);
        t[38] = _deployToken("Mock API3", "API3", 18);
        t[39] = _deployToken("Mock APR", "APR", 18);
        t[40] = _deployToken("Mock APT", "APT", 18);
        t[41] = _deployToken("Mock AQT", "AQT", 18);
        t[42] = _deployToken("Mock ARB", "ARB", 18);
        t[43] = _deployToken("Mock ARG", "ARG", 18);
        t[44] = _deployToken("Mock ARIAIP", "ARIAIP", 18);
        t[45] = _deployToken("Mock ARIA", "ARIA", 18);
        t[46] = _deployToken("Mock ARKM", "ARKM", 18);
        t[47] = _deployToken("Mock ARK", "ARK", 18);
        t[48] = _deployToken("Mock ARPA", "ARPA", 18);
        t[49] = _deployToken("Mock ARTX", "ARTX", 18);
    }

    function _deployBatch2(address[] memory t) internal {
        t[50] = _deployToken("Mock AR", "AR", 18);
        t[51] = _deployToken("Mock ASR", "ASR", 18);
        t[52] = _deployToken("Mock ASTER", "ASTER", 18);
        t[53] = _deployToken("Mock ASTR", "ASTR", 18);
        t[54] = _deployToken("Mock ATH", "ATH", 18);
        t[55] = _deployToken("Mock ATM", "ATM", 18);
        t[56] = _deployToken("Mock ATOM", "ATOM", 18);
        t[57] = _deployToken("Mock AUCTION", "AUCTION", 18);
        t[58] = _deployToken("Mock AUDIO", "AUDIO", 18);
        t[59] = _deployToken("Mock A", "A", 18);
        t[60] = _deployToken("Mock AVA", "AVA", 18);
        t[61] = _deployToken("Mock AVAX", "AVAX", 18);
        t[62] = _deployToken("Mock AVNT", "AVNT", 18);
        t[63] = _deployToken("Mock AWE", "AWE", 18);
        t[64] = _deployToken("Mock AXL", "AXL", 18);
        t[65] = _deployToken("Mock AXS", "AXS", 18);
        t[66] = _deployToken("Mock B2", "B2", 18);
        t[67] = _deployToken("Mock BABYDOGE", "BABYDOGE", 18);
        t[68] = _deployToken("Mock BABY", "BABY", 18);
        t[69] = _deployToken("Mock BANANAS31", "BANANAS31", 18);
        t[70] = _deployToken("Mock BANANA", "BANANA", 18);
        t[71] = _deployToken("Mock BAND", "BAND", 18);
        t[72] = _deployToken("Mock BANK", "BANK", 18);
        t[73] = _deployToken("Mock BAN", "BAN", 18);
        t[74] = _deployToken("Mock BARD", "BARD", 18);
    }

    function _deployBatch3(address[] memory t) internal {
        t[75] = _deployToken("Mock BAR", "BAR", 18);
        t[76] = _deployToken("Mock BAT", "BAT", 18);
        t[77] = _deployToken("Mock BAY", "BAY", 18);
        t[78] = _deployToken("Mock BB", "BB", 18);
        t[79] = _deployToken("Mock BCH", "BCH", 18);
        t[80] = _deployToken("Mock BDXN", "BDXN", 18);
        t[81] = _deployToken("Mock BEAM", "BEAM", 18);
        t[82] = _deployToken("Mock BERA", "BERA", 18);
        t[83] = _deployToken("Mock BGB", "BGB", 18);
        t[84] = _deployToken("Mock BGSC", "BGSC", 18);
        t[85] = _deployToken("Mock BGSOL", "BGSOL", 18);
        t[86] = _deployToken("Mock BICO", "BICO", 18);
        t[87] = _deployToken("Mock BIGTIME", "BIGTIME", 18);
        t[88] = _deployToken("Mock BIO", "BIO", 18);
        t[89] = _deployToken("Mock BIRB", "BIRB", 18);
        t[90] = _deployToken("Mock BLAST", "BLAST", 18);
        t[91] = _deployToken("Mock BLESS", "BLESS", 18);
        t[92] = _deployToken("Mock BLUE", "BLUE", 18);
        t[93] = _deployToken("Mock BLUM", "BLUM", 18);
        t[94] = _deployToken("Mock BLUR", "BLUR", 18);
        t[95] = _deployToken("Mock BMT", "BMT", 18);
        t[96] = _deployToken("Mock BNB", "BNB", 18);
        t[97] = _deployToken("Mock BNT", "BNT", 18);
        t[98] = _deployToken("Mock BOME", "BOME", 18);
        t[99] = _deployToken("Mock BONK", "BONK", 18);
    }

    function _deployBatch4(address[] memory t) internal {
        t[100] = _deployToken("Mock BOS", "BOS", 18);
        t[101] = _deployToken("Mock BRETT", "BRETT", 18);
        t[102] = _deployToken("Mock BREV", "BREV", 18);
        t[103] = _deployToken("Mock BROCCOLI", "BROCCOLI", 18);
        t[104] = _deployToken("Mock BR", "BR", 18);
        t[105] = _deployToken("Mock BSB", "BSB", 18);
        t[106] = _deployToken("Mock BSU", "BSU", 18);
        t[107] = _deployToken("Mock BSV", "BSV", 18);
        t[108] = _deployToken("Mock BTC", "BTC", 18);
        t[109] = _deployToken("Mock BTR", "BTR", 18);
        t[110] = _deployToken("Mock BTT", "BTT", 18);
        t[111] = _deployToken("Mock BTW", "BTW", 18);
        t[112] = _deployToken("Mock B", "B", 18);
        t[113] = _deployToken("Mock BYTE", "BYTE", 18);
        t[114] = _deployToken("Mock C98", "C98", 18);
        t[115] = _deployToken("Mock CAKE", "CAKE", 18);
        t[116] = _deployToken("Mock CAMP", "CAMP", 18);
        t[117] = _deployToken("Mock CARV", "CARV", 18);
        t[118] = _deployToken("Mock CATI", "CATI", 18);
        t[119] = _deployToken("Mock CBK", "CBK", 18);
        t[120] = _deployToken("Mock CELO", "CELO", 18);
        t[121] = _deployToken("Mock CELR", "CELR", 18);
        t[122] = _deployToken("Mock CESS", "CESS", 18);
        t[123] = _deployToken("Mock CETUS", "CETUS", 18);
        t[124] = _deployToken("Mock CFX", "CFX", 18);
    }

    function _deployBatch5(address[] memory t) internal {
        t[125] = _deployToken("Mock CGN", "CGN", 18);
        t[126] = _deployToken("Mock CGPT", "CGPT", 18);
        t[127] = _deployToken("Mock CHEEMS", "CHEEMS", 18);
        t[128] = _deployToken("Mock CHILLGUY", "CHILLGUY", 18);
        t[129] = _deployToken("Mock CHR", "CHR", 18);
        t[130] = _deployToken("Mock CHZ", "CHZ", 18);
        t[131] = _deployToken("Mock CKB", "CKB", 18);
        t[132] = _deployToken("Mock CLANKER", "CLANKER", 18);
        t[133] = _deployToken("Mock COAI", "COAI", 18);
        t[134] = _deployToken("Mock COLLECT", "COLLECT", 18);
        t[135] = _deployToken("Mock COMMON", "COMMON", 18);
        t[136] = _deployToken("Mock COMP", "COMP", 18);
        t[137] = _deployToken("Mock COOKIE", "COOKIE", 18);
        t[138] = _deployToken("Mock CORE", "CORE", 18);
        t[139] = _deployToken("Mock COTI", "COTI", 18);
        t[140] = _deployToken("Mock COW", "COW", 18);
        t[141] = _deployToken("Mock CPOOL", "CPOOL", 18);
        t[142] = _deployToken("Mock CREO", "CREO", 18);
        t[143] = _deployToken("Mock CROSS", "CROSS", 18);
        t[144] = _deployToken("Mock CRO", "CRO", 18);
        t[145] = _deployToken("Mock CRV", "CRV", 18);
        t[146] = _deployToken("Mock CSPR", "CSPR", 18);
        t[147] = _deployToken("Mock CTC", "CTC", 18);
        t[148] = _deployToken("Mock CTSI", "CTSI", 18);
        t[149] = _deployToken("Mock CUDIS", "CUDIS", 18);
    }

    function _deployBatch6(address[] memory t) internal {
        t[150] = _deployToken("Mock C", "C", 18);
        t[151] = _deployToken("Mock CVC", "CVC", 18);
        t[152] = _deployToken("Mock CVX", "CVX", 18);
        t[153] = _deployToken("Mock CYBER", "CYBER", 18);
        t[154] = _deployToken("Mock CYS", "CYS", 18);
        t[155] = _deployToken("Mock DAI", "DAI", 18);
        t[156] = _deployToken("Mock DBR", "DBR", 18);
        t[157] = _deployToken("Mock DEEP", "DEEP", 18);
        t[158] = _deployToken("Mock DEGEN", "DEGEN", 18);
        t[159] = _deployToken("Mock DENT", "DENT", 18);
        t[160] = _deployToken("Mock DMC", "DMC", 18);
        t[161] = _deployToken("Mock DN", "DN", 18);
        t[162] = _deployToken("Mock DODO", "DODO", 18);
        t[163] = _deployToken("Mock DOGE", "DOGE", 18);
        t[164] = _deployToken("Mock DOGS", "DOGS", 18);
        t[165] = _deployToken("Mock DOG", "DOG", 18);
        t[166] = _deployToken("Mock DOOD", "DOOD", 18);
        t[167] = _deployToken("Mock DOT", "DOT", 18);
        t[168] = _deployToken("Mock DRIFT", "DRIFT", 18);
        t[169] = _deployToken("Mock DTEC", "DTEC", 18);
        t[170] = _deployToken("Mock DUCK", "DUCK", 18);
        t[171] = _deployToken("Mock D", "D", 18);
        t[172] = _deployToken("Mock DUSK", "DUSK", 18);
        t[173] = _deployToken("Mock DYDX", "DYDX", 18);
        t[174] = _deployToken("Mock DYM", "DYM", 18);
    }

    function _deployBatch7(address[] memory t) internal {
        t[175] = _deployToken("Mock EDEN", "EDEN", 18);
        t[176] = _deployToken("Mock EGL1", "EGL1", 18);
        t[177] = _deployToken("Mock EGLD", "EGLD", 18);
        t[178] = _deployToken("Mock EIGEN", "EIGEN", 18);
        t[179] = _deployToken("Mock ELA", "ELA", 18);
        t[180] = _deployToken("Mock ELIZAOS", "ELIZAOS", 18);
        t[181] = _deployToken("Mock ENA", "ENA", 18);
        t[182] = _deployToken("Mock ENJ", "ENJ", 18);
        t[183] = _deployToken("Mock ENSO", "ENSO", 18);
        t[184] = _deployToken("Mock ENS", "ENS", 18);
        t[185] = _deployToken("Mock EPT", "EPT", 18);
        t[186] = _deployToken("Mock ERA", "ERA", 18);
        t[187] = _deployToken("Mock ESIM", "ESIM", 18);
        t[188] = _deployToken("Mock ESPORTS", "ESPORTS", 18);
        t[189] = _deployToken("Mock ES", "ES", 18);
        t[190] = _deployToken("Mock ETC", "ETC", 18);
        t[191] = _deployToken("Mock ETHFI", "ETHFI", 18);
        t[192] = _deployToken("Mock ETH", "ETH", 18);
        t[193] = _deployToken("Mock ETHW", "ETHW", 18);
        t[194] = _deployToken("Mock FARTCOIN", "FARTCOIN", 18);
        t[195] = _deployToken("Mock FET", "FET", 18);
        t[196] = _deployToken("Mock FF", "FF", 18);
        t[197] = _deployToken("Mock FHE", "FHE", 18);
        t[198] = _deployToken("Mock FIDA", "FIDA", 18);
        t[199] = _deployToken("Mock FIL", "FIL", 18);
    }

    function _deployBatch8(address[] memory t) internal {
        t[200] = _deployToken("Mock FLK", "FLK", 18);
        t[201] = _deployToken("Mock FLOCK", "FLOCK", 18);
        t[202] = _deployToken("Mock FLOKI", "FLOKI", 18);
        t[203] = _deployToken("Mock FLOW", "FLOW", 18);
        t[204] = _deployToken("Mock FLUX", "FLUX", 18);
        t[205] = _deployToken("Mock FOGO", "FOGO", 18);
        t[206] = _deployToken("Mock FORM", "FORM", 18);
        t[207] = _deployToken("Mock FRAX", "FRAX", 18);
        t[208] = _deployToken("Mock FROGGIE", "FROGGIE", 18);
        t[209] = _deployToken("Mock FTT", "FTT", 18);
        t[210] = _deployToken("Mock FUEL", "FUEL", 18);
        t[211] = _deployToken("Mock FUN", "FUN", 18);
        t[212] = _deployToken("Mock F", "F", 18);
        t[213] = _deployToken("Mock GAIA", "GAIA", 18);
        t[214] = _deployToken("Mock GAIB", "GAIB", 18);
        t[215] = _deployToken("Mock GALA", "GALA", 18);
        t[216] = _deployToken("Mock GAME2", "GAME2", 18);
        t[217] = _deployToken("Mock GAS", "GAS", 18);
        t[218] = _deployToken("Mock GHO", "GHO", 18);
        t[219] = _deployToken("Mock GLMR", "GLMR", 18);
        t[220] = _deployToken("Mock GLM", "GLM", 18);
        t[221] = _deployToken("Mock GMT", "GMT", 18);
        t[222] = _deployToken("Mock GMX", "GMX", 18);
        t[223] = _deployToken("Mock GNO", "GNO", 18);
        t[224] = _deployToken("Mock GNS", "GNS", 18);
    }

    function _deployBatch9(address[] memory t) internal {
        t[225] = _deployToken("Mock GOAT", "GOAT", 18);
        t[226] = _deployToken("Mock GODS", "GODS", 18);
        t[227] = _deployToken("Mock GOMINING", "GOMINING", 18);
        t[228] = _deployToken("Mock GPS", "GPS", 18);
        t[229] = _deployToken("Mock GRASS", "GRASS", 18);
        t[230] = _deployToken("Mock GRT", "GRT", 18);
        t[231] = _deployToken("Mock GUN", "GUN", 18);
        t[232] = _deployToken("Mock G", "G", 18);
        t[233] = _deployToken("Mock GWEI", "GWEI", 18);
        t[234] = _deployToken("Mock HAEDAL", "HAEDAL", 18);
        t[235] = _deployToken("Mock HBAR", "HBAR", 18);
        t[236] = _deployToken("Mock HEI", "HEI", 18);
        t[237] = _deployToken("Mock HFT", "HFT", 18);
        t[238] = _deployToken("Mock HIGH", "HIGH", 18);
        t[239] = _deployToken("Mock HIPPO", "HIPPO", 18);
        t[240] = _deployToken("Mock HIVE", "HIVE", 18);
        t[241] = _deployToken("Mock HMSTR", "HMSTR", 18);
        t[242] = _deployToken("Mock HNT", "HNT", 18);
        t[243] = _deployToken("Mock HOLD", "HOLD", 18);
        t[244] = _deployToken("Mock HOLO", "HOLO", 18);
        t[245] = _deployToken("Mock HOME", "HOME", 18);
        t[246] = _deployToken("Mock HOOK", "HOOK", 18);
        t[247] = _deployToken("Mock HOT", "HOT", 18);
        t[248] = _deployToken("Mock HTX", "HTX", 18);
        t[249] = _deployToken("Mock HUMA", "HUMA", 18);
    }

    function _deployBatch10(address[] memory t) internal {
        t[250] = _deployToken("Mock H", "H", 18);
        t[251] = _deployToken("Mock HYPER", "HYPER", 18);
        t[252] = _deployToken("Mock HYPE", "HYPE", 18);
        t[253] = _deployToken("Mock IAG", "IAG", 18);
        t[254] = _deployToken("Mock ICNT", "ICNT", 18);
        t[255] = _deployToken("Mock ICP", "ICP", 18);
        t[256] = _deployToken("Mock ICX", "ICX", 18);
        t[257] = _deployToken("Mock IDOL", "IDOL", 18);
        t[258] = _deployToken("Mock ID", "ID", 18);
        t[259] = _deployToken("Mock IKA", "IKA", 18);
        t[260] = _deployToken("Mock ILV", "ILV", 18);
        t[261] = _deployToken("Mock IMU", "IMU", 18);
        t[262] = _deployToken("Mock IMX", "IMX", 18);
        t[263] = _deployToken("Mock INIT", "INIT", 18);
        t[264] = _deployToken("Mock INJ", "INJ", 18);
        t[265] = _deployToken("Mock INTER", "INTER", 18);
        t[266] = _deployToken("Mock IN", "IN", 18);
        t[267] = _deployToken("Mock IOST", "IOST", 18);
        t[268] = _deployToken("Mock IOTX", "IOTX", 18);
        t[269] = _deployToken("Mock IO", "IO", 18);
        t[270] = _deployToken("Mock IP", "IP", 18);
        t[271] = _deployToken("Mock IQ", "IQ", 18);
        t[272] = _deployToken("Mock IR", "IR", 18);
        t[273] = _deployToken("Mock IRYS", "IRYS", 18);
        t[274] = _deployToken("Mock JASMY", "JASMY", 18);
    }

    function _deployBatch11(address[] memory t) internal {
        t[275] = _deployToken("Mock JCT", "JCT", 18);
        t[276] = _deployToken("Mock JELLYJELLY", "JELLYJELLY", 18);
        t[277] = _deployToken("Mock JOE", "JOE", 18);
        t[278] = _deployToken("Mock JST", "JST", 18);
        t[279] = _deployToken("Mock JTO", "JTO", 18);
        t[280] = _deployToken("Mock JUP", "JUP", 18);
        t[281] = _deployToken("Mock J", "J", 18);
        t[282] = _deployToken("Mock JUV", "JUV", 18);
        t[283] = _deployToken("Mock KAIA", "KAIA", 18);
        t[284] = _deployToken("Mock KAITO", "KAITO", 18);
        t[285] = _deployToken("Mock KAS", "KAS", 18);
        t[286] = _deployToken("Mock KAVA", "KAVA", 18);
        t[287] = _deployToken("Mock KERNEL", "KERNEL", 18);
        t[288] = _deployToken("Mock KGEN", "KGEN", 18);
        t[289] = _deployToken("Mock KITE", "KITE", 18);
        t[290] = _deployToken("Mock KLV", "KLV", 18);
        t[291] = _deployToken("Mock KMNO", "KMNO", 18);
        t[292] = _deployToken("Mock KNC", "KNC", 18);
        t[293] = _deployToken("Mock KOMA", "KOMA", 18);
        t[294] = _deployToken("Mock KSM", "KSM", 18);
        t[295] = _deployToken("Mock KUB", "KUB", 18);
        t[296] = _deployToken("Mock K", "K", 18);
        t[297] = _deployToken("Mock LAB", "LAB", 18);
        t[298] = _deployToken("Mock LAT", "LAT", 18);
        t[299] = _deployToken("Mock LA", "LA", 18);
    }

    function _deployBatch12(address[] memory t) internal {
        t[300] = _deployToken("Mock LAYER", "LAYER", 18);
        t[301] = _deployToken("Mock LDO", "LDO", 18);
        t[302] = _deployToken("Mock LIGHT", "LIGHT", 18);
        t[303] = _deployToken("Mock LINEA", "LINEA", 18);
        t[304] = _deployToken("Mock LINK", "LINK", 18);
        t[305] = _deployToken("Mock LISTA", "LISTA", 18);
        t[306] = _deployToken("Mock LIT", "LIT", 18);
        t[307] = _deployToken("Mock LMWR", "LMWR", 18);
        t[308] = _deployToken("Mock LNQ", "LNQ", 18);
        t[309] = _deployToken("Mock LPT", "LPT", 18);
        t[310] = _deployToken("Mock LQTY", "LQTY", 18);
        t[311] = _deployToken("Mock LRC", "LRC", 18);
        t[312] = _deployToken("Mock LSK", "LSK", 18);
        t[313] = _deployToken("Mock LTC", "LTC", 18);
        t[314] = _deployToken("Mock LUMIA", "LUMIA", 18);
        t[315] = _deployToken("Mock LUNA", "LUNA", 18);
        t[316] = _deployToken("Mock LUNC", "LUNC", 18);
        t[317] = _deployToken("Mock MAGMA", "MAGMA", 18);
        t[318] = _deployToken("Mock MAK", "MAK", 18);
        t[319] = _deployToken("Mock MANA", "MANA", 18);
        t[320] = _deployToken("Mock MANTA", "MANTA", 18);
        t[321] = _deployToken("Mock MANTRA", "MANTRA", 18);
        t[322] = _deployToken("Mock MAPO", "MAPO", 18);
        t[323] = _deployToken("Mock MASK", "MASK", 18);
        t[324] = _deployToken("Mock MAS", "MAS", 18);
    }

    function _deployBatch13(address[] memory t) internal {
        t[325] = _deployToken("Mock MAV", "MAV", 18);
        t[326] = _deployToken("Mock MAXEXCHANGE", "MAXEXCHANGE", 18);
        t[327] = _deployToken("Mock MBL", "MBL", 18);
        t[328] = _deployToken("Mock MBOX", "MBOX", 18);
        t[329] = _deployToken("Mock MEME", "MEME", 18);
        t[330] = _deployToken("Mock MERL", "MERL", 18);
        t[331] = _deployToken("Mock METIS", "METIS", 18);
        t[332] = _deployToken("Mock MET", "MET", 18);
        t[333] = _deployToken("Mock ME", "ME", 18);
        t[334] = _deployToken("Mock MEW", "MEW", 18);
        t[335] = _deployToken("Mock MGO", "MGO", 18);
        t[336] = _deployToken("Mock MINA", "MINA", 18);
        t[337] = _deployToken("Mock MIRA", "MIRA", 18);
        t[338] = _deployToken("Mock ML", "ML", 18);
        t[339] = _deployToken("Mock MMT", "MMT", 18);
        t[340] = _deployToken("Mock MOCA", "MOCA", 18);
        t[341] = _deployToken("Mock MOEW", "MOEW", 18);
        t[342] = _deployToken("Mock MOG", "MOG", 18);
        t[343] = _deployToken("Mock MON", "MON", 18);
        t[344] = _deployToken("Mock MOODENG", "MOODENG", 18);
        t[345] = _deployToken("Mock MORPHO", "MORPHO", 18);
        t[346] = _deployToken("Mock MOVE", "MOVE", 18);
        t[347] = _deployToken("Mock MOVR", "MOVR", 18);
        t[348] = _deployToken("Mock MTL", "MTL", 18);
        t[349] = _deployToken("Mock MUBARAK", "MUBARAK", 18);
    }

    function _deployBatch14(address[] memory t) internal {
        t[350] = _deployToken("Mock M", "M", 18);
        t[351] = _deployToken("Mock MX", "MX", 18);
        t[352] = _deployToken("Mock MYX", "MYX", 18);
        t[353] = _deployToken("Mock NAORIS", "NAORIS", 18);
        t[354] = _deployToken("Mock NEAR", "NEAR", 18);
        t[355] = _deployToken("Mock NEIROCTO", "NEIROCTO", 18);
        t[356] = _deployToken("Mock NEO", "NEO", 18);
        t[357] = _deployToken("Mock NERO", "NERO", 18);
        t[358] = _deployToken("Mock NESS", "NESS", 18);
        t[359] = _deployToken("Mock NEWT", "NEWT", 18);
        t[360] = _deployToken("Mock NEXO", "NEXO", 18);
        t[361] = _deployToken("Mock NFP", "NFP", 18);
        t[362] = _deployToken("Mock NFT", "NFT", 18);
        t[363] = _deployToken("Mock NIL", "NIL", 18);
        t[364] = _deployToken("Mock NMR", "NMR", 18);
        t[365] = _deployToken("Mock NODE", "NODE", 18);
        t[366] = _deployToken("Mock NOM", "NOM", 18);
        t[367] = _deployToken("Mock NOT", "NOT", 18);
        t[368] = _deployToken("Mock NPC", "NPC", 18);
        t[369] = _deployToken("Mock NS", "NS", 18);
        t[370] = _deployToken("Mock NTRN", "NTRN", 18);
        t[371] = _deployToken("Mock NXPC", "NXPC", 18);
        t[372] = _deployToken("Mock NYM", "NYM", 18);
        t[373] = _deployToken("Mock OGN", "OGN", 18);
        t[374] = _deployToken("Mock OG", "OG", 18);
    }

    function _deployBatch15(address[] memory t) internal {
        t[375] = _deployToken("Mock ONDO", "ONDO", 18);
        t[376] = _deployToken("Mock ONE", "ONE", 18);
        t[377] = _deployToken("Mock ONT", "ONT", 18);
        t[378] = _deployToken("Mock OPEN", "OPEN", 18);
        t[379] = _deployToken("Mock OPN", "OPN", 18);
        t[380] = _deployToken("Mock OP", "OP", 18);
        t[381] = _deployToken("Mock ORBS", "ORBS", 18);
        t[382] = _deployToken("Mock ORCA", "ORCA", 18);
        t[383] = _deployToken("Mock ORDER", "ORDER", 18);
        t[384] = _deployToken("Mock ORDI", "ORDI", 18);
        t[385] = _deployToken("Mock OSMO", "OSMO", 18);
        t[386] = _deployToken("Mock OXT", "OXT", 18);
        t[387] = _deployToken("Mock PARTI", "PARTI", 18);
        t[388] = _deployToken("Mock PAXG", "PAXG", 18);
        t[389] = _deployToken("Mock PCI", "PCI", 18);
        t[390] = _deployToken("Mock PEAQ", "PEAQ", 18);
        t[391] = _deployToken("Mock PENDLE", "PENDLE", 18);
        t[392] = _deployToken("Mock PENGUIN", "PENGUIN", 18);
        t[393] = _deployToken("Mock PENGU", "PENGU", 18);
        t[394] = _deployToken("Mock PEOPLE", "PEOPLE", 18);
        t[395] = _deployToken("Mock PEPE", "PEPE", 18);
        t[396] = _deployToken("Mock PHA", "PHA", 18);
        t[397] = _deployToken("Mock PHB", "PHB", 18);
        t[398] = _deployToken("Mock PI", "PI", 18);
        t[399] = _deployToken("Mock PIXEL", "PIXEL", 18);
    }

    function _deployBatch16(address[] memory t) internal {
        t[400] = _deployToken("Mock PLAI", "PLAI", 18);
        t[401] = _deployToken("Mock PLANCK", "PLANCK", 18);
        t[402] = _deployToken("Mock PLUME", "PLUME", 18);
        t[403] = _deployToken("Mock PNUT", "PNUT", 18);
        t[404] = _deployToken("Mock POL", "POL", 18);
        t[405] = _deployToken("Mock POLYX", "POLYX", 18);
        t[406] = _deployToken("Mock PORTAL", "PORTAL", 18);
        t[407] = _deployToken("Mock PORTO", "PORTO", 18);
        t[408] = _deployToken("Mock POWER", "POWER", 18);
        t[409] = _deployToken("Mock POWR", "POWR", 18);
        t[410] = _deployToken("Mock PRAI", "PRAI", 18);
        t[411] = _deployToken("Mock PRCL", "PRCL", 18);
        t[412] = _deployToken("Mock PRIME", "PRIME", 18);
        t[413] = _deployToken("Mock PROMPT", "PROMPT", 18);
        t[414] = _deployToken("Mock PROM", "PROM", 18);
        t[415] = _deployToken("Mock PROPS", "PROPS", 18);
        t[416] = _deployToken("Mock PROVE", "PROVE", 18);
        t[417] = _deployToken("Mock PSG", "PSG", 18);
        t[418] = _deployToken("Mock PUBLIC", "PUBLIC", 18);
        t[419] = _deployToken("Mock PUFFER", "PUFFER", 18);
        t[420] = _deployToken("Mock PUMPBTC", "PUMPBTC", 18);
        t[421] = _deployToken("Mock PUMP", "PUMP", 18);
        t[422] = _deployToken("Mock PUNDIX", "PUNDIX", 18);
        t[423] = _deployToken("Mock P", "P", 18);
        t[424] = _deployToken("Mock PYR", "PYR", 18);
    }

    function _deployBatch17(address[] memory t) internal {
        t[425] = _deployToken("Mock PYTH", "PYTH", 18);
        t[426] = _deployToken("Mock PYUSD", "PYUSD", 18);
        t[427] = _deployToken("Mock QKC", "QKC", 18);
        t[428] = _deployToken("Mock QNT", "QNT", 18);
        t[429] = _deployToken("Mock QTUM", "QTUM", 18);
        t[430] = _deployToken("Mock QUBIC", "QUBIC", 18);
        t[431] = _deployToken("Mock Q", "Q", 18);
        t[432] = _deployToken("Mock RARE", "RARE", 18);
        t[433] = _deployToken("Mock RATS", "RATS", 18);
        t[434] = _deployToken("Mock RAVE", "RAVE", 18);
        t[435] = _deployToken("Mock RAY", "RAY", 18);
        t[436] = _deployToken("Mock RDAC", "RDAC", 18);
        t[437] = _deployToken("Mock RDNT", "RDNT", 18);
        t[438] = _deployToken("Mock RECALL", "RECALL", 18);
        t[439] = _deployToken("Mock RED", "RED", 18);
        t[440] = _deployToken("Mock RENDER", "RENDER", 18);
        t[441] = _deployToken("Mock RESOLV", "RESOLV", 18);
        t[442] = _deployToken("Mock REZ", "REZ", 18);
        t[443] = _deployToken("Mock RHEA", "RHEA", 18);
        t[444] = _deployToken("Mock RIF", "RIF", 18);
        t[445] = _deployToken("Mock RIVER", "RIVER", 18);
        t[446] = _deployToken("Mock RLC", "RLC", 18);
        t[447] = _deployToken("Mock RLS", "RLS", 18);
        t[448] = _deployToken("Mock RLUSD", "RLUSD", 18);
        t[449] = _deployToken("Mock ROAM", "ROAM", 18);
    }

    function _deployBatch18(address[] memory t) internal {
        t[450] = _deployToken("Mock ROBO", "ROBO", 18);
        t[451] = _deployToken("Mock ROLL", "ROLL", 18);
        t[452] = _deployToken("Mock RON", "RON", 18);
        t[453] = _deployToken("Mock ROSE", "ROSE", 18);
        t[454] = _deployToken("Mock RPL", "RPL", 18);
        t[455] = _deployToken("Mock RSR", "RSR", 18);
        t[456] = _deployToken("Mock RTX", "RTX", 18);
        t[457] = _deployToken("Mock RUNE", "RUNE", 18);
        t[458] = _deployToken("Mock RVN", "RVN", 18);
        t[459] = _deployToken("Mock RVV", "RVV", 18);
        t[460] = _deployToken("Mock RWA", "RWA", 18);
        t[461] = _deployToken("Mock SAFE", "SAFE", 18);
        t[462] = _deployToken("Mock SAGA", "SAGA", 18);
        t[463] = _deployToken("Mock SAHARA", "SAHARA", 18);
        t[464] = _deployToken("Mock SAND", "SAND", 18);
        t[465] = _deployToken("Mock SANTOS", "SANTOS", 18);
        t[466] = _deployToken("Mock SAPIEN", "SAPIEN", 18);
        t[467] = _deployToken("Mock SATS", "SATS", 18);
        t[468] = _deployToken("Mock SCA", "SCA", 18);
        t[469] = _deployToken("Mock SDEX", "SDEX", 18);
        t[470] = _deployToken("Mock SD", "SD", 18);
        t[471] = _deployToken("Mock SEI", "SEI", 18);
        t[472] = _deployToken("Mock SENT", "SENT", 18);
        t[473] = _deployToken("Mock SFP", "SFP", 18);
        t[474] = _deployToken("Mock SHELL", "SHELL", 18);
    }

    function _deployBatch19(address[] memory t) internal {
        t[475] = _deployToken("Mock SHIB", "SHIB", 18);
        t[476] = _deployToken("Mock SIGN", "SIGN", 18);
        t[477] = _deployToken("Mock SKL", "SKL", 18);
        t[478] = _deployToken("Mock SKR", "SKR", 18);
        t[479] = _deployToken("Mock SKY", "SKY", 18);
        t[480] = _deployToken("Mock SLP", "SLP", 18);
        t[481] = _deployToken("Mock SNEK", "SNEK", 18);
        t[482] = _deployToken("Mock SNT", "SNT", 18);
        t[483] = _deployToken("Mock SNX", "SNX", 18);
        t[484] = _deployToken("Mock SOLO", "SOLO", 18);
        t[485] = _deployToken("Mock SOL", "SOL", 18);
        t[486] = _deployToken("Mock SOLV", "SOLV", 18);
        t[487] = _deployToken("Mock SOMI", "SOMI", 18);
        t[488] = _deployToken("Mock SONIC", "SONIC", 18);
        t[489] = _deployToken("Mock SOON", "SOON", 18);
        t[490] = _deployToken("Mock SOPH", "SOPH", 18);
        t[491] = _deployToken("Mock SPACE", "SPACE", 18);
        t[492] = _deployToken("Mock SPELL", "SPELL", 18);
        t[493] = _deployToken("Mock SPK", "SPK", 18);
        t[494] = _deployToken("Mock SSV", "SSV", 18);
        t[495] = _deployToken("Mock STABLE", "STABLE", 18);
        t[496] = _deployToken("Mock STETH", "STETH", 18);
        t[497] = _deployToken("Mock STG", "STG", 18);
        t[498] = _deployToken("Mock STORJ", "STORJ", 18);
        t[499] = _deployToken("Mock STO", "STO", 18);
    }

    function _deployBatch20(address[] memory t) internal {
        t[500] = _deployToken("Mock STRAX", "STRAX", 18);
        t[501] = _deployToken("Mock STRK", "STRK", 18);
        t[502] = _deployToken("Mock STX", "STX", 18);
        t[503] = _deployToken("Mock SUI", "SUI", 18);
        t[504] = _deployToken("Mock SUN", "SUN", 18);
        t[505] = _deployToken("Mock SUPER", "SUPER", 18);
        t[506] = _deployToken("Mock S", "S", 18);
        t[507] = _deployToken("Mock SUSHI", "SUSHI", 18);
        t[508] = _deployToken("Mock SWARMS", "SWARMS", 18);
        t[509] = _deployToken("Mock SWCH", "SWCH", 18);
        t[510] = _deployToken("Mock SWEAT", "SWEAT", 18);
        t[511] = _deployToken("Mock SWELL", "SWELL", 18);
        t[512] = _deployToken("Mock SXP", "SXP", 18);
        t[513] = _deployToken("Mock SXT", "SXT", 18);
        t[514] = _deployToken("Mock SYN", "SYN", 18);
        t[515] = _deployToken("Mock SYRUP", "SYRUP", 18);
        t[516] = _deployToken("Mock SYS", "SYS", 18);
        t[517] = _deployToken("Mock TAC", "TAC", 18);
        t[518] = _deployToken("Mock TAG", "TAG", 18);
        t[519] = _deployToken("Mock TAIKO", "TAIKO", 18);
        t[520] = _deployToken("Mock TAO", "TAO", 18);
        t[521] = _deployToken("Mock TCOM", "TCOM", 18);
        t[522] = _deployToken("Mock THE", "THE", 18);
        t[523] = _deployToken("Mock THQ", "THQ", 18);
        t[524] = _deployToken("Mock TIA", "TIA", 18);
    }

    function _deployBatch21(address[] memory t) internal {
        t[525] = _deployToken("Mock TLM", "TLM", 18);
        t[526] = _deployToken("Mock TLOS", "TLOS", 18);
        t[527] = _deployToken("Mock TNSR", "TNSR", 18);
        t[528] = _deployToken("Mock TON", "TON", 18);
        t[529] = _deployToken("Mock TOSHI", "TOSHI", 18);
        t[530] = _deployToken("Mock TOWNS", "TOWNS", 18);
        t[531] = _deployToken("Mock TOWN", "TOWN", 18);
        t[532] = _deployToken("Mock TRADOOR", "TRADOOR", 18);
        t[533] = _deployToken("Mock TRB", "TRB", 18);
        t[534] = _deployToken("Mock TREE", "TREE", 18);
        t[535] = _deployToken("Mock TRIA", "TRIA", 18);
        t[536] = _deployToken("Mock TRUMP", "TRUMP", 18);
        t[537] = _deployToken("Mock TRUST", "TRUST", 18);
        t[538] = _deployToken("Mock TRU", "TRU", 18);
        t[539] = _deployToken("Mock TRX", "TRX", 18);
        t[540] = _deployToken("Mock TURBO", "TURBO", 18);
        t[541] = _deployToken("Mock T", "T", 18);
        t[542] = _deployToken("Mock TUSD", "TUSD", 18);
        t[543] = _deployToken("Mock TUT", "TUT", 18);
        t[544] = _deployToken("Mock TWT", "TWT", 18);
        t[545] = _deployToken("Mock U2U", "U2U", 18);
        t[546] = _deployToken("Mock UAI", "UAI", 18);
        t[547] = _deployToken("Mock UMA", "UMA", 18);
        t[548] = _deployToken("Mock UNI", "UNI", 18);
        t[549] = _deployToken("Mock UPC", "UPC", 18);
    }

    function _deployBatch22(address[] memory t) internal {
        t[550] = _deployToken("Mock USAT", "USAT", 18);
        t[551] = _deployToken("Mock USD1", "USD1", 18);
        t[552] = _deployToken("Mock USDC", "USDC", 18);
        t[553] = _deployToken("Mock USDE", "USDE", 18);
        t[554] = _deployToken("Mock USDGO", "USDGO", 18);
        t[555] = _deployToken("Mock USDS", "USDS", 18);
        t[556] = _deployToken("Mock USTC", "USTC", 18);
        t[557] = _deployToken("Mock USUAL", "USUAL", 18);
        t[558] = _deployToken("Mock US", "US", 18);
        t[559] = _deployToken("Mock UXLINK", "UXLINK", 18);
        t[560] = _deployToken("Mock VANA", "VANA", 18);
        t[561] = _deployToken("Mock VANRY", "VANRY", 18);
        t[562] = _deployToken("Mock VELODROME", "VELODROME", 18);
        t[563] = _deployToken("Mock VELO", "VELO", 18);
        t[564] = _deployToken("Mock VELVET", "VELVET", 18);
        t[565] = _deployToken("Mock VERT", "VERT", 18);
        t[566] = _deployToken("Mock VET", "VET", 18);
        t[567] = _deployToken("Mock VFY", "VFY", 18);
        t[568] = _deployToken("Mock VIC", "VIC", 18);
        t[569] = _deployToken("Mock VINE", "VINE", 18);
        t[570] = _deployToken("Mock VIRTUAL", "VIRTUAL", 18);
        t[571] = _deployToken("Mock VOOI", "VOOI", 18);
        t[572] = _deployToken("Mock VSN", "VSN", 18);
        t[573] = _deployToken("Mock VTHO", "VTHO", 18);
        t[574] = _deployToken("Mock WAI", "WAI", 18);
    }

    function _deployBatch23(address[] memory t) internal {
        t[575] = _deployToken("Mock WAL", "WAL", 18);
        t[576] = _deployToken("Mock WARD", "WARD", 18);
        t[577] = _deployToken("Mock WAVES", "WAVES", 18);
        t[578] = _deployToken("Mock WAXP", "WAXP", 18);
        t[579] = _deployToken("Mock WBTC", "WBTC", 18);
        t[580] = _deployToken("Mock WCT", "WCT", 18);
        t[581] = _deployToken("Mock WEETH", "WEETH", 18);
        t[582] = _deployToken("Mock WEMIX", "WEMIX", 18);
        t[583] = _deployToken("Mock WIF", "WIF", 18);
        t[584] = _deployToken("Mock WIN", "WIN", 18);
        t[585] = _deployToken("Mock WLD", "WLD", 18);
        t[586] = _deployToken("Mock WLFI", "WLFI", 18);
        t[587] = _deployToken("Mock WOO", "WOO", 18);
        t[588] = _deployToken("Mock W", "W", 18);
        t[589] = _deployToken("Mock WUSD", "WUSD", 18);
        t[590] = _deployToken("Mock XAI", "XAI", 18);
        t[591] = _deployToken("Mock XAUT", "XAUT", 18);
        t[592] = _deployToken("Mock XCX", "XCX", 18);
        t[593] = _deployToken("Mock XDC", "XDC", 18);
        t[594] = _deployToken("Mock XION", "XION", 18);
        t[595] = _deployToken("Mock XLM", "XLM", 18);
        t[596] = _deployToken("Mock XPL", "XPL", 18);
        t[597] = _deployToken("Mock XRP", "XRP", 18);
        t[598] = _deployToken("Mock XTER", "XTER", 18);
        t[599] = _deployToken("Mock XTZ", "XTZ", 18);
    }

    function _deployBatch24(address[] memory t) internal {
        t[600] = _deployToken("Mock YB", "YB", 18);
        t[601] = _deployToken("Mock YFI", "YFI", 18);
        t[602] = _deployToken("Mock YGG", "YGG", 18);
        t[603] = _deployToken("Mock ZAMA", "ZAMA", 18);
        t[604] = _deployToken("Mock ZBCN", "ZBCN", 18);
        t[605] = _deployToken("Mock ZBT", "ZBT", 18);
        t[606] = _deployToken("Mock ZEC", "ZEC", 18);
        t[607] = _deployToken("Mock ZENT", "ZENT", 18);
        t[608] = _deployToken("Mock ZEN", "ZEN", 18);
        t[609] = _deployToken("Mock ZEREBRO", "ZEREBRO", 18);
        t[610] = _deployToken("Mock ZETA", "ZETA", 18);
        t[611] = _deployToken("Mock ZIG", "ZIG", 18);
        t[612] = _deployToken("Mock ZIL", "ZIL", 18);
        t[613] = _deployToken("Mock ZKC", "ZKC", 18);
        t[614] = _deployToken("Mock ZKJ", "ZKJ", 18);
        t[615] = _deployToken("Mock ZKL", "ZKL", 18);
        t[616] = _deployToken("Mock ZK", "ZK", 18);
        t[617] = _deployToken("Mock ZORA", "ZORA", 18);
        t[618] = _deployToken("Mock ZRO", "ZRO", 18);
        t[619] = _deployToken("Mock ZRX", "ZRX", 18);
        t[620] = _deployToken("Mock ZTC", "ZTC", 18);
    }

    function _export(address[] memory t) internal {
        string memory out = "";
        for (uint256 i = 0; i < N; i++) {
            out = string.concat(out, vm.toString(i), ",", vm.toString(t[i]), "\n");
        }
        vm.writeFile("../data/all-token-addresses.csv", out);
        console.log("  Token addresses written to data/all-token-addresses.csv");
    }

}