// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/deploy-all-tokens.py — DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../test/mocks/MockERC20.sol";

/// @title DeployAllTokens - Deploy 621 Bitget tokens + fund vault
/// @dev Uses regular CREATE (not CREATE2). Sequential nonces with --slow guarantee unique addresses.
contract DeployAllTokens is Script {
    uint256 constant N = 621;
    uint256 constant FUND = 1_000_000 * 1e18;

    function run() external {
        uint256 pk = vm.envOr("PRIVATE_KEY", uint256(0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d));
        address bv = vm.envAddress("MOCK_BITGET_VAULT");

        address[] memory t = new address[](N);

        vm.startBroadcast(pk);
        _deployBatch0(t);
        _deployBatch1(t);
        _deployBatch2(t);
        _deployBatch3(t);
        _deployBatch4(t);
        _deployBatch5(t);
        _deployBatch6(t);
        _deployBatch7(t);
        _deployBatch8(t);
        _deployBatch9(t);
        _deployBatch10(t);
        _deployBatch11(t);
        _deployBatch12(t);
        _deployBatch13(t);
        _deployBatch14(t);
        _deployBatch15(t);
        _deployBatch16(t);
        _deployBatch17(t);
        _deployBatch18(t);
        _deployBatch19(t);
        _deployBatch20(t);
        _deployBatch21(t);
        _deployBatch22(t);
        _deployBatch23(t);
        _deployBatch24(t);
        // Fund vault with 1M of each token
        for (uint256 i = 0; i < N; i++) MockERC20(t[i]).mint(bv, FUND);
        vm.stopBroadcast();

        _export(t);
        console.log("Done: 621 tokens deployed, vault funded");
    }

    function _deployBatch0(address[] memory t) internal {
        t[0] = address(new MockERC20("Mock 0G", "0G", 18));
        t[1] = address(new MockERC20("Mock 1INCH", "1INCH", 18));
        t[2] = address(new MockERC20("Mock 2Z", "2Z", 18));
        t[3] = address(new MockERC20("Mock A47", "A47", 18));
        t[4] = address(new MockERC20("Mock A8", "A8", 18));
        t[5] = address(new MockERC20("Mock AAVE", "AAVE", 18));
        t[6] = address(new MockERC20("Mock AB", "AB", 18));
        t[7] = address(new MockERC20("Mock ACE", "ACE", 18));
        t[8] = address(new MockERC20("Mock ACH", "ACH", 18));
        t[9] = address(new MockERC20("Mock ACM", "ACM", 18));
        t[10] = address(new MockERC20("Mock ACT", "ACT", 18));
        t[11] = address(new MockERC20("Mock ACX", "ACX", 18));
        t[12] = address(new MockERC20("Mock ADA", "ADA", 18));
        t[13] = address(new MockERC20("Mock AERGO", "AERGO", 18));
        t[14] = address(new MockERC20("Mock AERO", "AERO", 18));
        t[15] = address(new MockERC20("Mock AEVO", "AEVO", 18));
        t[16] = address(new MockERC20("Mock AFC", "AFC", 18));
        t[17] = address(new MockERC20("Mock AGLD", "AGLD", 18));
        t[18] = address(new MockERC20("Mock AIA", "AIA", 18));
        t[19] = address(new MockERC20("Mock AIAV", "AIAV", 18));
        t[20] = address(new MockERC20("Mock AIN", "AIN", 18));
        t[21] = address(new MockERC20("Mock AIO", "AIO", 18));
        t[22] = address(new MockERC20("Mock AITECH", "AITECH", 18));
        t[23] = address(new MockERC20("Mock AI", "AI", 18));
        t[24] = address(new MockERC20("Mock AIXBT", "AIXBT", 18));
    }

    function _deployBatch1(address[] memory t) internal {
        t[25] = address(new MockERC20("Mock ALCH", "ALCH", 18));
        t[26] = address(new MockERC20("Mock ALGO", "ALGO", 18));
        t[27] = address(new MockERC20("Mock ALICE", "ALICE", 18));
        t[28] = address(new MockERC20("Mock ALLO", "ALLO", 18));
        t[29] = address(new MockERC20("Mock ALMANAK", "ALMANAK", 18));
        t[30] = address(new MockERC20("Mock ALPH", "ALPH", 18));
        t[31] = address(new MockERC20("Mock ALPINE", "ALPINE", 18));
        t[32] = address(new MockERC20("Mock ALT", "ALT", 18));
        t[33] = address(new MockERC20("Mock AL", "AL", 18));
        t[34] = address(new MockERC20("Mock AMP", "AMP", 18));
        t[35] = address(new MockERC20("Mock ANIME", "ANIME", 18));
        t[36] = address(new MockERC20("Mock ANKR", "ANKR", 18));
        t[37] = address(new MockERC20("Mock APE", "APE", 18));
        t[38] = address(new MockERC20("Mock API3", "API3", 18));
        t[39] = address(new MockERC20("Mock APR", "APR", 18));
        t[40] = address(new MockERC20("Mock APT", "APT", 18));
        t[41] = address(new MockERC20("Mock AQT", "AQT", 18));
        t[42] = address(new MockERC20("Mock ARB", "ARB", 18));
        t[43] = address(new MockERC20("Mock ARG", "ARG", 18));
        t[44] = address(new MockERC20("Mock ARIAIP", "ARIAIP", 18));
        t[45] = address(new MockERC20("Mock ARIA", "ARIA", 18));
        t[46] = address(new MockERC20("Mock ARKM", "ARKM", 18));
        t[47] = address(new MockERC20("Mock ARK", "ARK", 18));
        t[48] = address(new MockERC20("Mock ARPA", "ARPA", 18));
        t[49] = address(new MockERC20("Mock ARTX", "ARTX", 18));
    }

    function _deployBatch2(address[] memory t) internal {
        t[50] = address(new MockERC20("Mock AR", "AR", 18));
        t[51] = address(new MockERC20("Mock ASR", "ASR", 18));
        t[52] = address(new MockERC20("Mock ASTER", "ASTER", 18));
        t[53] = address(new MockERC20("Mock ASTR", "ASTR", 18));
        t[54] = address(new MockERC20("Mock ATH", "ATH", 18));
        t[55] = address(new MockERC20("Mock ATM", "ATM", 18));
        t[56] = address(new MockERC20("Mock ATOM", "ATOM", 18));
        t[57] = address(new MockERC20("Mock AUCTION", "AUCTION", 18));
        t[58] = address(new MockERC20("Mock AUDIO", "AUDIO", 18));
        t[59] = address(new MockERC20("Mock A", "A", 18));
        t[60] = address(new MockERC20("Mock AVA", "AVA", 18));
        t[61] = address(new MockERC20("Mock AVAX", "AVAX", 18));
        t[62] = address(new MockERC20("Mock AVNT", "AVNT", 18));
        t[63] = address(new MockERC20("Mock AWE", "AWE", 18));
        t[64] = address(new MockERC20("Mock AXL", "AXL", 18));
        t[65] = address(new MockERC20("Mock AXS", "AXS", 18));
        t[66] = address(new MockERC20("Mock B2", "B2", 18));
        t[67] = address(new MockERC20("Mock BABYDOGE", "BABYDOGE", 18));
        t[68] = address(new MockERC20("Mock BABY", "BABY", 18));
        t[69] = address(new MockERC20("Mock BANANAS31", "BANANAS31", 18));
        t[70] = address(new MockERC20("Mock BANANA", "BANANA", 18));
        t[71] = address(new MockERC20("Mock BAND", "BAND", 18));
        t[72] = address(new MockERC20("Mock BANK", "BANK", 18));
        t[73] = address(new MockERC20("Mock BAN", "BAN", 18));
        t[74] = address(new MockERC20("Mock BARD", "BARD", 18));
    }

    function _deployBatch3(address[] memory t) internal {
        t[75] = address(new MockERC20("Mock BAR", "BAR", 18));
        t[76] = address(new MockERC20("Mock BAT", "BAT", 18));
        t[77] = address(new MockERC20("Mock BAY", "BAY", 18));
        t[78] = address(new MockERC20("Mock BB", "BB", 18));
        t[79] = address(new MockERC20("Mock BCH", "BCH", 18));
        t[80] = address(new MockERC20("Mock BDXN", "BDXN", 18));
        t[81] = address(new MockERC20("Mock BEAM", "BEAM", 18));
        t[82] = address(new MockERC20("Mock BERA", "BERA", 18));
        t[83] = address(new MockERC20("Mock BGB", "BGB", 18));
        t[84] = address(new MockERC20("Mock BGSC", "BGSC", 18));
        t[85] = address(new MockERC20("Mock BGSOL", "BGSOL", 18));
        t[86] = address(new MockERC20("Mock BICO", "BICO", 18));
        t[87] = address(new MockERC20("Mock BIGTIME", "BIGTIME", 18));
        t[88] = address(new MockERC20("Mock BIO", "BIO", 18));
        t[89] = address(new MockERC20("Mock BIRB", "BIRB", 18));
        t[90] = address(new MockERC20("Mock BLAST", "BLAST", 18));
        t[91] = address(new MockERC20("Mock BLESS", "BLESS", 18));
        t[92] = address(new MockERC20("Mock BLUE", "BLUE", 18));
        t[93] = address(new MockERC20("Mock BLUM", "BLUM", 18));
        t[94] = address(new MockERC20("Mock BLUR", "BLUR", 18));
        t[95] = address(new MockERC20("Mock BMT", "BMT", 18));
        t[96] = address(new MockERC20("Mock BNB", "BNB", 18));
        t[97] = address(new MockERC20("Mock BNT", "BNT", 18));
        t[98] = address(new MockERC20("Mock BOME", "BOME", 18));
        t[99] = address(new MockERC20("Mock BONK", "BONK", 18));
    }

    function _deployBatch4(address[] memory t) internal {
        t[100] = address(new MockERC20("Mock BOS", "BOS", 18));
        t[101] = address(new MockERC20("Mock BRETT", "BRETT", 18));
        t[102] = address(new MockERC20("Mock BREV", "BREV", 18));
        t[103] = address(new MockERC20("Mock BROCCOLI", "BROCCOLI", 18));
        t[104] = address(new MockERC20("Mock BR", "BR", 18));
        t[105] = address(new MockERC20("Mock BSB", "BSB", 18));
        t[106] = address(new MockERC20("Mock BSU", "BSU", 18));
        t[107] = address(new MockERC20("Mock BSV", "BSV", 18));
        t[108] = address(new MockERC20("Mock BTC", "BTC", 18));
        t[109] = address(new MockERC20("Mock BTR", "BTR", 18));
        t[110] = address(new MockERC20("Mock BTT", "BTT", 18));
        t[111] = address(new MockERC20("Mock BTW", "BTW", 18));
        t[112] = address(new MockERC20("Mock B", "B", 18));
        t[113] = address(new MockERC20("Mock BYTE", "BYTE", 18));
        t[114] = address(new MockERC20("Mock C98", "C98", 18));
        t[115] = address(new MockERC20("Mock CAKE", "CAKE", 18));
        t[116] = address(new MockERC20("Mock CAMP", "CAMP", 18));
        t[117] = address(new MockERC20("Mock CARV", "CARV", 18));
        t[118] = address(new MockERC20("Mock CATI", "CATI", 18));
        t[119] = address(new MockERC20("Mock CBK", "CBK", 18));
        t[120] = address(new MockERC20("Mock CELO", "CELO", 18));
        t[121] = address(new MockERC20("Mock CELR", "CELR", 18));
        t[122] = address(new MockERC20("Mock CESS", "CESS", 18));
        t[123] = address(new MockERC20("Mock CETUS", "CETUS", 18));
        t[124] = address(new MockERC20("Mock CFX", "CFX", 18));
    }

    function _deployBatch5(address[] memory t) internal {
        t[125] = address(new MockERC20("Mock CGN", "CGN", 18));
        t[126] = address(new MockERC20("Mock CGPT", "CGPT", 18));
        t[127] = address(new MockERC20("Mock CHEEMS", "CHEEMS", 18));
        t[128] = address(new MockERC20("Mock CHILLGUY", "CHILLGUY", 18));
        t[129] = address(new MockERC20("Mock CHR", "CHR", 18));
        t[130] = address(new MockERC20("Mock CHZ", "CHZ", 18));
        t[131] = address(new MockERC20("Mock CKB", "CKB", 18));
        t[132] = address(new MockERC20("Mock CLANKER", "CLANKER", 18));
        t[133] = address(new MockERC20("Mock COAI", "COAI", 18));
        t[134] = address(new MockERC20("Mock COLLECT", "COLLECT", 18));
        t[135] = address(new MockERC20("Mock COMMON", "COMMON", 18));
        t[136] = address(new MockERC20("Mock COMP", "COMP", 18));
        t[137] = address(new MockERC20("Mock COOKIE", "COOKIE", 18));
        t[138] = address(new MockERC20("Mock CORE", "CORE", 18));
        t[139] = address(new MockERC20("Mock COTI", "COTI", 18));
        t[140] = address(new MockERC20("Mock COW", "COW", 18));
        t[141] = address(new MockERC20("Mock CPOOL", "CPOOL", 18));
        t[142] = address(new MockERC20("Mock CREO", "CREO", 18));
        t[143] = address(new MockERC20("Mock CROSS", "CROSS", 18));
        t[144] = address(new MockERC20("Mock CRO", "CRO", 18));
        t[145] = address(new MockERC20("Mock CRV", "CRV", 18));
        t[146] = address(new MockERC20("Mock CSPR", "CSPR", 18));
        t[147] = address(new MockERC20("Mock CTC", "CTC", 18));
        t[148] = address(new MockERC20("Mock CTSI", "CTSI", 18));
        t[149] = address(new MockERC20("Mock CUDIS", "CUDIS", 18));
    }

    function _deployBatch6(address[] memory t) internal {
        t[150] = address(new MockERC20("Mock C", "C", 18));
        t[151] = address(new MockERC20("Mock CVC", "CVC", 18));
        t[152] = address(new MockERC20("Mock CVX", "CVX", 18));
        t[153] = address(new MockERC20("Mock CYBER", "CYBER", 18));
        t[154] = address(new MockERC20("Mock CYS", "CYS", 18));
        t[155] = address(new MockERC20("Mock DAI", "DAI", 18));
        t[156] = address(new MockERC20("Mock DBR", "DBR", 18));
        t[157] = address(new MockERC20("Mock DEEP", "DEEP", 18));
        t[158] = address(new MockERC20("Mock DEGEN", "DEGEN", 18));
        t[159] = address(new MockERC20("Mock DENT", "DENT", 18));
        t[160] = address(new MockERC20("Mock DMC", "DMC", 18));
        t[161] = address(new MockERC20("Mock DN", "DN", 18));
        t[162] = address(new MockERC20("Mock DODO", "DODO", 18));
        t[163] = address(new MockERC20("Mock DOGE", "DOGE", 18));
        t[164] = address(new MockERC20("Mock DOGS", "DOGS", 18));
        t[165] = address(new MockERC20("Mock DOG", "DOG", 18));
        t[166] = address(new MockERC20("Mock DOOD", "DOOD", 18));
        t[167] = address(new MockERC20("Mock DOT", "DOT", 18));
        t[168] = address(new MockERC20("Mock DRIFT", "DRIFT", 18));
        t[169] = address(new MockERC20("Mock DTEC", "DTEC", 18));
        t[170] = address(new MockERC20("Mock DUCK", "DUCK", 18));
        t[171] = address(new MockERC20("Mock D", "D", 18));
        t[172] = address(new MockERC20("Mock DUSK", "DUSK", 18));
        t[173] = address(new MockERC20("Mock DYDX", "DYDX", 18));
        t[174] = address(new MockERC20("Mock DYM", "DYM", 18));
    }

    function _deployBatch7(address[] memory t) internal {
        t[175] = address(new MockERC20("Mock EDEN", "EDEN", 18));
        t[176] = address(new MockERC20("Mock EGL1", "EGL1", 18));
        t[177] = address(new MockERC20("Mock EGLD", "EGLD", 18));
        t[178] = address(new MockERC20("Mock EIGEN", "EIGEN", 18));
        t[179] = address(new MockERC20("Mock ELA", "ELA", 18));
        t[180] = address(new MockERC20("Mock ELIZAOS", "ELIZAOS", 18));
        t[181] = address(new MockERC20("Mock ENA", "ENA", 18));
        t[182] = address(new MockERC20("Mock ENJ", "ENJ", 18));
        t[183] = address(new MockERC20("Mock ENSO", "ENSO", 18));
        t[184] = address(new MockERC20("Mock ENS", "ENS", 18));
        t[185] = address(new MockERC20("Mock EPT", "EPT", 18));
        t[186] = address(new MockERC20("Mock ERA", "ERA", 18));
        t[187] = address(new MockERC20("Mock ESIM", "ESIM", 18));
        t[188] = address(new MockERC20("Mock ESPORTS", "ESPORTS", 18));
        t[189] = address(new MockERC20("Mock ES", "ES", 18));
        t[190] = address(new MockERC20("Mock ETC", "ETC", 18));
        t[191] = address(new MockERC20("Mock ETHFI", "ETHFI", 18));
        t[192] = address(new MockERC20("Mock ETH", "ETH", 18));
        t[193] = address(new MockERC20("Mock ETHW", "ETHW", 18));
        t[194] = address(new MockERC20("Mock FARTCOIN", "FARTCOIN", 18));
        t[195] = address(new MockERC20("Mock FET", "FET", 18));
        t[196] = address(new MockERC20("Mock FF", "FF", 18));
        t[197] = address(new MockERC20("Mock FHE", "FHE", 18));
        t[198] = address(new MockERC20("Mock FIDA", "FIDA", 18));
        t[199] = address(new MockERC20("Mock FIL", "FIL", 18));
    }

    function _deployBatch8(address[] memory t) internal {
        t[200] = address(new MockERC20("Mock FLK", "FLK", 18));
        t[201] = address(new MockERC20("Mock FLOCK", "FLOCK", 18));
        t[202] = address(new MockERC20("Mock FLOKI", "FLOKI", 18));
        t[203] = address(new MockERC20("Mock FLOW", "FLOW", 18));
        t[204] = address(new MockERC20("Mock FLUX", "FLUX", 18));
        t[205] = address(new MockERC20("Mock FOGO", "FOGO", 18));
        t[206] = address(new MockERC20("Mock FORM", "FORM", 18));
        t[207] = address(new MockERC20("Mock FRAX", "FRAX", 18));
        t[208] = address(new MockERC20("Mock FROGGIE", "FROGGIE", 18));
        t[209] = address(new MockERC20("Mock FTT", "FTT", 18));
        t[210] = address(new MockERC20("Mock FUEL", "FUEL", 18));
        t[211] = address(new MockERC20("Mock FUN", "FUN", 18));
        t[212] = address(new MockERC20("Mock F", "F", 18));
        t[213] = address(new MockERC20("Mock GAIA", "GAIA", 18));
        t[214] = address(new MockERC20("Mock GAIB", "GAIB", 18));
        t[215] = address(new MockERC20("Mock GALA", "GALA", 18));
        t[216] = address(new MockERC20("Mock GAME2", "GAME2", 18));
        t[217] = address(new MockERC20("Mock GAS", "GAS", 18));
        t[218] = address(new MockERC20("Mock GHO", "GHO", 18));
        t[219] = address(new MockERC20("Mock GLMR", "GLMR", 18));
        t[220] = address(new MockERC20("Mock GLM", "GLM", 18));
        t[221] = address(new MockERC20("Mock GMT", "GMT", 18));
        t[222] = address(new MockERC20("Mock GMX", "GMX", 18));
        t[223] = address(new MockERC20("Mock GNO", "GNO", 18));
        t[224] = address(new MockERC20("Mock GNS", "GNS", 18));
    }

    function _deployBatch9(address[] memory t) internal {
        t[225] = address(new MockERC20("Mock GOAT", "GOAT", 18));
        t[226] = address(new MockERC20("Mock GODS", "GODS", 18));
        t[227] = address(new MockERC20("Mock GOMINING", "GOMINING", 18));
        t[228] = address(new MockERC20("Mock GPS", "GPS", 18));
        t[229] = address(new MockERC20("Mock GRASS", "GRASS", 18));
        t[230] = address(new MockERC20("Mock GRT", "GRT", 18));
        t[231] = address(new MockERC20("Mock GUN", "GUN", 18));
        t[232] = address(new MockERC20("Mock G", "G", 18));
        t[233] = address(new MockERC20("Mock GWEI", "GWEI", 18));
        t[234] = address(new MockERC20("Mock HAEDAL", "HAEDAL", 18));
        t[235] = address(new MockERC20("Mock HBAR", "HBAR", 18));
        t[236] = address(new MockERC20("Mock HEI", "HEI", 18));
        t[237] = address(new MockERC20("Mock HFT", "HFT", 18));
        t[238] = address(new MockERC20("Mock HIGH", "HIGH", 18));
        t[239] = address(new MockERC20("Mock HIPPO", "HIPPO", 18));
        t[240] = address(new MockERC20("Mock HIVE", "HIVE", 18));
        t[241] = address(new MockERC20("Mock HMSTR", "HMSTR", 18));
        t[242] = address(new MockERC20("Mock HNT", "HNT", 18));
        t[243] = address(new MockERC20("Mock HOLD", "HOLD", 18));
        t[244] = address(new MockERC20("Mock HOLO", "HOLO", 18));
        t[245] = address(new MockERC20("Mock HOME", "HOME", 18));
        t[246] = address(new MockERC20("Mock HOOK", "HOOK", 18));
        t[247] = address(new MockERC20("Mock HOT", "HOT", 18));
        t[248] = address(new MockERC20("Mock HTX", "HTX", 18));
        t[249] = address(new MockERC20("Mock HUMA", "HUMA", 18));
    }

    function _deployBatch10(address[] memory t) internal {
        t[250] = address(new MockERC20("Mock H", "H", 18));
        t[251] = address(new MockERC20("Mock HYPER", "HYPER", 18));
        t[252] = address(new MockERC20("Mock HYPE", "HYPE", 18));
        t[253] = address(new MockERC20("Mock IAG", "IAG", 18));
        t[254] = address(new MockERC20("Mock ICNT", "ICNT", 18));
        t[255] = address(new MockERC20("Mock ICP", "ICP", 18));
        t[256] = address(new MockERC20("Mock ICX", "ICX", 18));
        t[257] = address(new MockERC20("Mock IDOL", "IDOL", 18));
        t[258] = address(new MockERC20("Mock ID", "ID", 18));
        t[259] = address(new MockERC20("Mock IKA", "IKA", 18));
        t[260] = address(new MockERC20("Mock ILV", "ILV", 18));
        t[261] = address(new MockERC20("Mock IMU", "IMU", 18));
        t[262] = address(new MockERC20("Mock IMX", "IMX", 18));
        t[263] = address(new MockERC20("Mock INIT", "INIT", 18));
        t[264] = address(new MockERC20("Mock INJ", "INJ", 18));
        t[265] = address(new MockERC20("Mock INTER", "INTER", 18));
        t[266] = address(new MockERC20("Mock IN", "IN", 18));
        t[267] = address(new MockERC20("Mock IOST", "IOST", 18));
        t[268] = address(new MockERC20("Mock IOTX", "IOTX", 18));
        t[269] = address(new MockERC20("Mock IO", "IO", 18));
        t[270] = address(new MockERC20("Mock IP", "IP", 18));
        t[271] = address(new MockERC20("Mock IQ", "IQ", 18));
        t[272] = address(new MockERC20("Mock IR", "IR", 18));
        t[273] = address(new MockERC20("Mock IRYS", "IRYS", 18));
        t[274] = address(new MockERC20("Mock JASMY", "JASMY", 18));
    }

    function _deployBatch11(address[] memory t) internal {
        t[275] = address(new MockERC20("Mock JCT", "JCT", 18));
        t[276] = address(new MockERC20("Mock JELLYJELLY", "JELLYJELLY", 18));
        t[277] = address(new MockERC20("Mock JOE", "JOE", 18));
        t[278] = address(new MockERC20("Mock JST", "JST", 18));
        t[279] = address(new MockERC20("Mock JTO", "JTO", 18));
        t[280] = address(new MockERC20("Mock JUP", "JUP", 18));
        t[281] = address(new MockERC20("Mock J", "J", 18));
        t[282] = address(new MockERC20("Mock JUV", "JUV", 18));
        t[283] = address(new MockERC20("Mock KAIA", "KAIA", 18));
        t[284] = address(new MockERC20("Mock KAITO", "KAITO", 18));
        t[285] = address(new MockERC20("Mock KAS", "KAS", 18));
        t[286] = address(new MockERC20("Mock KAVA", "KAVA", 18));
        t[287] = address(new MockERC20("Mock KERNEL", "KERNEL", 18));
        t[288] = address(new MockERC20("Mock KGEN", "KGEN", 18));
        t[289] = address(new MockERC20("Mock KITE", "KITE", 18));
        t[290] = address(new MockERC20("Mock KLV", "KLV", 18));
        t[291] = address(new MockERC20("Mock KMNO", "KMNO", 18));
        t[292] = address(new MockERC20("Mock KNC", "KNC", 18));
        t[293] = address(new MockERC20("Mock KOMA", "KOMA", 18));
        t[294] = address(new MockERC20("Mock KSM", "KSM", 18));
        t[295] = address(new MockERC20("Mock KUB", "KUB", 18));
        t[296] = address(new MockERC20("Mock K", "K", 18));
        t[297] = address(new MockERC20("Mock LAB", "LAB", 18));
        t[298] = address(new MockERC20("Mock LAT", "LAT", 18));
        t[299] = address(new MockERC20("Mock LA", "LA", 18));
    }

    function _deployBatch12(address[] memory t) internal {
        t[300] = address(new MockERC20("Mock LAYER", "LAYER", 18));
        t[301] = address(new MockERC20("Mock LDO", "LDO", 18));
        t[302] = address(new MockERC20("Mock LIGHT", "LIGHT", 18));
        t[303] = address(new MockERC20("Mock LINEA", "LINEA", 18));
        t[304] = address(new MockERC20("Mock LINK", "LINK", 18));
        t[305] = address(new MockERC20("Mock LISTA", "LISTA", 18));
        t[306] = address(new MockERC20("Mock LIT", "LIT", 18));
        t[307] = address(new MockERC20("Mock LMWR", "LMWR", 18));
        t[308] = address(new MockERC20("Mock LNQ", "LNQ", 18));
        t[309] = address(new MockERC20("Mock LPT", "LPT", 18));
        t[310] = address(new MockERC20("Mock LQTY", "LQTY", 18));
        t[311] = address(new MockERC20("Mock LRC", "LRC", 18));
        t[312] = address(new MockERC20("Mock LSK", "LSK", 18));
        t[313] = address(new MockERC20("Mock LTC", "LTC", 18));
        t[314] = address(new MockERC20("Mock LUMIA", "LUMIA", 18));
        t[315] = address(new MockERC20("Mock LUNA", "LUNA", 18));
        t[316] = address(new MockERC20("Mock LUNC", "LUNC", 18));
        t[317] = address(new MockERC20("Mock MAGMA", "MAGMA", 18));
        t[318] = address(new MockERC20("Mock MAK", "MAK", 18));
        t[319] = address(new MockERC20("Mock MANA", "MANA", 18));
        t[320] = address(new MockERC20("Mock MANTA", "MANTA", 18));
        t[321] = address(new MockERC20("Mock MANTRA", "MANTRA", 18));
        t[322] = address(new MockERC20("Mock MAPO", "MAPO", 18));
        t[323] = address(new MockERC20("Mock MASK", "MASK", 18));
        t[324] = address(new MockERC20("Mock MAS", "MAS", 18));
    }

    function _deployBatch13(address[] memory t) internal {
        t[325] = address(new MockERC20("Mock MAV", "MAV", 18));
        t[326] = address(new MockERC20("Mock MAXEXCHANGE", "MAXEXCHANGE", 18));
        t[327] = address(new MockERC20("Mock MBL", "MBL", 18));
        t[328] = address(new MockERC20("Mock MBOX", "MBOX", 18));
        t[329] = address(new MockERC20("Mock MEME", "MEME", 18));
        t[330] = address(new MockERC20("Mock MERL", "MERL", 18));
        t[331] = address(new MockERC20("Mock METIS", "METIS", 18));
        t[332] = address(new MockERC20("Mock MET", "MET", 18));
        t[333] = address(new MockERC20("Mock ME", "ME", 18));
        t[334] = address(new MockERC20("Mock MEW", "MEW", 18));
        t[335] = address(new MockERC20("Mock MGO", "MGO", 18));
        t[336] = address(new MockERC20("Mock MINA", "MINA", 18));
        t[337] = address(new MockERC20("Mock MIRA", "MIRA", 18));
        t[338] = address(new MockERC20("Mock ML", "ML", 18));
        t[339] = address(new MockERC20("Mock MMT", "MMT", 18));
        t[340] = address(new MockERC20("Mock MOCA", "MOCA", 18));
        t[341] = address(new MockERC20("Mock MOEW", "MOEW", 18));
        t[342] = address(new MockERC20("Mock MOG", "MOG", 18));
        t[343] = address(new MockERC20("Mock MON", "MON", 18));
        t[344] = address(new MockERC20("Mock MOODENG", "MOODENG", 18));
        t[345] = address(new MockERC20("Mock MORPHO", "MORPHO", 18));
        t[346] = address(new MockERC20("Mock MOVE", "MOVE", 18));
        t[347] = address(new MockERC20("Mock MOVR", "MOVR", 18));
        t[348] = address(new MockERC20("Mock MTL", "MTL", 18));
        t[349] = address(new MockERC20("Mock MUBARAK", "MUBARAK", 18));
    }

    function _deployBatch14(address[] memory t) internal {
        t[350] = address(new MockERC20("Mock M", "M", 18));
        t[351] = address(new MockERC20("Mock MX", "MX", 18));
        t[352] = address(new MockERC20("Mock MYX", "MYX", 18));
        t[353] = address(new MockERC20("Mock NAORIS", "NAORIS", 18));
        t[354] = address(new MockERC20("Mock NEAR", "NEAR", 18));
        t[355] = address(new MockERC20("Mock NEIROCTO", "NEIROCTO", 18));
        t[356] = address(new MockERC20("Mock NEO", "NEO", 18));
        t[357] = address(new MockERC20("Mock NERO", "NERO", 18));
        t[358] = address(new MockERC20("Mock NESS", "NESS", 18));
        t[359] = address(new MockERC20("Mock NEWT", "NEWT", 18));
        t[360] = address(new MockERC20("Mock NEXO", "NEXO", 18));
        t[361] = address(new MockERC20("Mock NFP", "NFP", 18));
        t[362] = address(new MockERC20("Mock NFT", "NFT", 18));
        t[363] = address(new MockERC20("Mock NIL", "NIL", 18));
        t[364] = address(new MockERC20("Mock NMR", "NMR", 18));
        t[365] = address(new MockERC20("Mock NODE", "NODE", 18));
        t[366] = address(new MockERC20("Mock NOM", "NOM", 18));
        t[367] = address(new MockERC20("Mock NOT", "NOT", 18));
        t[368] = address(new MockERC20("Mock NPC", "NPC", 18));
        t[369] = address(new MockERC20("Mock NS", "NS", 18));
        t[370] = address(new MockERC20("Mock NTRN", "NTRN", 18));
        t[371] = address(new MockERC20("Mock NXPC", "NXPC", 18));
        t[372] = address(new MockERC20("Mock NYM", "NYM", 18));
        t[373] = address(new MockERC20("Mock OGN", "OGN", 18));
        t[374] = address(new MockERC20("Mock OG", "OG", 18));
    }

    function _deployBatch15(address[] memory t) internal {
        t[375] = address(new MockERC20("Mock ONDO", "ONDO", 18));
        t[376] = address(new MockERC20("Mock ONE", "ONE", 18));
        t[377] = address(new MockERC20("Mock ONT", "ONT", 18));
        t[378] = address(new MockERC20("Mock OPEN", "OPEN", 18));
        t[379] = address(new MockERC20("Mock OPN", "OPN", 18));
        t[380] = address(new MockERC20("Mock OP", "OP", 18));
        t[381] = address(new MockERC20("Mock ORBS", "ORBS", 18));
        t[382] = address(new MockERC20("Mock ORCA", "ORCA", 18));
        t[383] = address(new MockERC20("Mock ORDER", "ORDER", 18));
        t[384] = address(new MockERC20("Mock ORDI", "ORDI", 18));
        t[385] = address(new MockERC20("Mock OSMO", "OSMO", 18));
        t[386] = address(new MockERC20("Mock OXT", "OXT", 18));
        t[387] = address(new MockERC20("Mock PARTI", "PARTI", 18));
        t[388] = address(new MockERC20("Mock PAXG", "PAXG", 18));
        t[389] = address(new MockERC20("Mock PCI", "PCI", 18));
        t[390] = address(new MockERC20("Mock PEAQ", "PEAQ", 18));
        t[391] = address(new MockERC20("Mock PENDLE", "PENDLE", 18));
        t[392] = address(new MockERC20("Mock PENGUIN", "PENGUIN", 18));
        t[393] = address(new MockERC20("Mock PENGU", "PENGU", 18));
        t[394] = address(new MockERC20("Mock PEOPLE", "PEOPLE", 18));
        t[395] = address(new MockERC20("Mock PEPE", "PEPE", 18));
        t[396] = address(new MockERC20("Mock PHA", "PHA", 18));
        t[397] = address(new MockERC20("Mock PHB", "PHB", 18));
        t[398] = address(new MockERC20("Mock PI", "PI", 18));
        t[399] = address(new MockERC20("Mock PIXEL", "PIXEL", 18));
    }

    function _deployBatch16(address[] memory t) internal {
        t[400] = address(new MockERC20("Mock PLAI", "PLAI", 18));
        t[401] = address(new MockERC20("Mock PLANCK", "PLANCK", 18));
        t[402] = address(new MockERC20("Mock PLUME", "PLUME", 18));
        t[403] = address(new MockERC20("Mock PNUT", "PNUT", 18));
        t[404] = address(new MockERC20("Mock POL", "POL", 18));
        t[405] = address(new MockERC20("Mock POLYX", "POLYX", 18));
        t[406] = address(new MockERC20("Mock PORTAL", "PORTAL", 18));
        t[407] = address(new MockERC20("Mock PORTO", "PORTO", 18));
        t[408] = address(new MockERC20("Mock POWER", "POWER", 18));
        t[409] = address(new MockERC20("Mock POWR", "POWR", 18));
        t[410] = address(new MockERC20("Mock PRAI", "PRAI", 18));
        t[411] = address(new MockERC20("Mock PRCL", "PRCL", 18));
        t[412] = address(new MockERC20("Mock PRIME", "PRIME", 18));
        t[413] = address(new MockERC20("Mock PROMPT", "PROMPT", 18));
        t[414] = address(new MockERC20("Mock PROM", "PROM", 18));
        t[415] = address(new MockERC20("Mock PROPS", "PROPS", 18));
        t[416] = address(new MockERC20("Mock PROVE", "PROVE", 18));
        t[417] = address(new MockERC20("Mock PSG", "PSG", 18));
        t[418] = address(new MockERC20("Mock PUBLIC", "PUBLIC", 18));
        t[419] = address(new MockERC20("Mock PUFFER", "PUFFER", 18));
        t[420] = address(new MockERC20("Mock PUMPBTC", "PUMPBTC", 18));
        t[421] = address(new MockERC20("Mock PUMP", "PUMP", 18));
        t[422] = address(new MockERC20("Mock PUNDIX", "PUNDIX", 18));
        t[423] = address(new MockERC20("Mock P", "P", 18));
        t[424] = address(new MockERC20("Mock PYR", "PYR", 18));
    }

    function _deployBatch17(address[] memory t) internal {
        t[425] = address(new MockERC20("Mock PYTH", "PYTH", 18));
        t[426] = address(new MockERC20("Mock PYUSD", "PYUSD", 18));
        t[427] = address(new MockERC20("Mock QKC", "QKC", 18));
        t[428] = address(new MockERC20("Mock QNT", "QNT", 18));
        t[429] = address(new MockERC20("Mock QTUM", "QTUM", 18));
        t[430] = address(new MockERC20("Mock QUBIC", "QUBIC", 18));
        t[431] = address(new MockERC20("Mock Q", "Q", 18));
        t[432] = address(new MockERC20("Mock RARE", "RARE", 18));
        t[433] = address(new MockERC20("Mock RATS", "RATS", 18));
        t[434] = address(new MockERC20("Mock RAVE", "RAVE", 18));
        t[435] = address(new MockERC20("Mock RAY", "RAY", 18));
        t[436] = address(new MockERC20("Mock RDAC", "RDAC", 18));
        t[437] = address(new MockERC20("Mock RDNT", "RDNT", 18));
        t[438] = address(new MockERC20("Mock RECALL", "RECALL", 18));
        t[439] = address(new MockERC20("Mock RED", "RED", 18));
        t[440] = address(new MockERC20("Mock RENDER", "RENDER", 18));
        t[441] = address(new MockERC20("Mock RESOLV", "RESOLV", 18));
        t[442] = address(new MockERC20("Mock REZ", "REZ", 18));
        t[443] = address(new MockERC20("Mock RHEA", "RHEA", 18));
        t[444] = address(new MockERC20("Mock RIF", "RIF", 18));
        t[445] = address(new MockERC20("Mock RIVER", "RIVER", 18));
        t[446] = address(new MockERC20("Mock RLC", "RLC", 18));
        t[447] = address(new MockERC20("Mock RLS", "RLS", 18));
        t[448] = address(new MockERC20("Mock RLUSD", "RLUSD", 18));
        t[449] = address(new MockERC20("Mock ROAM", "ROAM", 18));
    }

    function _deployBatch18(address[] memory t) internal {
        t[450] = address(new MockERC20("Mock ROBO", "ROBO", 18));
        t[451] = address(new MockERC20("Mock ROLL", "ROLL", 18));
        t[452] = address(new MockERC20("Mock RON", "RON", 18));
        t[453] = address(new MockERC20("Mock ROSE", "ROSE", 18));
        t[454] = address(new MockERC20("Mock RPL", "RPL", 18));
        t[455] = address(new MockERC20("Mock RSR", "RSR", 18));
        t[456] = address(new MockERC20("Mock RTX", "RTX", 18));
        t[457] = address(new MockERC20("Mock RUNE", "RUNE", 18));
        t[458] = address(new MockERC20("Mock RVN", "RVN", 18));
        t[459] = address(new MockERC20("Mock RVV", "RVV", 18));
        t[460] = address(new MockERC20("Mock RWA", "RWA", 18));
        t[461] = address(new MockERC20("Mock SAFE", "SAFE", 18));
        t[462] = address(new MockERC20("Mock SAGA", "SAGA", 18));
        t[463] = address(new MockERC20("Mock SAHARA", "SAHARA", 18));
        t[464] = address(new MockERC20("Mock SAND", "SAND", 18));
        t[465] = address(new MockERC20("Mock SANTOS", "SANTOS", 18));
        t[466] = address(new MockERC20("Mock SAPIEN", "SAPIEN", 18));
        t[467] = address(new MockERC20("Mock SATS", "SATS", 18));
        t[468] = address(new MockERC20("Mock SCA", "SCA", 18));
        t[469] = address(new MockERC20("Mock SDEX", "SDEX", 18));
        t[470] = address(new MockERC20("Mock SD", "SD", 18));
        t[471] = address(new MockERC20("Mock SEI", "SEI", 18));
        t[472] = address(new MockERC20("Mock SENT", "SENT", 18));
        t[473] = address(new MockERC20("Mock SFP", "SFP", 18));
        t[474] = address(new MockERC20("Mock SHELL", "SHELL", 18));
    }

    function _deployBatch19(address[] memory t) internal {
        t[475] = address(new MockERC20("Mock SHIB", "SHIB", 18));
        t[476] = address(new MockERC20("Mock SIGN", "SIGN", 18));
        t[477] = address(new MockERC20("Mock SKL", "SKL", 18));
        t[478] = address(new MockERC20("Mock SKR", "SKR", 18));
        t[479] = address(new MockERC20("Mock SKY", "SKY", 18));
        t[480] = address(new MockERC20("Mock SLP", "SLP", 18));
        t[481] = address(new MockERC20("Mock SNEK", "SNEK", 18));
        t[482] = address(new MockERC20("Mock SNT", "SNT", 18));
        t[483] = address(new MockERC20("Mock SNX", "SNX", 18));
        t[484] = address(new MockERC20("Mock SOLO", "SOLO", 18));
        t[485] = address(new MockERC20("Mock SOL", "SOL", 18));
        t[486] = address(new MockERC20("Mock SOLV", "SOLV", 18));
        t[487] = address(new MockERC20("Mock SOMI", "SOMI", 18));
        t[488] = address(new MockERC20("Mock SONIC", "SONIC", 18));
        t[489] = address(new MockERC20("Mock SOON", "SOON", 18));
        t[490] = address(new MockERC20("Mock SOPH", "SOPH", 18));
        t[491] = address(new MockERC20("Mock SPACE", "SPACE", 18));
        t[492] = address(new MockERC20("Mock SPELL", "SPELL", 18));
        t[493] = address(new MockERC20("Mock SPK", "SPK", 18));
        t[494] = address(new MockERC20("Mock SSV", "SSV", 18));
        t[495] = address(new MockERC20("Mock STABLE", "STABLE", 18));
        t[496] = address(new MockERC20("Mock STETH", "STETH", 18));
        t[497] = address(new MockERC20("Mock STG", "STG", 18));
        t[498] = address(new MockERC20("Mock STORJ", "STORJ", 18));
        t[499] = address(new MockERC20("Mock STO", "STO", 18));
    }

    function _deployBatch20(address[] memory t) internal {
        t[500] = address(new MockERC20("Mock STRAX", "STRAX", 18));
        t[501] = address(new MockERC20("Mock STRK", "STRK", 18));
        t[502] = address(new MockERC20("Mock STX", "STX", 18));
        t[503] = address(new MockERC20("Mock SUI", "SUI", 18));
        t[504] = address(new MockERC20("Mock SUN", "SUN", 18));
        t[505] = address(new MockERC20("Mock SUPER", "SUPER", 18));
        t[506] = address(new MockERC20("Mock S", "S", 18));
        t[507] = address(new MockERC20("Mock SUSHI", "SUSHI", 18));
        t[508] = address(new MockERC20("Mock SWARMS", "SWARMS", 18));
        t[509] = address(new MockERC20("Mock SWCH", "SWCH", 18));
        t[510] = address(new MockERC20("Mock SWEAT", "SWEAT", 18));
        t[511] = address(new MockERC20("Mock SWELL", "SWELL", 18));
        t[512] = address(new MockERC20("Mock SXP", "SXP", 18));
        t[513] = address(new MockERC20("Mock SXT", "SXT", 18));
        t[514] = address(new MockERC20("Mock SYN", "SYN", 18));
        t[515] = address(new MockERC20("Mock SYRUP", "SYRUP", 18));
        t[516] = address(new MockERC20("Mock SYS", "SYS", 18));
        t[517] = address(new MockERC20("Mock TAC", "TAC", 18));
        t[518] = address(new MockERC20("Mock TAG", "TAG", 18));
        t[519] = address(new MockERC20("Mock TAIKO", "TAIKO", 18));
        t[520] = address(new MockERC20("Mock TAO", "TAO", 18));
        t[521] = address(new MockERC20("Mock TCOM", "TCOM", 18));
        t[522] = address(new MockERC20("Mock THE", "THE", 18));
        t[523] = address(new MockERC20("Mock THQ", "THQ", 18));
        t[524] = address(new MockERC20("Mock TIA", "TIA", 18));
    }

    function _deployBatch21(address[] memory t) internal {
        t[525] = address(new MockERC20("Mock TLM", "TLM", 18));
        t[526] = address(new MockERC20("Mock TLOS", "TLOS", 18));
        t[527] = address(new MockERC20("Mock TNSR", "TNSR", 18));
        t[528] = address(new MockERC20("Mock TON", "TON", 18));
        t[529] = address(new MockERC20("Mock TOSHI", "TOSHI", 18));
        t[530] = address(new MockERC20("Mock TOWNS", "TOWNS", 18));
        t[531] = address(new MockERC20("Mock TOWN", "TOWN", 18));
        t[532] = address(new MockERC20("Mock TRADOOR", "TRADOOR", 18));
        t[533] = address(new MockERC20("Mock TRB", "TRB", 18));
        t[534] = address(new MockERC20("Mock TREE", "TREE", 18));
        t[535] = address(new MockERC20("Mock TRIA", "TRIA", 18));
        t[536] = address(new MockERC20("Mock TRUMP", "TRUMP", 18));
        t[537] = address(new MockERC20("Mock TRUST", "TRUST", 18));
        t[538] = address(new MockERC20("Mock TRU", "TRU", 18));
        t[539] = address(new MockERC20("Mock TRX", "TRX", 18));
        t[540] = address(new MockERC20("Mock TURBO", "TURBO", 18));
        t[541] = address(new MockERC20("Mock T", "T", 18));
        t[542] = address(new MockERC20("Mock TUSD", "TUSD", 18));
        t[543] = address(new MockERC20("Mock TUT", "TUT", 18));
        t[544] = address(new MockERC20("Mock TWT", "TWT", 18));
        t[545] = address(new MockERC20("Mock U2U", "U2U", 18));
        t[546] = address(new MockERC20("Mock UAI", "UAI", 18));
        t[547] = address(new MockERC20("Mock UMA", "UMA", 18));
        t[548] = address(new MockERC20("Mock UNI", "UNI", 18));
        t[549] = address(new MockERC20("Mock UPC", "UPC", 18));
    }

    function _deployBatch22(address[] memory t) internal {
        t[550] = address(new MockERC20("Mock USAT", "USAT", 18));
        t[551] = address(new MockERC20("Mock USD1", "USD1", 18));
        t[552] = address(new MockERC20("Mock USDC", "USDC", 18));
        t[553] = address(new MockERC20("Mock USDE", "USDE", 18));
        t[554] = address(new MockERC20("Mock USDGO", "USDGO", 18));
        t[555] = address(new MockERC20("Mock USDS", "USDS", 18));
        t[556] = address(new MockERC20("Mock USTC", "USTC", 18));
        t[557] = address(new MockERC20("Mock USUAL", "USUAL", 18));
        t[558] = address(new MockERC20("Mock US", "US", 18));
        t[559] = address(new MockERC20("Mock UXLINK", "UXLINK", 18));
        t[560] = address(new MockERC20("Mock VANA", "VANA", 18));
        t[561] = address(new MockERC20("Mock VANRY", "VANRY", 18));
        t[562] = address(new MockERC20("Mock VELODROME", "VELODROME", 18));
        t[563] = address(new MockERC20("Mock VELO", "VELO", 18));
        t[564] = address(new MockERC20("Mock VELVET", "VELVET", 18));
        t[565] = address(new MockERC20("Mock VERT", "VERT", 18));
        t[566] = address(new MockERC20("Mock VET", "VET", 18));
        t[567] = address(new MockERC20("Mock VFY", "VFY", 18));
        t[568] = address(new MockERC20("Mock VIC", "VIC", 18));
        t[569] = address(new MockERC20("Mock VINE", "VINE", 18));
        t[570] = address(new MockERC20("Mock VIRTUAL", "VIRTUAL", 18));
        t[571] = address(new MockERC20("Mock VOOI", "VOOI", 18));
        t[572] = address(new MockERC20("Mock VSN", "VSN", 18));
        t[573] = address(new MockERC20("Mock VTHO", "VTHO", 18));
        t[574] = address(new MockERC20("Mock WAI", "WAI", 18));
    }

    function _deployBatch23(address[] memory t) internal {
        t[575] = address(new MockERC20("Mock WAL", "WAL", 18));
        t[576] = address(new MockERC20("Mock WARD", "WARD", 18));
        t[577] = address(new MockERC20("Mock WAVES", "WAVES", 18));
        t[578] = address(new MockERC20("Mock WAXP", "WAXP", 18));
        t[579] = address(new MockERC20("Mock WBTC", "WBTC", 18));
        t[580] = address(new MockERC20("Mock WCT", "WCT", 18));
        t[581] = address(new MockERC20("Mock WEETH", "WEETH", 18));
        t[582] = address(new MockERC20("Mock WEMIX", "WEMIX", 18));
        t[583] = address(new MockERC20("Mock WIF", "WIF", 18));
        t[584] = address(new MockERC20("Mock WIN", "WIN", 18));
        t[585] = address(new MockERC20("Mock WLD", "WLD", 18));
        t[586] = address(new MockERC20("Mock WLFI", "WLFI", 18));
        t[587] = address(new MockERC20("Mock WOO", "WOO", 18));
        t[588] = address(new MockERC20("Mock W", "W", 18));
        t[589] = address(new MockERC20("Mock WUSD", "WUSD", 18));
        t[590] = address(new MockERC20("Mock XAI", "XAI", 18));
        t[591] = address(new MockERC20("Mock XAUT", "XAUT", 18));
        t[592] = address(new MockERC20("Mock XCX", "XCX", 18));
        t[593] = address(new MockERC20("Mock XDC", "XDC", 18));
        t[594] = address(new MockERC20("Mock XION", "XION", 18));
        t[595] = address(new MockERC20("Mock XLM", "XLM", 18));
        t[596] = address(new MockERC20("Mock XPL", "XPL", 18));
        t[597] = address(new MockERC20("Mock XRP", "XRP", 18));
        t[598] = address(new MockERC20("Mock XTER", "XTER", 18));
        t[599] = address(new MockERC20("Mock XTZ", "XTZ", 18));
    }

    function _deployBatch24(address[] memory t) internal {
        t[600] = address(new MockERC20("Mock YB", "YB", 18));
        t[601] = address(new MockERC20("Mock YFI", "YFI", 18));
        t[602] = address(new MockERC20("Mock YGG", "YGG", 18));
        t[603] = address(new MockERC20("Mock ZAMA", "ZAMA", 18));
        t[604] = address(new MockERC20("Mock ZBCN", "ZBCN", 18));
        t[605] = address(new MockERC20("Mock ZBT", "ZBT", 18));
        t[606] = address(new MockERC20("Mock ZEC", "ZEC", 18));
        t[607] = address(new MockERC20("Mock ZENT", "ZENT", 18));
        t[608] = address(new MockERC20("Mock ZEN", "ZEN", 18));
        t[609] = address(new MockERC20("Mock ZEREBRO", "ZEREBRO", 18));
        t[610] = address(new MockERC20("Mock ZETA", "ZETA", 18));
        t[611] = address(new MockERC20("Mock ZIG", "ZIG", 18));
        t[612] = address(new MockERC20("Mock ZIL", "ZIL", 18));
        t[613] = address(new MockERC20("Mock ZKC", "ZKC", 18));
        t[614] = address(new MockERC20("Mock ZKJ", "ZKJ", 18));
        t[615] = address(new MockERC20("Mock ZKL", "ZKL", 18));
        t[616] = address(new MockERC20("Mock ZK", "ZK", 18));
        t[617] = address(new MockERC20("Mock ZORA", "ZORA", 18));
        t[618] = address(new MockERC20("Mock ZRO", "ZRO", 18));
        t[619] = address(new MockERC20("Mock ZRX", "ZRX", 18));
        t[620] = address(new MockERC20("Mock ZTC", "ZTC", 18));
    }

    function _export(address[] memory t) internal {
        string memory out = "";
        for (uint256 i = 0; i < N; i++) {
            out = string.concat(out, vm.toString(i), ",", vm.toString(t[i]), "\n");
        }
        vm.writeFile("../data/all-token-addresses.csv", out);
        console.log("  Token addresses written to data/all-token-addresses.csv");
    }

}