export type LogoEntry = { name: string; file: string };
// file is relative to the public/ folder, for use with staticFile()
export const LOGOS_BY_VENUE: Record<string, LogoEntry[]> = {
  "Index funds": [
    { name: "Vanguard", file: "retail-pnl/logos/index-funds/vanguard.png" },
    { name: "iShares", file: "retail-pnl/logos/index-funds/ishares.png" },
    { name: "State Street", file: "retail-pnl/logos/index-funds/state-street.png" },
    { name: "Fidelity", file: "retail-pnl/logos/index-funds/fidelity.png" },
    { name: "Charles Schwab", file: "retail-pnl/logos/index-funds/charles-schwab.png" },
    { name: "Invesco", file: "retail-pnl/logos/index-funds/invesco.png" },
  ],
  "Robinhood stocks": [
    { name: "Robinhood", file: "retail-pnl/logos/robinhood-stocks/robinhood.png" },
    { name: "Webull", file: "retail-pnl/logos/robinhood-stocks/webull.png" },
    { name: "E*TRADE", file: "retail-pnl/logos/robinhood-stocks/etrade.png" },
    { name: "Fidelity", file: "retail-pnl/logos/robinhood-stocks/fidelity.png" },
    { name: "Charles Schwab", file: "retail-pnl/logos/robinhood-stocks/charles-schwab.png" },
    { name: "SoFi", file: "retail-pnl/logos/robinhood-stocks/sofi.png" },
  ],
  "Crypto spot": [
    { name: "Coinbase", file: "retail-pnl/logos/crypto-spot/coinbase.png" },
    { name: "Binance", file: "retail-pnl/logos/crypto-spot/binance.png" },
    { name: "Kraken", file: "retail-pnl/logos/crypto-spot/kraken.png" },
    { name: "OKX", file: "retail-pnl/logos/crypto-spot/okx.png" },
    { name: "Bybit", file: "retail-pnl/logos/crypto-spot/bybit.png" },
    { name: "Crypto.com", file: "retail-pnl/logos/crypto-spot/crypto-com.png" },
  ],
  "US options": [
    { name: "Robinhood", file: "retail-pnl/logos/us-options/robinhood.png" },
    { name: "tastytrade", file: "retail-pnl/logos/us-options/tastytrade.png" },
    { name: "Interactive Brokers", file: "retail-pnl/logos/us-options/interactive-brokers.png" },
    { name: "Webull", file: "retail-pnl/logos/us-options/webull.png" },
    { name: "Charles Schwab", file: "retail-pnl/logos/us-options/charles-schwab.png" },
    { name: "E*TRADE", file: "retail-pnl/logos/us-options/etrade.png" },
  ],
  "Crypto perps": [
    { name: "Binance", file: "retail-pnl/logos/crypto-perps/binance.png" },
    { name: "Hyperliquid", file: "retail-pnl/logos/crypto-perps/hyperliquid.png" },
    { name: "Bybit", file: "retail-pnl/logos/crypto-perps/bybit.png" },
    { name: "OKX", file: "retail-pnl/logos/crypto-perps/okx.png" },
    { name: "Bitget", file: "retail-pnl/logos/crypto-perps/bitget.png" },
    { name: "dYdX", file: "retail-pnl/logos/crypto-perps/dydx.png" },
  ],
  "FX / CFDs": [
    { name: "IG", file: "retail-pnl/logos/fx-cfds/ig.png" },
    { name: "CMC Markets", file: "retail-pnl/logos/fx-cfds/cmc-markets.png" },
    { name: "Plus500", file: "retail-pnl/logos/fx-cfds/plus500.png" },
    { name: "eToro", file: "retail-pnl/logos/fx-cfds/etoro.png" },
    { name: "Saxo Bank", file: "retail-pnl/logos/fx-cfds/saxo-bank.png" },
    { name: "OANDA", file: "retail-pnl/logos/fx-cfds/oanda.png" },
  ],
  "Prediction markets": [
    { name: "Polymarket", file: "retail-pnl/logos/prediction-markets/polymarket.png" },
    { name: "Kalshi", file: "retail-pnl/logos/prediction-markets/kalshi.png" },
    { name: "PredictIt", file: "retail-pnl/logos/prediction-markets/predictit.png" },
    { name: "Manifold", file: "retail-pnl/logos/prediction-markets/manifold.png" },
    { name: "Metaculus", file: "retail-pnl/logos/prediction-markets/metaculus.png" },
    { name: "Limitless", file: "retail-pnl/logos/prediction-markets/limitless.png" },
  ],
  "Sports betting": [
    { name: "FanDuel", file: "retail-pnl/logos/sports-betting/fanduel.png" },
    { name: "DraftKings", file: "retail-pnl/logos/sports-betting/draftkings.png" },
    { name: "BetMGM", file: "retail-pnl/logos/sports-betting/betmgm.png" },
    { name: "Caesars", file: "retail-pnl/logos/sports-betting/caesars.png" },
    { name: "ESPN Bet", file: "retail-pnl/logos/sports-betting/espn-bet.png" },
    { name: "Fanatics", file: "retail-pnl/logos/sports-betting/fanatics.png" },
  ],
  "Memecoins": [
    { name: "Pump.fun", file: "retail-pnl/logos/memecoins/pump-fun.png" },
    { name: "Raydium", file: "retail-pnl/logos/memecoins/raydium.png" },
    { name: "Jupiter", file: "retail-pnl/logos/memecoins/jupiter.png" },
    { name: "DexScreener", file: "retail-pnl/logos/memecoins/dexscreener.png" },
    { name: "Birdeye", file: "retail-pnl/logos/memecoins/birdeye.png" },
    { name: "BullX", file: "retail-pnl/logos/memecoins/bullx.png" },
  ],
  "Sweeps casinos": [
    { name: "Stake.us", file: "retail-pnl/logos/sweeps-casinos/stake-us.png" },
    { name: "Chumba Casino", file: "retail-pnl/logos/sweeps-casinos/chumba-casino.png" },
    { name: "LuckyLand Slots", file: "retail-pnl/logos/sweeps-casinos/luckyland-slots.png" },
    { name: "McLuck", file: "retail-pnl/logos/sweeps-casinos/mcluck.png" },
    { name: "Pulsz", file: "retail-pnl/logos/sweeps-casinos/pulsz.png" },
    { name: "High 5 Casino", file: "retail-pnl/logos/sweeps-casinos/high-5-casino.png" },
  ],
  "Online casinos": [
    { name: "BetMGM", file: "retail-pnl/logos/online-casinos/betmgm.png" },
    { name: "DraftKings", file: "retail-pnl/logos/online-casinos/draftkings.png" },
    { name: "Caesars Palace Online", file: "retail-pnl/logos/online-casinos/caesars.png" },
    { name: "FanDuel Casino", file: "retail-pnl/logos/online-casinos/fanduel.png" },
    { name: "BetRivers", file: "retail-pnl/logos/online-casinos/betrivers.png" },
    { name: "Golden Nugget", file: "retail-pnl/logos/online-casinos/golden-nugget.png" },
  ],
  "Online poker": [
    { name: "PokerStars", file: "retail-pnl/logos/online-poker/pokerstars.png" },
    { name: "GGPoker", file: "retail-pnl/logos/online-poker/ggpoker.png" },
    { name: "partypoker", file: "retail-pnl/logos/online-poker/partypoker.png" },
    { name: "WSOP", file: "retail-pnl/logos/online-poker/wsop.png" },
    { name: "888poker", file: "retail-pnl/logos/online-poker/888poker.png" },
    { name: "Americas Cardroom", file: "retail-pnl/logos/online-poker/americas-cardroom.png" },
  ],
  "Online lottery": [
    { name: "Jackpocket", file: "retail-pnl/logos/online-lottery/jackpocket.png" },
    { name: "theLotter", file: "retail-pnl/logos/online-lottery/thelotter.png" },
    { name: "Lotto.com", file: "retail-pnl/logos/online-lottery/lotto-com.png" },
    { name: "Jackpot.com", file: "retail-pnl/logos/online-lottery/jackpot-com.png" },
    { name: "Powerball", file: "retail-pnl/logos/online-lottery/powerball.png" },
    { name: "Mega Millions", file: "retail-pnl/logos/online-lottery/mega-millions.png" },
  ],
};
