// AUTO-GENERATED by scripts/winners-daily/fetch-flows.mjs — do not edit by hand.
// 2026-05-27 13:19 UTC  ·  source: DefiLlama /protocols (free), 7-day TVL change.
import type { FlowRow } from "./FlowReel";

export const ASOF = "2026-05-27 13:19 UTC";

export const LIVE: Record<string, { asof: string; rows: FlowRow[] }> = {
  PerpsFlowReel: {
    asof: ASOF,
    rows: [
      { id: "jupiter-perpetual-exchange", name: "Jupiter Perps", now: 656164157, prior: 675932947 },
      { id: "hyperliquid-hlp", name: "Hyperliquid HLP", now: 356836098, prior: 381510926 },
      { id: "gmx-v2-perps", name: "GMX V2", now: 195910674, prior: 202216152 },
      { id: "extended", name: "Extended", now: 151090316, prior: 152017658 },
      { id: "derive-v2", name: "Derive", now: 131951356, prior: 124715966 },
      { id: "dydx-v4", name: "dYdX", now: 100116341, prior: 98922351 },
      { id: "ostium", name: "Ostium", now: 43945959, prior: 50010087 },
      { id: "avantis", name: "Avantis", now: 45669767, prior: 45869965 },
      { id: "decibel", name: "Decibel", now: 41873104, prior: 42258482 },
      { id: "gmtrade", name: "GMTrade", now: 43286557, prior: 42462084 },
    ],
  },
  PredictionMarketsFlowReel: {
    asof: ASOF,
    rows: [
      { id: "polymarket-international", name: "Polymarket", now: 460800392, prior: 454722772 },
      { id: "predict-fun", name: "Predict.fun", now: 14359499, prior: 16051169 },
      { id: "opinion", name: "Opinion", now: 7258095, prior: 7652145 },
      { id: "sport.fun", name: "Sport.fun", now: 3669709, prior: 3641864 },
      { id: "gnosis-protocol-v1", name: "Gnosis Protocol", now: 2213919, prior: 2255191 },
      { id: "augur", name: "Augur", now: 1657594, prior: 1696985 },
      { id: "seer", name: "Seer", now: 1538844, prior: 1519831 },
      { id: "overtime", name: "Overtime", now: 1234552, prior: 1453144 },
      { id: "liquidity-house", name: "Liquidity House", now: 1429497, prior: 1411209 },
    ],
  },
  PrivacyFlowReel: {
    asof: ASOF,
    rows: [
      { id: "tornado-cash", name: "Tornado Cash", now: 516163558, prior: 521593741 },
      { id: "railgun", name: "Railgun", now: 92602346, prior: 93787451 },
      { id: "zama", name: "Zama", now: 31341990, prior: 32327210 },
      { id: "privacy-pools", name: "Privacy Pools", now: 6726196, prior: 6732977 },
      { id: "aztec-connect", name: "Aztec Connect", now: 5288873, prior: 5400355 },
      { id: "privacy-cash", name: "Privacy Cash", now: 2333617, prior: 2542447 },
      { id: "namada-shielded-pools", name: "Namada", now: 669778, prior: 615534 },
      { id: "hinkal", name: "Hinkal", now: 619995, prior: 634235 },
      { id: "zkbob", name: "zkBob", now: 242516, prior: 255989 },
      { id: "0x0.ai", name: "0x0.ai", now: 216940, prior: 222221 },
    ],
  },
  RwaFlowReel: {
    asof: ASOF,
    rows: [
      { id: "tether-gold", name: "Tether Gold", now: 3169942135, prior: 3201795622 },
      { id: "blackrock-buidl", name: "BlackRock BUIDL", now: 3030707593, prior: 3130373014 },
      { id: "circle-usyc", name: "Circle USYC", now: 2986583667, prior: 2975652512 },
      { id: "ondo-yield-assets", name: "Ondo Yield", now: 2677223377, prior: 2676895719 },
      { id: "paxos-gold", name: "Paxos Gold", now: 2091000576, prior: 2111179744 },
      { id: "centrifuge-protocol", name: "Centrifuge", now: 1430814713, prior: 1526410715 },
      { id: "spiko", name: "Spiko", now: 1227772045, prior: 1235104028 },
      { id: "ethena-usdtb", name: "Ethena USDtb", now: 1089119057, prior: 1076109711 },
      { id: "ondo-global-markets", name: "Ondo Global Markets", now: 1145187575, prior: 1024875104 },
      { id: "anemoy-capital", name: "Anemoy", now: 914269696, prior: 1013781396 },
    ],
  },
  LendingProtocolsFlowReel: {
    asof: ASOF,
    rows: [
      { id: "aave-v3", name: "Aave V3", now: 13675366440, prior: 14103531926 },
      { id: "morpho-blue", name: "Morpho", now: 7405435473, prior: 7385641114 },
      { id: "justlend", name: "JustLend", now: 3583266960, prior: 3535959986 },
      { id: "sparklend", name: "Spark", now: 3027807200, prior: 3207015786 },
      { id: "maple", name: "Maple", now: 2046253427, prior: 2046398741 },
      { id: "kamino-lend", name: "Kamino", now: 1343844513, prior: 1623328154 },
      { id: "jupiter-lend", name: "Jupiter Lend", now: 969990625, prior: 1220255675 },
      { id: "compound-v3", name: "Compound V3", now: 1217683005, prior: 1230470449 },
      { id: "venus-core-pool", name: "Venus", now: 1158016059, prior: 1175499992 },
      { id: "fluid-lending", name: "Fluid", now: 845404015, prior: 794518860 },
    ],
  },
};
