services:
  itp-trader-bot:
    image: itp-trader-bot:latest
    container_name: itp-trader-bot
    restart: always
    environment:
      - LOG_LEVEL=info
      - DATA_NODE_URL=https://generalmarket.io/api/dn
      - HEALTH_PORT=8090
      - KEYS_PATH=/data/keys.json
      - KEYRING_SIZE=5
      - EXTRA_MORPHO_MARKETS=0x736b6e07edd80ab0ce7e4657ea4bb1eafb4cb9523fccf38bb2bbd65bea143fc5
    volumes:
      - /opt/itp-trader-bot/data:/data
    ports:
      - "127.0.0.1:8090:8090"
