#!/bin/bash
# Deploy ITPs - 2-phase deployment (tokens handled by deploy-all-tokens.py)
# Generated by scripts/deploy-107-itps.py
set -e
cd "$(dirname "$0")/.."

RPC="${RPC_URL:-http://localhost:8545}"
echo "=== Phase 1: Create 96 ITPs ==="
cd contracts
forge script script/Deploy107ITPs_Create.s.sol:Deploy107ITPs_Create \
    --rpc-url "$RPC" --broadcast --slow -vv
cd ..
echo ""

echo "=== Phase 2: Deploy 96 ITP vaults ==="
cd contracts
forge script script/Deploy107ITPs_Vaults.s.sol:Deploy107ITPs_Vaults \
    --rpc-url "$RPC" --broadcast --slow -vv
cd ..
echo ""

echo "=== ALL DONE ==="
