#!/usr/bin/env python3
"""
Generate DeployAllTokens.s.sol from assets.json.

Reads all Bitget-listed tokens, generates a Forge script that:
  - Deploys 621 MockERC20 tokens (one per unique symbol)
  - Funds MockBitgetVault with 1M of each
  - Exports data/all-token-addresses.csv (index,address)

Also writes data/all-token-symbols.json ({symbol: index}) for deploy-107-itps.py.
"""

import json
import os
import re
import math

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_PATH = os.path.join(REPO_ROOT, "assets.json")
SOL_OUTPUT = os.path.join(REPO_ROOT, "contracts/script/DeployAllTokens.s.sol")
SYMBOLS_JSON = os.path.join(REPO_ROOT, "data/all-token-symbols.json")

BATCH_SIZE = 25


def load_symbols():
    """Extract unique symbols from assets.json, stripping USDT/USDC suffix."""
    assets = json.load(open(ASSETS_PATH))
    seen = set()
    symbols = []
    for a in assets:
        sym = re.sub(r"(USDT|USDC)$", "", a["bitget"])
        if sym and sym not in seen:
            seen.add(sym)
            symbols.append(sym)
    return symbols


def generate_sol(symbols):
    N = len(symbols)
    num_batches = math.ceil(N / BATCH_SIZE)

    L = []
    a = L.append

    a("// SPDX-License-Identifier: MIT")
    a("// AUTO-GENERATED by scripts/deploy-all-tokens.py — DO NOT EDIT")
    a("pragma solidity ^0.8.20;")
    a("")
    a('import "forge-std/Script.sol";')
    a('import "forge-std/console.sol";')
    a('import "../src/mocks/MockERC20.sol";')
    a("")
    a(f"/// @title DeployAllTokens - Deploy {N} Bitget tokens + fund vault")
    a("contract DeployAllTokens is Script {")
    a(f"    uint256 constant N = {N};")
    a("    uint256 constant FUND = 1_000_000 * 1e18;")
    a("")

    # run()
    a("    function run() external {")
    a('        uint256 pk = vm.envOr("PRIVATE_KEY", uint256(0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d));')
    a('        address bv = vm.envAddress("MOCK_BITGET_VAULT");')
    a("")
    a("        address[] memory t = new address[](N);")
    a("")
    a("        vm.startBroadcast(pk);")
    for bi in range(num_batches):
        a(f"        _deployBatch{bi}(t);")
    a("        // Fund vault with 1M of each token")
    a("        for (uint256 i = 0; i < N; i++) MockERC20(t[i]).mint(bv, FUND);")
    a("        vm.stopBroadcast();")
    a("")
    a("        _export(t);")
    a(f'        console.log("Done: {N} tokens deployed, vault funded");')
    a("    }")
    a("")

    # Batch functions
    for bi in range(num_batches):
        start = bi * BATCH_SIZE
        end = min(start + BATCH_SIZE, N)
        batch = symbols[start:end]
        a(f"    function _deployBatch{bi}(address[] memory t) internal {{")
        for j, sym in enumerate(batch):
            idx = start + j
            a(f'        t[{idx}] = address(new MockERC20("Mock {sym}", "{sym}", 18));')
        a("    }")
        a("")

    # Export CSV
    a("    function _export(address[] memory t) internal {")
    a('        string memory out = "";')
    a("        for (uint256 i = 0; i < N; i++) {")
    a('            out = string.concat(out, vm.toString(i), ",", vm.toString(t[i]), "\\n");')
    a("        }")
    a('        vm.writeFile("../data/all-token-addresses.csv", out);')
    a('        console.log("  Token addresses written to data/all-token-addresses.csv");')
    a("    }")
    a("")
    a("}")

    return "\n".join(L)


def main():
    symbols = load_symbols()
    print(f"Loaded {len(symbols)} unique symbols from assets.json")

    # Generate Solidity
    sol = generate_sol(symbols)
    with open(SOL_OUTPUT, "w") as f:
        f.write(sol)
    print(f"Wrote {SOL_OUTPUT} ({sol.count(chr(10))} lines)")

    # Write symbol index JSON
    sym_idx = {s: i for i, s in enumerate(symbols)}
    with open(SYMBOLS_JSON, "w") as f:
        json.dump(sym_idx, f, indent=2)
    print(f"Wrote {SYMBOLS_JSON} ({len(sym_idx)} symbols)")


if __name__ == "__main__":
    main()
