#!/usr/bin/env bash
# Extract ABI JSON from Forge build artifacts into committed files.
# Run after contract changes: ./scripts/extract-abis.sh
# CI check mode: ./scripts/extract-abis.sh --check

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"

# Format: "ContractName:InterfaceName" — tries Interface artifact first,
# then falls back to implementation artifact.
# If no colon, uses ContractName for both.
CONTRACTS=(
  "Vision:IVision"
  "Index:IIndex"
  "Investment:Investment"
  "OracleRegistry:IOracleRegistry"
  "BridgeProxy:IBridgeProxy"
  "BridgedItpFactory:IBridgedItpFactory"
  "SettlementBridgeCustody:SettlementBridgeCustody"
  "L3BridgeCustody:L3BridgeCustody"
  "MockBitgetVault:MockBitgetVault"
  "ERC20:ERC20"
  # Add more as needed
)

ABI_DIR="$ROOT/common/src/adapters/abi"
TS_DIR="$ROOT/frontend/lib/contracts/generated"

mkdir -p "$ABI_DIR" "$TS_DIR"

count=0

for entry in "${CONTRACTS[@]}"; do
  impl="${entry%%:*}"
  iface="${entry##*:}"

  # Try interface artifact first, then implementation
  src="$ROOT/contracts/out/${iface}.sol/${iface}.json"
  if [ ! -f "$src" ]; then
    src="$ROOT/contracts/out/${impl}.sol/${impl}.json"
  fi

  if [ ! -f "$src" ]; then
    echo "WARN: no artifact for $entry — skipping"
    continue
  fi

  # Convert PascalCase to snake_case (portable — no GNU sed \L needed)
  snake=$(echo "$impl" | sed 's/\([a-z0-9]\)\([A-Z]\)/\1_\2/g' | sed 's/\([A-Z]\)\([A-Z][a-z]\)/\1_\2/g' | tr '[:upper:]' '[:lower:]')

  json_out="$ABI_DIR/${snake}_abi.json"
  ts_out="$TS_DIR/${snake}-abi.ts"

  # Extract the ABI array
  jq '.abi' "$src" > "$json_out"

  # Generate TS const export
  {
    echo "// AUTO-GENERATED by scripts/extract-abis.sh — do not edit"
    echo "export const ${impl}ABI = $(jq -c '.abi' "$src") as const;"
  } > "$ts_out"

  count=$((count + 1))
done

# --check mode: verify generated files match committed
if [ "${1:-}" = "--check" ]; then
  if git diff --quiet -- "$ABI_DIR" "$TS_DIR"; then
    echo "ABIs up to date."
  else
    echo "ERROR: ABIs out of date. Run ./scripts/extract-abis.sh"
    git diff --stat -- "$ABI_DIR" "$TS_DIR"
    exit 1
  fi
fi

echo "Extracted $count ABIs."
