#!/bin/bash
# Sync deployment addresses to all services (frontend, issuers, AP)
# Run after any contract deployment

set -e

DEPLOYMENT_FILE="${1:-deployments/full-e2e-deployment.json}"
FRONTEND_DIR="/Users/maxguillabert/Desktop/mar26/frontend"
INDEX_DIR="/Users/maxguillabert/Desktop/index"

if [ ! -f "$DEPLOYMENT_FILE" ]; then
    echo "Error: Deployment file not found: $DEPLOYMENT_FILE"
    exit 1
fi

echo "=== Syncing deployment from $DEPLOYMENT_FILE ==="

# Extract addresses from deployment JSON
CHAIN_ID=$(jq -r '.chainId' "$DEPLOYMENT_FILE")
RPC_URL=$(jq -r '.rpc // "https://index.rpc.zeeve.net"' "$DEPLOYMENT_FILE")
GOVERNANCE=$(jq -r '.Governance // ""' "$DEPLOYMENT_FILE")
ISSUER_REGISTRY=$(jq -r '.IssuerRegistry // ""' "$DEPLOYMENT_FILE")
ASSET_PAIR_REGISTRY=$(jq -r '.AssetPairRegistry // ""' "$DEPLOYMENT_FILE")
INDEX_CONTRACT=$(jq -r '.Index // ""' "$DEPLOYMENT_FILE")
BRIDGE_PROXY=$(jq -r '.BridgeProxy // ""' "$DEPLOYMENT_FILE")
BRIDGED_ITP_FACTORY=$(jq -r '.BridgedItpFactory // ""' "$DEPLOYMENT_FILE")
MOCK_BITGET_VAULT=$(jq -r '.MockBitgetVault // ""' "$DEPLOYMENT_FILE")

echo "Chain ID: $CHAIN_ID"
echo "RPC: $RPC_URL"
echo ""
echo "Contracts:"
echo "  Governance: $GOVERNANCE"
echo "  IssuerRegistry: $ISSUER_REGISTRY"
echo "  AssetPairRegistry: $ASSET_PAIR_REGISTRY"
echo "  Index: $INDEX_CONTRACT"
echo "  BridgeProxy: $BRIDGE_PROXY"
echo "  BridgedItpFactory: $BRIDGED_ITP_FACTORY"
echo "  MockBitgetVault: $MOCK_BITGET_VAULT"
echo ""

# 1. Update Frontend .env.local
if [ -d "$FRONTEND_DIR" ]; then
    echo "=== Updating Frontend .env.local ==="
    cat > "$FRONTEND_DIR/.env.local" << EOF
# Auto-generated by sync-deployment.sh - DO NOT EDIT MANUALLY
# Source: $DEPLOYMENT_FILE
# Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID
NEXT_PUBLIC_RPC_URL=$RPC_URL

# Index Protocol Contracts
NEXT_PUBLIC_GOVERNANCE_ADDRESS=$GOVERNANCE
NEXT_PUBLIC_ISSUER_REGISTRY_ADDRESS=$ISSUER_REGISTRY
NEXT_PUBLIC_ASSET_PAIR_REGISTRY_ADDRESS=$ASSET_PAIR_REGISTRY
NEXT_PUBLIC_INDEX_ADDRESS=$INDEX_CONTRACT
NEXT_PUBLIC_BRIDGE_PROXY_ADDRESS=$BRIDGE_PROXY
NEXT_PUBLIC_BRIDGED_ITP_FACTORY_ADDRESS=$BRIDGED_ITP_FACTORY
NEXT_PUBLIC_MOCK_BITGET_VAULT_ADDRESS=$MOCK_BITGET_VAULT

# WalletConnect
NEXT_PUBLIC_WC_PROJECT_ID=010e9f68ffff0f6f91d6840a512a747a
EOF
    echo "Frontend .env.local updated"
fi

# 2. Create shared deployment JSON for Rust services
echo "=== Creating Rust services deployment config ==="
cat > "$INDEX_DIR/deployments/active-deployment.json" << EOF
{
  "chainId": $CHAIN_ID,
  "rpc": "$RPC_URL",
  "contracts": {
    "Governance": "$GOVERNANCE",
    "IssuerRegistry": "$ISSUER_REGISTRY",
    "AssetPairRegistry": "$ASSET_PAIR_REGISTRY",
    "Index": "$INDEX_CONTRACT",
    "BridgeProxy": "$BRIDGE_PROXY",
    "BridgedItpFactory": "$BRIDGED_ITP_FACTORY",
    "MockBitgetVault": "$MOCK_BITGET_VAULT"
  },
  "updatedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
echo "Created deployments/active-deployment.json"

# 3. Create issuer env template
echo "=== Creating Issuer environment template ==="
cat > "$INDEX_DIR/issuer.env" << EOF
# Issuer Node Environment - Auto-generated by sync-deployment.sh
# Source: $DEPLOYMENT_FILE
# Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Chain Configuration
ISSUER_RPC_URL=$RPC_URL

# Contract Addresses
ISSUER_INDEX_ADDRESS=$INDEX_CONTRACT
ISSUER_GOVERNANCE_ADDRESS=$GOVERNANCE
ISSUER_ISSUER_REGISTRY_ADDRESS=$ISSUER_REGISTRY
ISSUER_BRIDGE_PROXY_ADDRESS=$BRIDGE_PROXY
ISSUER_BITGET_VAULT=$MOCK_BITGET_VAULT

# Arbitrum (using L3 as mock Arbitrum for E2E)
ISSUER_ARBITRUM_RPC_URL=$RPC_URL
ISSUER_ARBITRUM_CHAIN_ID=$CHAIN_ID

# Node-specific (set per instance)
# ISSUER_NODE_ID=1
# ISSUER_PRIVATE_KEY=0x...
# ISSUER_PEERS=127.0.0.1:9002,127.0.0.1:9003
EOF
echo "Created issuer.env"

# 4. Create AP env template
echo "=== Creating AP environment template ==="
cat > "$INDEX_DIR/ap.env" << EOF
# AP Node Environment - Auto-generated by sync-deployment.sh
# Source: $DEPLOYMENT_FILE
# Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Chain Configuration
AP_RPC_URL=$RPC_URL

# Contract Addresses
AP_INDEX_ADDRESS=$INDEX_CONTRACT
AP_BITGET_VAULT=$MOCK_BITGET_VAULT

# AP-specific
# AP_PRIVATE_KEY=0x...
# AP_PORT=9100
EOF
echo "Created ap.env"

echo ""
echo "=== Sync Complete ==="
echo ""
echo "To start services with the new config:"
echo "  Issuers: source issuer.env && ./scripts/start-issuers.sh"
echo "  AP:      source ap.env && ./scripts/start-ap.sh"
echo "  Frontend: cd $FRONTEND_DIR && npm run dev"
