[package]
name = "issuer"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "issuer"
path = "src/main.rs"

[[bin]]
name = "bls-tool"
path = "src/bin/bls_tool.rs"

[dependencies]
common = { path = "../common" }
tokio.workspace = true
async-trait.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
toml = "0.8"
chrono.workspace = true
thiserror.workspace = true
ethers.workspace = true
futures.workspace = true
rust_decimal.workspace = true
dashmap = "5"
hex = "0.4"
rmp-serde.workspace = true
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pemfile = "2"
async-stream = "0.3"
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

[dev-dependencies]
tempfile = "3"
wiremock = "0.6"
