// Maps sourceId → local looping b-roll mp4 in /public/source-video/.
// When a mapping exists, SourceCard plays it behind the logo as ambient motion.
// All clips are 360p, CC0 (Mixkit). Sources without a mapping fall back to
// their solid brand color.
export const SOURCE_BROLLS: Record<string, string> = {
  // Finance
  coingecko: '/source-video/coingecko.mp4',
  pumpfun: '/source-video/pumpfun.mp4',
  defillama: '/source-video/defillama.mp4',
  finnhub: '/source-video/finnhub.mp4',
  nasdaq: '/source-video/nasdaq.mp4',
  zillow: '/source-video/zillow.mp4',
  polymarket: '/source-video/polymarket.mp4',
  bchain: '/source-video/bchain.mp4',
  yahoo_drinks: '/source-video/yahoo_drinks.mp4',
  twse: '/source-video/twse.mp4',
  sec: '/source-video/sec.mp4',
  finra: '/source-video/finra.mp4',
  finra_short_vol: '/source-video/finra.mp4',
  futures: '/source-video/futures.mp4',
  opec: '/source-video/futures.mp4',

  // Economic & regulatory
  fred: '/source-video/fred.mp4',
  treasury: '/source-video/fred.mp4',
  ecb: '/source-video/fred.mp4',
  boe: '/source-video/fred.mp4',
  worldbank: '/source-video/worldbank.mp4',
  imf: '/source-video/worldbank.mp4',
  bls: '/source-video/bls.mp4',
  adzuna: '/source-video/adzuna.mp4',
  usa_spending: '/source-video/usa_spending.mp4',
  congress: '/source-video/usa_spending.mp4',
  cftc: '/source-video/cftc.mp4',
  courtlistener: '/source-video/courtlistener.mp4',

  // Tech & academic
  github: '/source-video/github.mp4',
  npm: '/source-video/npm.mp4',
  pypi: '/source-video/pypi.mp4',
  crates_io: '/source-video/crates_io.mp4',
  stackexchange: '/source-video/stackexchange.mp4',
  hackernews: '/source-video/hackernews.mp4',
  fourchan: '/source-video/fourchan.mp4',
  cloudflare: '/source-video/cloudflare.mp4',
  openalex: '/source-video/openalex.mp4',
  crossref: '/source-video/openalex.mp4',
  pubmed: '/source-video/pubmed.mp4',
  ioda: '/source-video/ioda.mp4',

  // Entertainment
  twitch: '/source-video/twitch-broll.mp4',
  tmdb: '/source-video/tmdb.mp4',
  lastfm: '/source-video/lastfm.mp4',
  steam: '/source-video/steam.mp4',
  anilist: '/source-video/anilist.mp4',
  reddit: '/source-video/reddit.mp4',
  chaturbate: '/source-video/tubes.mp4',
  tubes: '/source-video/tubes.mp4',
  pandascore: '/source-video/pandascore.mp4',
  queue_times: '/source-video/queue_times.mp4',
  sports: '/source-video/sports.mp4',
  bgg: '/source-video/bgg.mp4',
  lichess: '/source-video/lichess.mp4',
  backpacktf: '/source-video/polymarket.mp4',
  mcbroken: '/source-video/mcbroken.mp4',
  bestbuy: '/source-video/bestbuy.mp4',

  // Geophysical
  weather: '/source-video/weather.mp4',
  weather_alerts: '/source-video/weather_alerts.mp4',
  openmeteo: '/source-video/openmeteo.mp4',
  airnow: '/source-video/futures.mp4',
  volcano: '/source-video/volcano.mp4',
  wildfire: '/source-video/wildfire.mp4',
  epidemic: '/source-video/epidemic.mp4',
  earthquake: '/source-video/earthquake.mp4',
  power_outages: '/source-video/power_outages.mp4',
  nrc_nuclear: '/source-video/nrc_nuclear.mp4',
  usgs_water: '/source-video/usgs_water.mp4',
  nwps: '/source-video/usgs_water.mp4',
  ndbc: '/source-video/ndbc.mp4',
  noaa_tides: '/source-video/ndbc.mp4',
  noaa_met: '/source-video/ndbc.mp4',

  // Transport
  flights: '/source-video/flights.mp4',
  ryanair: '/source-video/flights.mp4',
  faa_delays: '/source-video/flights.mp4',
  mta_subway: '/source-video/mta_subway.mp4',
  paris_metro: '/source-video/mta_subway.mp4',
  tfl_tube: '/source-video/mta_subway.mp4',
  gtfs_rt: '/source-video/mta_subway.mp4',
  db_trains: '/source-video/db_trains.mp4',
  citybikes: '/source-video/citybikes.mp4',
  aisstream: '/source-video/aisstream.mp4',
  maritime: '/source-video/aisstream.mp4',
  tomtom_traffic: '/source-video/nyc311.mp4',
  nyc311: '/source-video/nyc311.mp4',
  tomtom_evcharge: '/source-video/tomtom_evcharge.mp4',
  cbp_border: '/source-video/cbp_border.mp4',

  // Nature & space
  ebird: '/source-video/ebird.mp4',
  animals: '/source-video/animals.mp4',
  movebank: '/source-video/movebank.mp4',
  shelter: '/source-video/shelter.mp4',
  spaceweather: '/source-video/spaceweather.mp4',
  iss: '/source-video/iss.mp4',
  mil_aircraft: '/source-video/mil_aircraft.mp4',
}
