#!/bin/bash
# verify-scene-01.sh — Verify scene 01 only (faster than full video)
# Auto-generated by split-scenes.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VIDEO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ANALYSIS_DIR="/tmp/ordinaryfolk-analysis"
SCENE_CLIP="$ANALYSIS_DIR/scene_clips/scene_01.mp4"
COMP_ID="ReplicateScene01"
ATTEMPT="/tmp/scene-01-attempt-$$.mp4"

cd "/Users/maxguillabert/Downloads/index/video"

# Guard: TypeScript compiles
if ! npx tsc --noEmit 2>/dev/null; then
  echo "SCORE: 0"
  exit 1
fi

# Render just this scene
if ! npx remotion render src/index.ts "$COMP_ID" "$ATTEMPT" --codec h264 2>/dev/null; then
  echo "SCORE: 0"
  exit 1
fi

if [ ! -f "$ATTEMPT" ] || [ ! -f "$SCENE_CLIP" ]; then
  echo "SCORE: 0"
  exit 1
fi

# Scale to match
ATTEMPT_SCALED="/tmp/scene-01-scaled-$$.mp4"
ffmpeg -i "$ATTEMPT" -vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2"   -c:v libx264 -crf 18 "$ATTEMPT_SCALED" -y 2>/dev/null
ATTEMPT="$ATTEMPT_SCALED"

# SSIM comparison
MIN_DUR=$(python3 -c "
import subprocess, json
def get_dur(p):
    r = subprocess.run(['ffprobe','-v','quiet','-print_format','json','-show_format',p], capture_output=True, text=True)
    return float(json.loads(r.stdout)['format']['duration'])
print(min(get_dur('$SCENE_CLIP'), get_dur('$ATTEMPT')))
")

VIDEO_SSIM=$(ffmpeg -t "$MIN_DUR" -i "$SCENE_CLIP" -t "$MIN_DUR" -i "$ATTEMPT"   -lavfi ssim -f null - 2>&1 | grep "All:" | sed 's/.*All://' | awk '{print $1}' || echo "0")

# Keyframe SSIM (5 samples across the scene)
KF_SUM=0
KF_COUNT=0
for i in 0 1 2 3 4; do
  T=$(python3 -c "print(round(0.0 + 8.642 * $i / 5, 2))")
  ffmpeg -i "$SCENE_CLIP" -ss $(python3 -c "print(round(8.642 * $i / 5, 2))") -frames:v 1 /tmp/_skf_ref_$i.png -y 2>/dev/null || continue
  ffmpeg -i "$ATTEMPT" -ss $(python3 -c "print(round(8.642 * $i / 5, 2))") -frames:v 1 /tmp/_skf_att_$i.png -y 2>/dev/null || continue
  KF=$(magick compare -metric SSIM /tmp/_skf_ref_$i.png /tmp/_skf_att_$i.png /dev/null 2>&1 | head -1 | awk '{print $1}' || echo "0")
  KF_SUM=$(echo "$KF_SUM + $KF" | bc -l)
  KF_COUNT=$((KF_COUNT + 1))
done
KF_AVG=$(python3 -c "print($KF_SUM / max(1, $KF_COUNT))")

# Color similarity
COLOR=$(python3 -c "
import subprocess, math, os
def rgb(p):
    r=subprocess.run(['magick',p,'-resize','1x1!','-format','%[fx:mean.r],%[fx:mean.g],%[fx:mean.b]','info:-'],capture_output=True,text=True)
    try: return [float(x) for x in r.stdout.strip().split(',')]
    except: return [0,0,0]
scores=[]
for i in range(5):
    t=8.642*i/5
    ref='/tmp/_sc_ref.png'; att='/tmp/_sc_att.png'
    subprocess.run(['ffmpeg','-i','$SCENE_CLIP','-ss',str(t),'-frames:v','1','-vf','scale=64:-1',ref,'-y'],capture_output=True)
    subprocess.run(['ffmpeg','-i','$ATTEMPT','-ss',str(t),'-frames:v','1','-vf','scale=64:-1',att,'-y'],capture_output=True)
    if os.path.exists(ref) and os.path.exists(att):
        rr,ar=rgb(ref),rgb(att)
        d=math.sqrt(sum((a-b)**2 for a,b in zip(rr,ar)))
        scores.append(1-d/math.sqrt(3))
print(sum(scores)/len(scores) if scores else 0)
")

# Duration match
DUR_MATCH=$(python3 -c "
rd=float('$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$SCENE_CLIP")')
ad=float('$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "$ATTEMPT")')
print(min(rd,ad)/max(rd,ad) if max(rd,ad)>0 else 0)
")

SCORE=$(python3 -c "
s=(float('$VIDEO_SSIM')*0.40 + float('$KF_AVG')*0.35 + float('$COLOR')*0.15 + float('$DUR_MATCH')*0.10)*100
print(f'{s:.1f}')
")

# Write breakdown for agent
mkdir -p "$ANALYSIS_DIR"
cat > "$ANALYSIS_DIR/scene_01_breakdown.json" << JSONEOF
{
  "scene": 1,
  "score": $SCORE,
  "video_ssim": $VIDEO_SSIM,
  "keyframe_ssim": $KF_AVG,
  "color_match": $COLOR,
  "duration_match": $DUR_MATCH
}
JSONEOF

# Cleanup
rm -f "$ATTEMPT" "$ATTEMPT_SCALED" /tmp/_skf_*.png /tmp/_sc_*.png 2>/dev/null

echo "SCORE: $SCORE" >&2
echo "$SCORE"
