import { redirect } from 'next/navigation'
import type { Metadata } from 'next'
import { getSourceDisplayServer } from '@/lib/vision/sources-server'
import { getCategoryLabel } from '@/lib/vision/source-categories'

export const dynamic = 'force-dynamic'

interface Props {
  params: Promise<{ locale: string; sourceId: string; assetId: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { sourceId, assetId } = await params
  const source = await getSourceDisplayServer(sourceId)
  const marketName = decodeURIComponent(assetId).replace(/_/g, ' ')

  if (!source) return { title: 'Market Not Found' }

  const category = getCategoryLabel(source.category)
  const description = `${marketName} — trade predictions on ${source.name}. Category: ${category}. Live on Vision.`

  return {
    title: `${marketName} | ${source.name} | Vision`,
    description,
    openGraph: {
      title: `${marketName} — ${source.name}`,
      description,
      // OG image generated by opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title: `${marketName} — ${source.name}`,
      description,
    },
  }
}

export default async function MarketPage({ params }: Props) {
  const { locale, sourceId } = await params
  // Redirect to the source page — individual markets live within the source detail
  const prefix = locale === 'en' ? '' : `/${locale}`
  redirect(`${prefix}/source/${sourceId}`)
}
